### ISSUE TITLE
Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException

### ISSUE THREAD

**Issue by RaviPradad** [transistorsoft/flutter_background_geolocation#1015]
## Your Environment
* Plugin version: 4.8.3
* Platform: iOS or Android
* OS version: Android
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>
Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{5b327a9 u0 com.av.wynd/com.transistorsoft.locationmanager.service.ActivityRecognitionService}
       at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2245)
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2216)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

[com.av.wynd_issue_bf0aa132fee08d894d95a404d1a44d14_crash_session_6433CA0901D300013C31197A2C0A2567_DNE_0_v2_stacktrace.txt](https://github.com/transistorsoft/flutter_background_geolocation/files/11233570/com.av.wynd_issue_bf0aa132fee08d894d95a404d1a44d14_crash_session_6433CA0901D300013C31197A2C0A2567_DNE_0_v2_stacktrace.txt)

**Comment by christocracy** [comment]
This issue is well known among Android app developers and is not directly the problem of this plug-in.

this issue has been posted here in the issues many times before.  Search issues here for “* Context.startForegroundService() did not then call Service.startForeground()*”.
