### ISSUE TITLE
App crashs in release mode with an exception mentioning the plugin

### ISSUE THREAD

**Issue by iliraga** [transistorsoft/flutter_background_geolocation#1034]
## Your Environment
* Plugin version: 4.10.3
* Platform: Android
* OS version: Happens on any device (verified by the firebase cloud testing kit)
* Device manufacturer / model: *
* Flutter info (`flutter doctor`):

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.2.1 22D68 darwin-x64, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.78.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

class BgGeolocationConfig {
  /// Current config
  static Config? currentConfig;

  /// Desired accuracy
  static const desiredOdometerAccuracy = 70.0;

  /// Speed jump filter
  static final speedJumpfilter = 35.kmhToMps().toInt();

  /// Distance filter
  static const distanceFilter = 10.0;

  /// Default config
  static Config get defaultConfig => getConfig();

  /// Warmup config
  static Config get warmup => getConfig(isWarmup: true);

  /// Returns a config.
  ///
  /// Modifies the config with [extras] provided based on if it [isWarmup]
  /// and if it should produce [debug] logs
  static Config getConfig({
    bool isWarmup = false,
    bool debug = false,
    Json? extras,
  }) {
    extras ??= {};
    if (isWarmup) {
      extras['warmup'] = true;
    }

    return Config(
      /// Disable this otherwise will continuously call "pause" and
      /// "resume" events on Android
      ///
      /// See link below for a related issue
      /// https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/1073
      disableLocationAuthorizationAlert: Platform.isAndroid,

      // we need the highest possible accuracy
      desiredAccuracy: Config.DESIRED_ACCURACY_NAVIGATION,

      // make odometer only use locations with accuracy above desired for its calculations / updates
      desiredOdometerAccuracy: desiredOdometerAccuracy,

      /// deliver a location each ...
      /// from remote config it is 10 (meters) for both ios and android
      distanceFilter: distanceFilter,

      /// Disable the stop detection completely - we handle the stop / start state by our self.
      disableStopDetection: true,

      /// As long as the Background Geolocation is started we don't need any automatic stops
      pausesLocationUpdatesAutomatically: false,

      /// Debug when debugging is enabled
      /// (Way more logs and some sounds)
      debug: debug,

      /// Loglevel
      logLevel: debug ? Config.LOG_LEVEL_VERBOSE : Config.LOG_LEVEL_ERROR,

      /// Our desired GPS authorisation
      locationAuthorizationRequest: 'Always',

      backgroundPermissionRationale: PermissionRationale(
        title: 'Allow {applicationName} to access this device\'s location '
            'even when the app is closed.',
        message:
            'In order to track your activity in the background while in a run '
            'and the app is closed, please enable "Allow all the time" '
            'location permission.',
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel',
      ),

      /// Activity settings
      activityType: Config.ACTIVITY_TYPE_FITNESS,

      /// Don't go into background
      stopOnTerminate: isWarmup ? true : false,
      startOnBoot: false,
      foregroundService: false,

      // Persistence
      persistMode:
          isWarmup ? Config.PERSIST_MODE_NONE : Config.PERSIST_MODE_ALL,

      // Mark locations as extras
      extras: extras,
    );
  }

  /// Returns the [defaultConfig] with the provided [extras]
  static Config withExtras(Json extras) {
    final config = getConfig();
    config.extras = extras;
    return config;
  }
}


```

## Expected Behavior

The appp shouldn't crash.

## Actual Behavior

There is an immediate crash with our app. On iOS it works.

## Steps to Reproduce

1. Basically just create a build with `flutter run --release`
2. As soon as the device starts up it crashes with the exception below

The sample apps of the plugin work, so I know that the plugin is not causing this as of now, but maybe there is a known issue causing this.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
05-08 22:59:10.158  2535  3160 E memtrack: Couldn't load memtrack module
05-08 22:59:10.159  2535  3160 W android.os.Debug: failed to get memory consumption info: -1
05-08 22:59:10.471  3635  5491 D CustomFrequencyManagerService: FrequencyrequestList.getNextMaxCPUCoreRequest, index: 4
05-08 22:59:10.508  6299  6299 W FlutterActivityAndFragmentDelegate: A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
05-08 22:59:10.520  6299  6299 I zygote64: Rejecting re-init on previously-failed class java.lang.Class<oh.c>: java.lang.ExceptionInInitializerError: 
05-08 22:59:10.520  6299  6299 I zygote64: (Throwable with no stack trace)
05-08 22:59:10.520  6299  6299 I zygote64: 
05-08 22:59:10.521  6299  6299 D AndroidRuntime: Shutting down VM
05-08 22:59:10.521  6299  6299 E AndroidRuntime: FATAL EXCEPTION: main
05-08 22:59:10.521  6299  6299 E AndroidRuntime: Process: ch.irtech.actyvo.cyclingChallenges, PID: 6299
05-08 22:59:10.521  6299  6299 E AndroidRuntime: java.lang.NoClassDefFoundError: oh.c
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at oh.c.e0(Unknown Source:0)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at lh.a.G(BackgroundGeolocationModule.java:2)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at lh.a.onActivityStarted(BackgroundGeolocationModule.java:2)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.app.Application.dispatchActivityStarted(Application.java:231)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.app.Activity.onStart(Activity.java:1296)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at io.flutter.embedding.android.d.onStart(FlutterActivity.java:1)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7200)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2920)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6944)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
05-08 22:59:10.521  6299  6299 E AndroidRuntime: Caused by: java.lang.ExceptionInInitializerError
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at mh.i.<init>(LocationStreamHandler.java:2)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at lh.a.b0(BackgroundGeolocationModule.java:8)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at lh.b.onAttachedToActivity(FLTBackgroundGeolocationPlugin.java:1)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at io.flutter.embedding.engine.c.f(FlutterEngineConnectionRegistry.java:12)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:15)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at kj.a.a(GeneratedPluginRegister.java:4)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at io.flutter.embedding.android.d.m(FlutterActivity.java:2)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at io.flutter.embedding.android.e.p(FlutterActivityAndFragmentDelegate.java:8)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at io.flutter.embedding.android.d.onCreate(FlutterActivity.java:4)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7183)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        ... 9 more
05-08 22:59:10.521  6299  6299 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at ji.a.c(Unknown Source:27)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        at oh.c.<clinit>(Unknown Source:2)
05-08 22:59:10.521  6299  6299 E AndroidRuntime:        ... 22 more
05-08 22:59:10.524  3635  5491 D Debug   : !@DumpState : SHIP
05-08 22:59:10.524  3635  5491 D Debug   : !@DumpState : debug level:0x4f4c
05-08 22:59:10.524  3635  5491 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
05-08 22:59:10.524  3635  5491 W ActivityManager: crash : ch.irtech.actyvo.cyclingChallenges,0
05-08 22:59:10.525  3635  5491 W ActivityManager:   Force finishing activity ch.irtech.actyvo.cyclingChallenges/.MainActivity
05-08 22:59:10.525  3635  5491 W MultiScreenManagerService: moveTaskBackToDisplayIfNeeded(): root activity or app is null, task=TaskRecord{f54fec4d0 #20 A=ch.irtech.actyvo.cyclingChallenges U=0 StackId=1 sz=1}, rootActivity=null
05-08 22:59:10.525  3635  3635 D MdnieScenarioControlService: Listener Real Multi Window State : true
05-08 22:59:10.532  3635  3655 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 2600000  uid : 1000  pid : 3635  pkgName : AMS_APP_HOME@CPU_MIN@9
05-08 22:59:10.532  3635  3655 D ActivityManagerPerformance: AMP_acquire() HOME
05-08 22:59:10.537  3635  3656 I ActivityManager: Showing crash dialog for package ch.irtech.actyvo.cyclingChallenges u0
05-08 22:59:10.539  5956  5956 I DMT-SMReceiver: Received : com.samsung.android.sm.ACTION_ERROR
05-08 22:59:10.540  5956  5956 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1483 android.content.ContextWrapper.startService:663 android.content.ContextWrapper.startService:663 com.samsung.android.sm.common.SmartManagerReceiver.a:278 com.samsung.android.sm.common.SmartManagerReceiver.onReceive:125 
05-08 22:59:10.541  3635  3656 D ScrollView: initGoToTop
05-08 22:59:10.545  3635  3656 D RestrictionPolicy: isGoogleCrashReportAllowed : ret=true userId =0
05-08 22:59:10.549  3635  3656 E PhoneWindow_APM : : isCalledPackage return true
05-08 22:59:10.551  3635  7718 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-08 22:59:10.551  3635  3660 V MARsPolicyManager: handelAlertToastWindowStarted pkgName = android, userId = 0
05-08 22:59:10.552  3635  3655 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
05-08 22:59:10.553  3635  5065 D SamsungAlarmManager: setInexact Intent (T:3/F:0/AC:false) 20330505T225910 - CU:10015/CP:4503
05-08 22:59:10.553  3635  3656 D InputDispatcher: Focus entered window: 3635
05-08 22:59:10.554  3635  3656 D ViewRootImpl@bc5378[cyclingChallenges]: setView = DecorView@b0f4bb7[cyclingChallenges] TM=true MM=false
05-08 22:59:10.562  3635  3656 D ViewRootImpl@bc5378[cyclingChallenges]: dispatchAttachedToWindow
05-08 22:59:10.563  3635  3656 V WindowManager: Relayout Window{86e4a51 u0 Application Error: ch.irtech.actyvo.cyclingChallenges}: viewVisibility=0 req=676x337 WM.LayoutParams{(0,0)(wrapxwrap) gr=#11 sim=#120 ty=2003 fl=#1820002 pfl=0x110 fmt=-3 wanim=0x10302ec surfaceInsets=Rect(4, 4 - 4, 4) needsMenuKey=2 colorMode=0 naviIconColor=0}
05-08 22:59:10.566  3197  3197 I SurfaceFlinger: id=85 createSurf (684x345),1 flag=4, Application Error: ch.irtech.actyvo.cyclingChallenges#0
05-08 22:59:10.567  3635  3656 V Surface : sf_framedrop debug : 0x4f4c, game : false, logging : 0
05-08 22:59:10.569  3635  3656 D ViewRootImpl@bc5378[cyclingChallenges]: Relayout returned: old=[0,0][0,0] new=[22,495][698,832] result=0x7 surface={valid=true 489434972160} changed=true
05-08 22:59:10.571  5956  6367 V CrashedAppLogging: isMasterSwitchOff : false
05-08 22:59:10.572  3635  3656 D ViewRootImpl@bc5378[cyclingChallenges]: MSG_WINDOW_FOCUS_CHANGED 1
05-08 22:59:10.574  3635  3656 D WindowManager: set systemUiVisibility : systemUiFlags= 0x8 fullscreenStackSysUiFlags= 0x0
05-08 22:59:10.575  3635  4019 I OpenGLRenderer: Initialized EGL, version 1.4
05-08 22:59:10.575  3635  4019 D OpenGLRenderer: Swap behavior 2
05-08 22:59:10.575  3635  5065 D WindowManager: adjustSystemUiVisibilityLw : vis= 0x8
05-08 22:59:10.582  3635  7718 D SamsungAlarmManager: setInexact Intent (T:3/F:0/AC:false) 20330505T225910 - CU:10015/CP:2535

```

</details>

## Additional informations

I found an interesting issue here #1024  mentioning this issue, I tried the step there (increase the `playServicesLocationVersion` to `21.0.1`) but that didn't help.

* Debug builds work like a charm, so there must be something different in between.
* I changed the package name of the app a week ago, but ensured that all the required places were updated (including the package leading to the `MainActivity`)

Any ideas what this could be caused by?

**Comment by iliraga** [comment]
On the play consoles `pre-launch report details` the exception seems to be slightly different, but the core seems to be the same:

```
Exception java.lang.NoClassDefFoundError: oh.c
  at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance
  at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule.initializeLocationManager (BackgroundGeolocationModule.java:189)
  at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule.onActivityStarted (BackgroundGeolocationModule.java:1049)
  at android.app.Application.dispatchActivityStarted (Application.java:425)
  at android.app.Activity.dispatchActivityStarted (Activity.java:1260)
  at android.app.Activity.onStart (Activity.java:1747)
  at io.flutter.embedding.android.FlutterActivity.onStart (FlutterActivity.java:673)
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1433)
  at android.app.Activity.performStart (Activity.java:7980)
  at android.app.ActivityThread.handleStartActivity (ActivityThread.java:3578)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:221)
  at android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:201)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:173)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2220)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8016)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1076)
Caused by java.lang.ExceptionInInitializerError:
  at com.transistorsoft.flutter.backgroundgeolocation.streams.LocationStreamHandler.<init> (LocationStreamHandler.java:15)
  at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule.setActivity (BackgroundGeolocationModule.java:132)
  at com.transistorsoft.flutter.backgroundgeolocation.FLTBackgroundGeolocationPlugin.onAttachedToActivity (FLTBackgroundGeolocationPlugin.java:43)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add (FlutterEngineConnectionRegistry.java:154)
  at io.flutter.plugins.GeneratedPluginRegistrant.registerWith (GeneratedPluginRegistrant.java:54)
  at java.lang.reflect.Method.invoke
  at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins (GeneratedPluginRegister.java:80)
  at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine (FlutterActivity.java:1133)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach (FlutterActivityAndFragmentDelegate.java:206)
  at io.flutter.embedding.android.FlutterActivity.onCreate (FlutterActivity.java:495)
  at android.app.Activity.performCreate (Activity.java:7957)
  at android.app.Activity.performCreate (Activity.java:7946)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1307)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3530)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3707)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
  at com.transistorsoft.tslocationmanager.Application.ujBvejbwuJ (Application.java)
  at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<clinit>
```

I'm currenty trying to symbolize this `oh.c`- and other obfuscated parts in the stacktrace, but since my speciality lies more in the iOS stuff I'm having some trouble doing so. That might give additional insights.

**Comment by christocracy** [comment]
The Setup docs direct you to do this:

> shrinkResources false
> proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"

**Comment by christocracy** [comment]
The Setup docs direct you to do this:

> shrinkResources false
> proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"

**Comment by christocracy** [comment]
The Setup docs direct you to do this:

> shrinkResources false
> proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
