### ISSUE TITLE
Android devices in headless mode causes ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() 

### ISSUE THREAD

**Issue by stevegaunt** [transistorsoft/flutter_background_geolocation#1037]
## Your Environment
* Plugin version:4.10.1
* Platform:  Android
* OS version:13
* Device manufacturer / model:Galaxy S22+ (g0s) (SM-S906B)
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.3.1 22E772610a darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

```

## Expected Behavior

when the app is terminated , the headless task is started and geolocation events are emitted to the headless function.
## Actual Behavior

In general on most users devices , when the app is terminated , the headless task is started and performs has expected, just the few devices ( majority seem to be Samsung) we get this exception .   Also, it does seem to eventually respawn a new headless task later . 
## Steps to Reproduce

1.  not been able to reproduce .  the times manages to get the logs, just before the crash we see this in the logs
ℹ️  Location availability: true
05-10 17:13:28.303 INFO [TSLocationManager removeLocationUpdates] 
  🔴  Location-services: OFF
05-10 17:13:28.319 ERROR [BackgroundGeolocation$w0 uncaughtException] 
 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->

05-10 16:29:02.926 INFO [LocationRequestService handleLocationResult] 
╔═════════════════════════════════════════════
║ motionchange LocationResult: 1
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 55.612164,-2.767828 hAcc=110.0 et=+14d19h56m34s97ms alt=174.09999084472656 vAcc=19.645525 vel=0.004012239], age: 94ms, time: 1683732542832

05-10 16:29:02.938 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired motionchange position, isMoving: true
05-10 16:29:02.980 INFO [TSLocationManager requestLocationUpdates] 
  🎾  Location-services: ON
05-10 16:29:03.007 INFO [ActivityRecognitionService start] 
  🎾  Start motion-activity updates
05-10 16:29:03.028 INFO [b persist] 
  ✅  INSERT: b38bd0ca-4096-455b-aff8-f2d8b16f4396
05-10 16:41:19.853 INFO [LoggerFacade$a a] 
╔═════════════════════════════════════════════
║ TSLocationManager version: 3.4.0 (420)
╠═════════════════════════════════════════════
╟─ samsung SM-S906B @ 13 (flutter)
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": {
    "strategy": "jwt",
    "accessToken": "eyJra<redacted>",
    "refreshToken": "eyJjd<redacted>",
    "refreshUrl": "https:\/\/REMOVED\/auth\/refresh_tokens",
    "refreshPayload": {
      "refresh_token": "{refreshToken}",
      "username": "+REMOVED"
    },
    "refreshHeaders": {
      "Authorization": "Bearer {accessToken}"
    },
    "expires": -1
  },
  "autoSync": false,
  "autoSyncThreshold": 20,
  "backgroundPermissionRationale": {
    "title": "Allow {applicationName} to access this device's location even when closed or not in use?",
    "message": "This enables s",
    "positiveAction": "Change to \"{backgroundPermissionOptionLabel}\"",
    "negativeAction": ""
  },
  "batchSync": true,
  "configUrl": "",
  "debug": false,
  "deferTime": 0,
  "desiredAccuracy": -1,
  "desiredOdometerAccuracy": 100,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": false,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": false,
  "disableProviderChangeRecord": false,
  "disableStopDetection": false,
  "distanceFilter": 50,
  "elasticityMultiplier": 4,
  "enableHeadless": true,
  "enableTimestampMeta": false,
  "extras": {},
  "fastestLocationUpdateInterval": -1,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": true,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {
    "Device-Name": "SM-S906B",
    "Platform-Version": "13",
    "Device-Manufacturer": "samsung",
    "Platform": "Android",
    "x-api-key": "REMOVED",
    "App-Version": "1.0.5",
    "Language-Accept": "en_GB"
  },
  "headlessJobService": "com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": true,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 3,
  "logMaxDays": 5,
  "maxBatchSize": 500,
  "maxDaysToPersist": 7,
  "maxRecordsToPersist": 100000,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "",
    "text": "Location Service activated",
    "color": "",
    "channelName": "TSLocationManager",
    "channelId": "",
    "smallIcon": "",
    "largeIcon": "",
    "priority": 0,
    "sticky": false,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "https:\/\/REMOVED\/userLocationLog",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 1524442.875,
  "isFirstBoot": false,
  "didLaunchInBackground": false,
  "didDeviceReboot": false
}
05-10 16:41:19.855 INFO [TSConfig print] 
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="LSM6DSO Accelerometer", vendor="STM", version=15932, type=1, maxRange=78.4532, resolution=0.0023942017, power=0.2, minDelay=5000}
╟─ ✅  GYROSCOPE: {Sensor name="LSM6DSO Gyroscope", vendor="STM", version=1, type=4, maxRange=17.453032, resolution=6.1086525E-4, power=0.3, minDelay=5000}
╟─ ✅  MAGNETOMETER: {Sensor name="AK09918C Magnetometer", vendor="AKM", version=1, type=2, maxRange=1999.98, resolution=0.06, power=0.6, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Sensor", vendor="Samsung Electronics", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.3, minDelay=-1}
╚═════════════════════════════════════════════
05-10 16:41:19.864 INFO [BackgroundGeolocation <init>] 
  ✅  Google Play Services: connected (version code:12451000)
05-10 16:41:19.915 INFO [TSProviderManager startMonitoring] 
  🎾  Start monitoring location-provider changes
05-10 16:41:19.929 INFO [b persist] 
  ✅  INSERT: a40a0aa8-3a47-449c-ab4c-30639b56b00f
05-10 16:41:19.943 INFO [b persist] 
  ✅  INSERT: f797838e-48f9-4021-852b-ecc55e914e8c
05-10 16:46:53.303 INFO [HeartbeatService stop] 
  🔴  Stop heartbeat
05-10 16:46:53.315 INFO [TrackingService changePace] 
  🔵  setPace: true → true
05-10 16:46:53.315 INFO [ActivityRecognitionService handleActivityTransitionResult] 
╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🔴  EXIT: walking
╟─ 🎾  ENTER: in_vehicle
╚═════════════════════════════════════════════
05-10 16:46:53.329 INFO [TrackingService handleMotionChangeResult] 
╔═════════════════════════════════════════════
║ TrackingService motionchange: true
╠═════════════════════════════════════════════

05-10 16:46:53.369 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 1, requestId: 1]
05-10 16:46:53.374 INFO [ActivityRecognitionService start] 
  🎾  Start motion-activity updates
05-10 16:46:54.408 INFO [LocationRequestService handleLocationResult] 
╔═════════════════════════════════════════════
║ motionchange LocationResult: 1
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 55.612095,-2.768006 hAcc=98.4 et=+14d20h14m25s500ms alt=166.08478936883265 vAcc=11.29874 vel=0.0], age: 172ms, time: 1683733614235

05-10 16:50:54.686 INFO [LocationRequestService handleLocationResult] 
╔═════════════════════════════════════════════
║ motionchange LocationResult: 1
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 55.612095,-2.768013 hAcc=110.0 et=+14d20h18m25s775ms alt=178.10213382852177 vAcc=11.753336], age: 175ms, time: 1683733854510

05-10 16:50:54.709 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired motionchange position, isMoving: true
05-10 16:50:54.719 INFO [TSLocationManager requestLocationUpdates] 
  🎾  Location-services: ON
05-10 16:50:54.727 INFO [b persist] 
  ✅  INSERT: 09ff46ee-e9b2-4e85-bb76-201f398545db
05-10 16:50:54.732 INFO [ActivityRecognitionService start] 
  🎾  Start motion-activity updates
05-10 16:54:55.009 INFO [b persist] 
  ✅  INSERT: a2daeff2-3461-47ec-b463-116db141e6bd
05-10 16:54:55.014 INFO [b persist] 
  ✅  INSERT: 04a076ad-ffe8-4708-b550-5b9b93a10c95
05-10 17:03:46.942 INFO [LoggerFacade$a a] 
╔═════════════════════════════════════════════
║ TSLocationManager version: 3.4.0 (420)
╠═════════════════════════════════════════════
╟─ samsung SM-S906B @ 13 (flutter)
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": {
    "strategy": "jwt",
    "accessToken": "eyJra<redacted>",
    "refreshToken": "eyJjd<redacted>",
    "refreshUrl": "https:\/\/REMOVED\/auth\/refresh_tokens",
    "refreshPayload": {
      "refresh_token": "{refreshToken}",
      "username": "+REMOVED"
    },
    "refreshHeaders": {
      "Authorization": "Bearer {accessToken}"
    },
    "expires": -1
  },
  "autoSync": false,
  "autoSyncThreshold": 20,
  "backgroundPermissionRationale": {
    "title": "Allow {applicationName} to access this device's location even when closed or not in use?",
    "message": "This enables t"he automatic logging of visits for your jobs"",
    "positiveAction": "Change to \"{backgroundPermissionOptionLabel}\"",
    "negativeAction": ""
  },
  "batchSync": true,
  "configUrl": "",
  "debug": false,
  "deferTime": 0,
  "desiredAccuracy": -1,
  "desiredOdometerAccuracy": 100,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": false,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": false,
  "disableProviderChangeRecord": false,
  "disableStopDetection": false,
  "distanceFilter": 50,
  "elasticityMultiplier": 4,
  "enableHeadless": true,
  "enableTimestampMeta": false,
  "extras": {},
  "fastestLocationUpdateInterval": -1,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": true,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {
    "Device-Name": "SM-S906B",
    "Platform-Version": "13",
    "Device-Manufacturer": "samsung",
    "Platform": "Android",
    "x-api-key": "REMOVED",
    "App-Version": "1.0.5",
    "Language-Accept": "en_GB"
  },
  "headlessJobService": "com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": true,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 3,
  "logMaxDays": 5,
  "maxBatchSize": 500,
  "maxDaysToPersist": 7,
  "maxRecordsToPersist": 100000,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "",
    "text": "Location Service activated",
    "color": "",
    "channelName": "TSLocationManager",
    "channelId": "",
    "smallIcon": "",
    "largeIcon": "",
    "priority": 0,
    "sticky": false,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "https:\/\/REMOVED\/userLocationLog",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 1524442.875,
  "isFirstBoot": false,
  "didLaunchInBackground": false,
  "didDeviceReboot": false
}
05-10 17:03:46.943 INFO [LoggerFacade$a a] 
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="LSM6DSO Accelerometer", vendor="STM", version=15932, type=1, maxRange=78.4532, resolution=0.0023942017, power=0.2, minDelay=5000}
╟─ ✅  GYROSCOPE: {Sensor name="LSM6DSO Gyroscope", vendor="STM", version=1, type=4, maxRange=17.453032, resolution=6.1086525E-4, power=0.3, minDelay=5000}
╟─ ✅  MAGNETOMETER: {Sensor name="AK09918C Magnetometer", vendor="AKM", version=1, type=2, maxRange=1999.98, resolution=0.06, power=0.6, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Sensor", vendor="Samsung Electronics", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.3, minDelay=-1}
╚═════════════════════════════════════════════
05-10 17:03:46.951 INFO [BackgroundGeolocation <init>] 
  ✅  Google Play Services: connected (version code:12451000)
05-10 17:03:47.002 INFO [TSProviderManager startMonitoring] 
  🎾  Start monitoring location-provider changes
05-10 17:03:47.004 INFO [b persist] 
  ✅  INSERT: 71110271-2e71-4c98-b90b-ff3fef2f1586
05-10 17:03:47.036 INFO [b persist] 
  ✅  INSERT: e7c2b3ef-de05-4276-b882-56bb60dc2dd6
05-10 17:09:51.640 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: STOP_TIMEOUT in 300000ms (jobID: 2059034116)
05-10 17:09:51.652 INFO [b persist] 
  ✅  INSERT: 52349dac-58ed-4485-9816-fd491be61974
05-10 17:11:05.031 INFO [TrackingService performStopDetection] 
  ℹ️  Distance from stoppedAtLocation: -1866.7615
05-10 17:11:05.055 INFO [b persist] 
  ✅  INSERT: b618ea65-1b23-41d7-8ead-6b181a833e63
05-10 17:11:05.066 INFO [b persist] 
  ✅  INSERT: b27c70d7-0d82-4e94-b36c-2058475e3bce
05-10 17:12:05.380 INFO [HeartbeatService stop] 
  🔴  Stop heartbeat
05-10 17:12:05.391 INFO [TrackingService changePace] 
  🔵  setPace: true → true
05-10 17:12:05.393 INFO [ActivityRecognitionService handleActivityTransitionResult] 
╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🔴  EXIT: in_vehicle
╟─ 🎾  ENTER: still
╚═════════════════════════════════════════════
05-10 17:12:05.400 INFO [TrackingService handleMotionChangeResult] 
╔═════════════════════════════════════════════
║ TrackingService motionchange: true
╠═════════════════════════════════════════════

05-10 17:12:05.425 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 1, requestId: 1]
05-10 17:12:05.434 INFO [ActivityRecognitionService start] 
  🎾  Start motion-activity updates
05-10 17:13:13.433 INFO [ActivityRecognitionService handleActivityTransitionResult] 
╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🔴  EXIT: still
╟─ 🎾  ENTER: in_vehicle
╚═════════════════════════════════════════════
05-10 17:13:13.447 INFO [TSScheduleManager cancelOneShot] 
  ⏰ Cancel OneShot: STOP_TIMEOUT
05-10 17:13:28.157 INFO [TrackingService handleLocationAvailability] 
  ℹ️  Location availability: false
05-10 17:13:28.204 INFO [LocationRequestService handleLocationResult] 
╔═════════════════════════════════════════════
║ motionchange LocationResult: 1
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 55.612110,-2.767992 hAcc=52.4 et=+14d20h39m37s314ms alt=174.6999969482422 vAcc=13.485399], age: 82155ms, time: 1683735126050

05-10 17:13:28.214 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired motionchange position, isMoving: true
05-10 17:13:28.222 INFO [LocationRequestService handleLocationAvailability] 
  ℹ️  Location availability: false
05-10 17:13:28.237 INFO [TSLocationManager requestLocationUpdates] 
  🎾  Location-services: ON
05-10 17:13:28.244 INFO [ActivityRecognitionService start] 
  🎾  Start motion-activity updates
05-10 17:13:28.248 INFO [b persist] 
  ✅  INSERT: c615a0f0-7a80-45e0-9cc5-0b9f5203694f
05-10 17:13:28.280 INFO [TrackingService handleLocationAvailability] 
  ℹ️  Location availability: true
05-10 17:13:28.294 INFO [LocationRequestService handleLocationAvailability] 
  ℹ️  Location availability: true
05-10 17:13:28.303 INFO [TSLocationManager removeLocationUpdates] 
  🔴  Location-services: OFF
05-10 17:13:28.319 ERROR [BackgroundGeolocation$w0 uncaughtException] 
  ‼️  Uncaught Exception: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b7454e9 u0 com.yepic/com.transistorsoft.locationmanager.service.LocationRequestService}
{"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{"strategy":"jwt","accessToken":"removed","refreshUrl":"https:\/\/REMOVED\/auth\/refresh_tokens","refreshPayload":{"refresh_token":"{refreshToken}","username":"+REMOVED"},"refreshHeaders":{"Authorization":"Bearer {accessToken}"},"expires":-1},"autoSync":false,"autoSyncThreshold":20,"backgroundPermissionRationale":{"title":"Allow {applicationName} to access this device's location even when closed or not in use?","message":"This enables t","positiveAction":"Change to \"{backgroundPermissionOptionLabel}\"","negativeAction":""},"batchSync":true,"configUrl":"","debug":false,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableProviderChangeRecord":false,"disableStopDetection":false,"distanceFilter":50,"elasticityMultiplier":4,"enableHeadless":true,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":true,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{"Device-Name":"SM-S906B","Platform-Version":"13","Device-Manufacturer":"samsung","Platform":"Android","x-api-key":"REMOVED","App-Version":"1.0.5","Language-Accept":"en_GB"},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":true,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":3,"logMaxDays":5,"maxBatchSize":500,"maxDaysToPersist":7,"maxRecordsToPersist":100000,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","channelId":"","smallIcon":"","largeIcon":"","priority":0,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"https:\/\/REMOVED\/userLocationLog","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":1524442.875,"isFirstBoot":false,"didLaunchInBackground":false,"didDeviceReboot":false}

android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b7454e9 u0 com.yepic/com.transistorsoft.locationmanager.service.LocationRequestService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2245)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2216)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

05-10 17:33:00.112 DEBUG [LoggerFacade$a a] PID: 3
05-10 17:33:00.115 INFO [LoggerFacade$a a] 
╔═════════════════════════════════════════════
║ TSLocationManager version: 3.4.0 (420)
╠═════════════════════════════════════════════
╟─ samsung SM-S906B @ 13 (flutter)
{
  "activityRecognitionInterval": 10000,
  "allowIdenticalLocations": false,
  "authorization": {
    "strategy": "jwt",
    "accessToken": "eyJra<redacted>",
    "refreshToken": "eyJjd<redacted>",
    "refreshUrl": "https:\/\/removed\/auth\/refresh_tokens",
    "refreshPayload": {
      "refresh_token": "{refreshToken}",
      "username": "+RMEVOED"
    },
    "refreshHeaders": {
      "Authorization": "Bearer {accessToken}"
    },
    "expires": -1
  },
  "autoSync": false,
  "autoSyncThreshold": 20,
  "backgroundPermissionRationale": {
    "title": "Allow {applicationName} to access this device's location even when closed or not in use?",
    "message": "This enables ",
    "positiveAction": "Change to \"{backgroundPermissionOptionLabel}\"",
    "negativeAction": ""
  },
  "batchSync": true,
  "configUrl": "",
  "debug": false,
  "deferTime": 0,
  "desiredAccuracy": -1,
  "desiredOdometerAccuracy": 100,
  "disableAutoSyncOnCellular": false,
  "disableElasticity": false,
  "disableLocationAuthorizationAlert": false,
  "disableMotionActivityUpdates": false,
  "disableProviderChangeRecord": false,
  "disableStopDetection": false,
  "distanceFilter": 50,
  "elasticityMultiplier": 4,
  "enableHeadless": true,
  "enableTimestampMeta": false,
  "extras": {},
  "fastestLocationUpdateInterval": -1,
  "foregroundService": true,
  "geofenceInitialTriggerEntry": true,
  "geofenceModeHighAccuracy": true,
  "geofenceProximityRadius": 1000,
  "geofenceTemplate": "",
  "headers": {
    "Device-Name": "SM-S906B",
    "Platform-Version": "13",
    "Device-Manufacturer": "samsung",
    "Platform": "Android",
    "x-api-key": "REMOVED",
    "App-Version": "1.0.5",
    "Language-Accept": "en_GB"
  },
  "headlessJobService": "com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask",
  "heartbeatInterval": -1,
  "httpRootProperty": "location",
  "httpTimeout": 60000,
  "isMoving": true,
  "locationAuthorizationRequest": "Always",
  "locationTemplate": "",
  "locationTimeout": 60,
  "locationUpdateInterval": 1000,
  "locationsOrderDirection": "ASC",
  "logLevel": 3,
  "logMaxDays": 5,
  "maxBatchSize": 500,
  "maxDaysToPersist": 7,
  "maxRecordsToPersist": 100000,
  "method": "POST",
  "minimumActivityRecognitionConfidence": 75,
  "motionTriggerDelay": 0,
  "notification": {
    "layout": "",
    "title": "",
    "text": "Location Service activated",
    "color": "",
    "channelName": "TSLocationManager",
    "channelId": "",
    "smallIcon": "",
    "largeIcon": "",
    "priority": 0,
    "sticky": false,
    "strings": {},
    "actions": []
  },
  "params": {},
  "persist": true,
  "persistMode": 2,
  "schedule": [],
  "scheduleUseAlarmManager": false,
  "speedJumpFilter": 300,
  "startOnBoot": true,
  "stationaryRadius": 25,
  "stopAfterElapsedMinutes": 0,
  "stopOnStationary": false,
  "stopOnTerminate": false,
  "stopTimeout": 5,
  "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
  "url": "https:\/\/removed",
  "useSignificantChangesOnly": false,
  "enabled": true,
  "schedulerEnabled": false,
  "trackingMode": 1,
  "odometer": 1524442.875,
  "isFirstBoot": false,
  "didLaunchInBackground": false,
  "didDeviceReboot": false
}
05-10 17:33:00.119 INFO [LoggerFacade$a a] 
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="LSM6DSO Accelerometer", vendor="STM", version=15932, type=1, maxRange=78.4532, resolution=0.0023942017, power=0.2, minDelay=5000}
╟─ ✅  GYROSCOPE: {Sensor name="LSM6DSO Gyroscope", vendor="STM", version=1, type=4, maxRange=17.453032, resolution=6.1086525E-4, power=0.3, minDelay=5000}
╟─ ✅  MAGNETOMETER: {Sensor name="AK09918C Magnetometer", vendor="AKM", version=1, type=2, maxRange=1999.98, resolution=0.06, power=0.6, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Sensor", vendor="Samsung Electronics", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.3, minDelay=-1}
╚═════════════════════════════════════════════
05-10 17:33:00.120 DEBUG [AbstractService onDestroy] 
  🔴  TrackingService stopped
05-10 17:33:00.146 INFO [BackgroundGeolocation <init>] 
  ✅  Google Play Services: connected (version code:12451000)
05-10 17:33:00.234 INFO [TSProviderManager startMonitoring] 
  🎾  Start monitoring location-provider changes
05-10 17:51:42.547 DEBUG [LoggerFacade$a a] PID: 3
05-10 17:51:42.547 INFO [TSConfig print] 
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="LSM6DSO Accelerometer", vendor="STM", version=15932, type=1, maxRange=78.4532, resolution=0.0023942017, power=0.2, minDelay=5000}
╟─ ✅  GYROSCOPE: {Sensor name="LSM6DSO Gyroscope", vendor="STM", version=1, type=4, maxRange=17.453032, resolution=6.1086525E-4, power=0.3, minDelay=5000}
╟─ ✅  MAGNETOMETER: {Sensor name="AK09918C Magnetometer", vendor="AKM", version=1, type=2, maxRange=1999.98, resolution=0.06, power=0.6, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion Sensor", vendor="Samsung Electronics", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.3, minDelay=-1}
```

</details>

**Comment by christocracy** [comment]
This has been posted dozens of times in the past.  Please search before posting.

see wiki about this:
https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-ANR-%22Context.startForegroundService()-did-not-then-call-Service.startForeground()%22

Duplicate #1019

**Comment by stevegaunt** [comment]
Is this true also when running as a background process as the headless task??
This exception seems to be happening when running as a background task within the headless task, and we have already processed several events within our registered  headless task
BackgroundGeolocation.registerHeadlessTask(onBackgroundLocationHeadlessTask)

**Comment by stevegaunt** [comment]
It says on your docs when in strict mode 
You will want to observe StrictMode violations while your app is launched from a terminated state

Looking at the logs when this has happened, it looks like this is happening when running as a headless task.  the logs  does not look like the app is being launched.

is this possible this exception can happen when run-on soles as a background headless task??

**Comment by christocracy** [comment]
> is this possible this exception can happen when run-on soles as a background headless task??

Yes, of course!!  Now go analyze and fix your StrictMode violations.
