### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by choim4389** [transistorsoft/flutter_background_geolocation#1041]
## Your Environment
* Plugin version: 4.10.3
* Platform: iOS or Android : Android
* OS version: 13
* Device manufacturer / model: Galaxy S20
* Flutter info (`flutter doctor`):  flutter 3.7.5
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
      isMoving: true,
      desiredAccuracy: Platform.isAndroid ? bg.Config.DESIRED_ACCURACY_HIGH : bg.Config.DESIRED_ACCURACY_NAVIGATION,
      allowIdenticalLocations: true,
      stopOnTerminate: false,
      disableStopDetection: true,
      disableMotionActivityUpdates: true,
      startOnBoot: true,
      pausesLocationUpdatesAutomatically: false,
      persistMode: bg.Config.PERSIST_MODE_LOCATION,
      maxRecordsToPersist: 1,
      locationAuthorizationRequest: 'WhenInUse',
      logLevel: kReleaseMode ? bg.Config.LOG_LEVEL_OFF : bg.Config.LOG_LEVEL_VERBOSE,
```

## Context
crashlytics report this issue.

```
Fatal Exception: java.lang.NumberFormatException: For input string: "2024-05-16T03:26:35+09:00"
       at java.lang.Long.parseLong(Long.java:594)
       at java.lang.Long.valueOf(Long.java:808)
       at com.transistorsoft.locationmanager.config.TSAuthorization.applyResponseData(:143)
       at com.transistorsoft.locationmanager.config.TSAuthorization._onSuccess(:32)
       at com.transistorsoft.locationmanager.config.TSAuthorization.access$800()
       at com.transistorsoft.locationmanager.config.TSAuthorization$a.onResponse(:41)
       at okhttp3.RealCall$AsyncCall.run(RealCall.java:60)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
```
I can't find how to reproduce it. It seems to be rare case.
</details>

**Comment by choim4389** [comment]
Oh, should `expires` be a long?

**Comment by christocracy** [comment]
>  (which is supposed to be a long value, not String.

That’s exactly what I said.
