### ISSUE TITLE
Getting ANRs on Crashlytics on daily basis

### ISSUE THREAD

**Issue by adn9990** [transistorsoft/flutter_background_geolocation#1061]
## Your Environment
* Plugin version: 
* Platform: iOS or Android : Android
* OS version: 12, 13
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->

main (native):tid=1 systid=29620 
#00 pc 0x79db0 libc.so (syscall + 32) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
#01 pc 0x3a8ff4 libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 140) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#02 pc 0x77fa34 libart.so (artJniMethodEnd + 204) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#03 pc 0x20facc libart.so (art_jni_method_end + 12) (BuildId: 4c9b59b74ca9272f710a71137164c349)
       at android.os.BinderProxy.transactNative(Native method)
       at android.os.BinderProxy.transact(BinderProxy.java:672)
       at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:5919)
       at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:490)
       at android.app.PendingIntent.getActivity(PendingIntent.java:471)
       at android.app.PendingIntent.getActivity(PendingIntent.java:435)
       at com.transistorsoft.locationmanager.notification.TSLocalNotification.build(unavailable:125)
       at com.transistorsoft.locationmanager.service.ForegroundNotification.build(unavailable)
       at com.transistorsoft.locationmanager.service.AbstractService.doStartForeground(unavailable:18)
       at com.transistorsoft.locationmanager.service.AbstractService.start(unavailable:8)
       at com.transistorsoft.locationmanager.service.TrackingService.onStartCommand(unavailable:1)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4912)
       at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(unavailable)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2335)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8380)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)



main (native):tid=1 systid=25928 
#00 pc 0x79db0 libc.so (syscall + 32) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
#01 pc 0x3a8ff4 libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 140) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#02 pc 0x77fa34 libart.so (artJniMethodEnd + 204) (BuildId: 4c9b59b74ca9272f710a71137164c349)
#03 pc 0x20facc libart.so (art_jni_method_end + 12) (BuildId: 4c9b59b74ca9272f710a71137164c349)
       at android.os.BinderProxy.transactNative(Native method)
       at android.os.BinderProxy.transact(BinderProxy.java:672)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6112)
       at android.app.Service.startForeground(Service.java:743)
       at com.transistorsoft.locationmanager.service.AbstractService.doStartForeground(unavailable:22)
       at com.transistorsoft.locationmanager.service.AbstractService.start(unavailable:8)
       at com.transistorsoft.locationmanager.service.TrackingService.onStartCommand(unavailable:1)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4912)
       at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(unavailable)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2335)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8380)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)



main (native):tid=1 systid=6021 
#00 pc 0xd0ffc libc.so (__ioctl + 12) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
#01 pc 0x87cb8 libc.so (ioctl + 160) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
#02 pc 0x5f384 libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 284) (BuildId: e715d326cdaa54d19cd16928aec8d5bc)
#03 pc 0x605e0 libbinder.so (android::IPCThreadState::waitForResponse(android::Parcel*, int*) + 76) (BuildId: e715d326cdaa54d19cd16928aec8d5bc)
#04 pc 0x6031c libbinder.so (android::IPCThreadState::transact(int, unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 224) (BuildId: e715d326cdaa54d19cd16928aec8d5bc)
#05 pc 0x57ab8 libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 308) (BuildId: e715d326cdaa54d19cd16928aec8d5bc)
#06 pc 0x179860 libandroid_runtime.so (android_os_BinderProxy_transact(_JNIEnv*, _jobject*, int, _jobject*, _jobject*, int) + 400) (BuildId: 5ee67362e71f1a426ab4a7367412e7d2)
       at android.os.BinderProxy.transactNative(Native method)
       at android.os.BinderProxy.transact(BinderProxy.java:672)
       at android.app.INotificationManager$Stub$Proxy.getNotificationChannel(INotificationManager.java:3695)
       at android.app.NotificationManager.getNotificationChannel(NotificationManager.java:947)
       at com.transistorsoft.locationmanager.service.ForegroundNotification.createNotificationChannel(unavailable:91)
       at com.transistorsoft.locationmanager.notification.TSLocalNotification.build(unavailable:1)
       at com.transistorsoft.locationmanager.service.ForegroundNotification.build(unavailable)
       at com.transistorsoft.locationmanager.service.AbstractService.doStartForeground(unavailable:18)
       at com.transistorsoft.locationmanager.service.AbstractService.start(unavailable:8)
       at com.transistorsoft.locationmanager.service.TrackingService.onStartCommand(unavailable:1)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4912)
       at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(unavailable)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2335)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8380)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
       
       
       
       main (native):tid=1 systid=17793 
#00 pc 0xcad6c libc.so (__epoll_pwait + 12) (BuildId: bbbdeb7c87c74f1491f92c6e605095b0)
#01 pc 0x17ea8 libutils.so (android::Looper::pollInner(int) + 184) (BuildId: 35086774ccd6a31df507943fb218149a)
#02 pc 0x17d84 libutils.so (android::Looper::pollOnce(int, int*, int*, void**) + 116) (BuildId: 35086774ccd6a31df507943fb218149a)
#03 pc 0x154fa4 libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int) + 48) (BuildId: f5282a9c8dd6d2535a490ff65f1319c8)
#04 pc 0x461554 libart.so (art_quick_generic_jni_trampoline + 148) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
#05 pc 0x2060f10 memfd:jit-zygote-cache (android.os.MessageQueue.next + 224)
#06 pc 0x29cd8d4 memfd:jit-zygote-cache (android.os.Looper.loopOnce + 100)
#07 pc 0x208c610 memfd:jit-zygote-cache (android.os.Looper.loop + 656)
#08 pc 0x209398 libart.so (nterp_helper + 152) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
#09 pc 0x1b6608 framework.jar (android.app.ActivityThread.main + 252)
#10 pc 0x457e00 libart.so (art_quick_invoke_static_stub + 576) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
#11 pc 0x48c038 libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long) + 1560) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
#12 pc 0x48b9f8 libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277) + 48) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
#13 pc 0x461554 libart.so (art_quick_generic_jni_trampoline + 148) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
#14 pc 0x2d9d508 memfd:jit-zygote-cache (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 136)
#15 pc 0x20b0d4 libart.so (nterp_helper + 7636) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
#16 pc 0x2be54a framework.jar (com.android.internal.os.ZygoteInit.main + 694)
#17 pc 0x457e00 libart.so (art_quick_invoke_static_stub + 576) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
#18 pc 0x58bc24 libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list) + 912) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
#19 pc 0x609b6c libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list) + 172) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
#20 pc 0xb2bf8 libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...) + 124) (BuildId: f5282a9c8dd6d2535a490ff65f1319c8)
#21 pc 0xbf0fc libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool) + 840) (BuildId: f5282a9c8dd6d2535a490ff65f1319c8)
#22 pc 0x2684 app_process64 (main + 1580) (BuildId: b66800b6ac5d87b7c521c256d6340555)
#23 pc 0x720c4 libc.so (__libc_init + 100) (BuildId: bbbdeb7c87c74f1491f92c6e605095b0)
       at android.os.MessageQueue.nativePollOnce(Native method)
       at android.os.MessageQueue.next(MessageQueue.java:339)
       at android.os.Looper.loopOnce(Looper.java:179)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
       
       
       
       main (native):tid=1 systid=24039 
#00 pc 0xd0ffc libc.so (__ioctl + 12) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
#01 pc 0x87cb8 libc.so (ioctl + 160) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
#02 pc 0x5f384 libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 284) (BuildId: e715d326cdaa54d19cd16928aec8d5bc)
#03 pc 0x605e0 libbinder.so (android::IPCThreadState::waitForResponse(android::Parcel*, int*) + 76) (BuildId: e715d326cdaa54d19cd16928aec8d5bc)
#04 pc 0x6031c libbinder.so (android::IPCThreadState::transact(int, unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 224) (BuildId: e715d326cdaa54d19cd16928aec8d5bc)
#05 pc 0x57ab8 libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 308) (BuildId: e715d326cdaa54d19cd16928aec8d5bc)
#06 pc 0x179860 libandroid_runtime.so (android_os_BinderProxy_transact(_JNIEnv*, _jobject*, int, _jobject*, _jobject*, int) + 400) (BuildId: 5ee67362e71f1a426ab4a7367412e7d2)
       at android.os.BinderProxy.transactNative(Native method)
       at android.os.BinderProxy.transact(BinderProxy.java:672)
       at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2042)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1827)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1108)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1079)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:442)
       at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity$a.run(unavailable:4)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8380)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

</details>

**Comment by christocracy** [comment]
**Ignored Issue Template**

Plugin version:
Platform: iOS or Android : Android
OS version: 12, 13
Device manufacturer / model:
Flutter info (flutter doctor):
Plugin config:

See the Wiki:
https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-ANR-%22Context.startForegroundService()-did-not-then-call-Service.startForeground()%22

**Comment by christocracy** [comment]
The published `/example` app (in this repo), running `v4.10.1`, has had one ANR in the past 60 days.  And it was related to the debug sound FX player (`TSMediaPlayer`).

<img width="1794" alt="Screenshot 2023-06-02 at 9 49 27 AM" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/1b13c3c2-2529-42de-a8c9-08fe57e6b379">

**Comment by adn9990** [comment]
Any configuration i need to change
