### ISSUE TITLE
Android crash if app is running in background - Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by xunreal75** [transistorsoft/flutter_background_geolocation#1103]
## Your Environment
* Plugin version: 4.12.0
* Platform:  Android
* OS version: 13 TP1A.220624.14
* Device manufacturer / model: Red Note 10
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale de-DE)
    • Flutter version 3.10.6 on channel stable at /Users/..../development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (vor 5 Wochen), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/...../Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_SDK_ROOT = /Users/...../Library/Android/sdk
    • Java binary at: /Users/....../Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/...../Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.5)
    • IntelliJ at /Users/..../Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9392.3

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.5)
    • IntelliJ at /Users/....../Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9392.1/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (6 available)
   ...
[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Expected Behavior
App should not crash

## Steps to Reproduce

1. Flutter pubspec.yaml - upgrade V4.11.1 to V4.12.0
2. Compile and start app
3. switch App to Background
4. wait a while -> App is closed and crashed with 
```
E/TSLocationManager(10037): [c.t.l.a.BackgroundGeolocation$x0 uncaughtException] 
E/TSLocationManager(10037):   ‼️  Uncaught Exception: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9f2a8cf u0 de.bladenight.bladenight_app_flutter/com.transistorsoft.locationmanager.service.LocationRequestService}
E/TSLocationManager(10037): 
```
6.  switch back to V 4.11.1 and app is running  without crashing

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
I/flutter (10037): LocationProvider, _onLocation, _onLocation [Location {odometer: 14777.5, activity: {confidence: 100, type: still}, extras: {}, battery: {level: 1.0, is_charging: true}, uuid: cdb354e7-d0f5-4593-9f28-85c8d2e5edb5, age: 802, coords: {altitude: 561.6, heading: -1.0, latitude: 48.1647157, accuracy: 16.7, heading_accuracy: -1.0, altitude_accuracy: 1.7, speed_accuracy: -1.0, speed: -1.0, age: 806, longitude: 11.5284539, ellipsoidal_altitude: 561.6}, is_moving: false, timestamp: 2023-08-20T08:11:55.634Z}], LogLevel.TRACE, 20/08/2023 10:11:56 null 1692519116492
E/TSLocationManager(10037): [c.t.l.a.BackgroundGeolocation$x0 uncaughtException] 
E/TSLocationManager(10037):   ‼️  Uncaught Exception: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9f2a8cf u0 de.bladenight.bladenight_app_flutter/com.transistorsoft.locationmanager.service.LocationRequestService}
E/TSLocationManager(10037): {"activityRecognitionInterval":10000,"allowIdenticalLocations":true,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"backgroundPermissionRationale":{"title":"Standort - Immer zulassen","message":"Standort 'Während der Benutzung' ist eingestellt. Daher ist keine Hintergrundaktualisierung aktiviert. Um die Darstellung des BladeNight-Zuges so genau wie möglich zu bekommen und deine Postion ohne Einschränkung mit Freunden zu teilen, bitten wir Dich die App offen halten oder die Einstellung auf 'Immer zulassen' zu ändern. Danke.","positiveAction":"Öffne Systemeinstellungen","negativeAction":"Abbruch"},"batchSync":false,"configUrl":"","debug":false,"deferTime":0,"desiredAccuracy":-2,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableProviderChangeRecord":false,"disableStopDetection":false,"distanceFilter":0.5,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":60,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Any","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":3,"logMaxDays":1,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","channelId":"","smallIcon":"","largeIcon":"","priority":0,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":0,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":false,"stationaryRadius":25,"stopAfterElapsedMinutes":3600,"stopOnStationary":false,"stopOnTerminate":true,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":14777.5185546875,"isFirstBoot":false,"didLaunchInBackground":false,"didDeviceReboot":false}
E/TSLocationManager(10037): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9f2a8cf u0 de.bladenight.bladenight_app_flutter/com.transistorsoft.locationmanager.service.LocationRequestService}
E/TSLocationManager(10037): 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2118)
E/TSLocationManager(10037): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2089)
E/TSLocationManager(10037): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
E/TSLocationManager(10037): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2354)
E/TSLocationManager(10037): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/TSLocationManager(10037): 	at android.os.Looper.loopOnce(Looper.java:211)
E/TSLocationManager(10037): 	at android.os.Looper.loop(Looper.java:300)
E/TSLocationManager(10037): 	at android.app.ActivityThread.main(ActivityThread.java:8227)
E/TSLocationManager(10037): 	at java.lang.reflect.Method.invoke(Native Method)
E/TSLocationManager(10037): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/TSLocationManager(10037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Lost connection to device.

```

</details>

**Comment by christocracy** [comment]
I need all true logs leading up to the uncaught exception.

**Comment by christocracy** [comment]
Use LOG_LEVEL_VERBOSE

**Comment by christocracy** [comment]
>As attachment the full log.

What attachment?? You can’t send file-attachment in an **email reply** to a GitHub issue.

you have to visit the issue on the web and drag/drop the attachment onto the TEXTAREA.

**Comment by christocracy** [comment]
Can generate a fresh new Flutter *hello_world* app that reproduces this?  I see you're likely executing `.getCurrentPosition()` in a `Timer`.

**Comment by xunreal75** [comment]
Yes the timer is triggered to update an procession continuously on server.
I'll create a clean Flutter project this week and check it out. 
On iOS is all working fine.

**Comment by christocracy** [comment]
There are better ways to do that than running `getCurrentPosition()` in a `Timer`.

I would do this:
```dart
await BackgroundGeolocation.setConfig(Config(
  distanceFilter: 0, 
  locationUpdateInterval: 1000,
  stopTimeout:  1000 // <-- a very long stopTimeout 
  disableStopDetection: true // <-- Don't interrupt location updates when Motion API says "still"
));
await BackgroundGeolocation.changePace(true);
```

**Comment by christocracy** [comment]
I think with your `Timer` aggressively calling `.getCurrentPosition()`, it may exposed a flaw that can be corrected.

It's like *Donkey Kong* throwing barrels (*ForegroundService start/stops*).

<img width="486" alt="Screenshot 2023-08-21 at 7 59 56 AM" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/14999/04ac6577-f879-4f66-a055-de28108fed0b">

Before the crash, I note there was a *Heartbeat event* and two simultaneous `LocationRequests` running (which it's designed to handle, but their may by a flaw that can be corrected).

```
08-21 10:39:31.771 DEBUG [HeartbeatService$a run] ❤️
08-21 10:39:31.789 DEBUG [AbstractService finish] ⚙️︎  finish HeartbeatService [eventCount: 0, sticky: false]
08-21 10:39:31.814 INFO [TSLocationManager logSingleLocationResult] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 348 (3905ms old)
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 48.164714,11.528452 hAcc=17.761 et=+12h3m41s180ms alt=561.6000366210938 vAcc=1.7054092 vel=0.039901145], time: 1692607167908

08-21 10:39:31.816 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 17.079
08-21 10:39:31.826 DEBUG [c h] 
  ℹ️  LocationAuthorization: Permission granted
08-21 10:39:31.847 DEBUG [AbstractService start] 
  🎾  LocationRequestService [eventCount: 1]
08-21 10:39:31.848 INFO [SingleLocationRequest startUpdatingLocation] 
  🔵  [SingleLocationRequest start, action: 2, requestId: 348]
08-21 10:39:31.851 DEBUG [AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
08-21 10:39:32.048 DEBUG [AbstractService onDestroy] 
  🔴  HeartbeatService stopped
08-21 10:39:32.248 DEBUG [AbstractService start] 
  🎾  LocationRequestService [eventCount: 1]
08-21 10:39:32.251 INFO [TSLocationManager logSingleLocationResult] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 347 (129ms old)
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 48.164716,11.528455 hAcc=17.305 et=+12h3m45s393ms alt=561.6000366210938 vAcc=1.5951366 vel=0.06219776], time: 1692607172121

08-21 10:39:32.265 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
08-21 10:39:32.266 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 17.079
08-21 10:39:32.267 DEBUG [AbstractService start] 
  🎾  LocationRequestService [eventCount: 2]
08-21 10:39:32.288 DEBUG [AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 1, sticky: false]
08-21 10:39:32.288 INFO [TSLocationManager logSingleLocationResult] 
╔═════════════════════════════════════════════
║ getCurrentPosition LocationResult: 348 (167ms old)
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 48.164716,11.528455 hAcc=17.305 et=+12h3m45s393ms alt=561.6000366210938 vAcc=1.5951366 vel=0.06219776], time: 1692607172121

08-21 10:39:32.292 INFO [b persist] 
  ✅  INSERT: 74ed5f09-673b-43ab-a1ce-46a92bc86bc7
08-21 10:39:32.294 DEBUG [AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
08-21 10:39:32.306 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired current position
08-21 10:39:32.306 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 17.079
08-21 10:39:32.316 DEBUG [AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
08-21 10:39:32.317 INFO [b persist] 
  ✅  INSERT: 67b5717e-cea8-4263-805a-e4f91e979a0b
08-21 10:39:32.324 DEBUG [AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
08-21 10:39:32.324 DEBUG [AbstractService onDestroy] 
  🔴  LocationRequestService stopped
08-21 10:39:32.341 ERROR [BackgroundGeolocation$x0 uncaughtException] 
  ‼️  Uncaught Exception: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3bb037 u0 de.bladenight.bladenight_app_flutter/com.transistorsoft.locationmanager.service.LocationRequestService}
```

**Comment by xunreal75** [comment]
Hi

I implemeted for Android your suggestion and it looks good since about 50 minutes. 
On iOS (were is no problem) I run the timer with getCurrentPosition because the locationUpdateInterval option is only for Android.

```dart
await BackgroundGeolocation.setConfig(Config(
  distanceFilter: 0, 
  locationUpdateInterval: 1000,
  stopTimeout:  1000 // <-- a very long stopTimeout 
  disableStopDetection: true // <-- Don't interrupt location updates when Motion API says "still"
));
await BackgroundGeolocation.changePace(true);
```

**Comment by christocracy** [comment]
When you set iOS `distanceFilter: 0`, it returns a location as fast as possible (about every second).  You don't need a`Timer` with iOS.

**Comment by christocracy** [comment]
I'm abusing the plugin calling `.getCurrentPosition()` every second (in addition to simulating `background_fetch` events, which also call `.getCurrenetPosition()`).  I cannot make it fail.

```dart
mTimer = Timer.periodic(const Duration(seconds: 1), (timer) {
      print(timer.tick);
      bg.BackgroundGeolocation.getCurrentPosition(
        persist: false,
        samples: 2
      );
    });
```
