### ISSUE TITLE
compatibility problems with two other packages

### ISSUE THREAD

**Issue by Abubakarshaikh** [transistorsoft/flutter_background_geolocation#1132]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):[✓] Flutter (Channel stable, 3.10.5, on macOS 13.2 22D49 darwin-x64, locale
en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.82.1)
[✓] Connected device (2 available)
[✓] Network resources
• No issues found!

Plugin config:
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      // distanceFilter: newDistance,
      // locationUpdateInterval: 60000,
      distanceFilter: 10.0,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: true,
      // disableElasticity: ,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      enableHeadless: true,
      backgroundPermissionRationale: bg.PermissionRationale(
        title:
            "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
        message:
            "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
        positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
        negativeAction: 'Cancel',
      ),
    );


## Expected Behavior
<!--- Tell us what should happen -->

## Actual Behavior
<!--- Tell us what happens instead -->

## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- What were you trying to do? -->

## Debug logs
<!-- include iOS / Android logs
- ios XCode logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat -s TSLocationManager
-->E/TSLocationManager(18942): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~kezSw3r0rytX-nB1WP0Yug==/com.salesflo.core.multiplatform.app-9CpAYtcT2VMp3VegZj_YWA==/base.apk)
E/TSLocationManager(18942):     at com.transistorsoft.xms.g.location.FusedLocationProviderClient.getLastLocation(Unknown Source:50)
E/TSLocationManager(18942):     at com.transistorsoft.locationmanager.location.TSLocationManager.getLastLocation(Unknown Source:20)
E/TSLocationManager(18942):     at com.transistorsoft.locationmanager.location.TSLocationManager.getCurrentPosition(Unknown Source:8)
E/TSLocationManager(18942):     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$i.run(Unknown Source:12)
E/TSLocationManager(18942):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/TSLocationManager(18942):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/TSLocationManager(18942):     at java.lang.Thread.run(Thread.java:923)
I/Process (18942): Sending signal. PID: 18942 SIG: 9
Lost connection to device.
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> Plugin version:

Ignored issue template

**Comment by christocracy** [comment]
Duplicate #933.

This issue is *well-known* and has been posted *many* times before.  Please [search issues: "IncompatibleClassChangeError"](https://github.com/transistorsoft/flutter_background_geolocation/issues?q=IncompatibleClassChangeError) *before* posting.
