### ISSUE TITLE
App is killed itself

### ISSUE THREAD

**Issue by pradhansoubhagya** [transistorsoft/flutter_background_geolocation#1138]
## Your Environment
* Plugin version:4.13.0
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE

```@override
  void initState() {
    // TODO: implement initState
    super.initState();
    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        distanceFilter: 0.5,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        reset: true
    )).then((bg.State state) {
      print('BackgroundGeolocation is ready: $state');

      // Start location tracking.
      bg.BackgroundGeolocation.start();
    });
  }

## Expected Behavior
App should keep opened after allowing all the permission

## Actual Behavior
E/AndroidRuntime(27546): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~C0S-0wJfsL8_SEjGHBhFeQ==/io.growith.sky_app-zDI5JzisZvHAxO_P2mZzQw==/base.apk!classes2.dex)
E/AndroidRuntime(27546): 	at com.transistorsoft.xms.g.location.FusedLocationProviderClient.getLastLocation(Unknown Source:50)
E/AndroidRuntime(27546): 	at com.transistorsoft.locationmanager.location.TSLocationManager.getLastLocation(Unknown Source:20)
E/AndroidRuntime(27546): 	at com.transistorsoft.locationmanager.location.TSLocationManager.onProviderChange(Unknown Source:195)
E/AndroidRuntime(27546): 	at com.transistorsoft.locationmanager.provider.TSProviderManager.a(Unknown Source:84)
E/AndroidRuntime(27546): 	at com.transistorsoft.locationmanager.provider.TSProviderManager.onConnectivityChange(Unknown Source:17)
E/AndroidRuntime(27546): 	at com.transistorsoft.locationmanager.http.HttpService.a(Unknown Source:8)
E/AndroidRuntime(27546): 	at com.transistorsoft.locationmanager.http.HttpService.a(Unknown Source:0)
E/AndroidRuntime(27546): 	at com.transistorsoft.locationmanager.http.HttpService$g.onAvailable(Unknown Source:6)
E/AndroidRuntime(27546): 	at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3932)
E/AndroidRuntime(27546): 	at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3914)
E/AndroidRuntime(27546): 	at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:4241)
E/AndroidRuntime(27546): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27546): 	at android.os.Looper.loopOnce(Looper.java:210)
E/AndroidRuntime(27546): 	at android.os.Looper.loop(Looper.java:299)
E/AndroidRuntime(27546): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/AndroidRuntime(27546): FATAL EXCEPTION: pool-3-thread-2
E/AndroidRuntime(27546): Process: io.growith.sky_app, PID: 27546
E/AndroidRuntime(27546): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gms.location.ActivityRecognitionClient' appears in /data/app/~~C0S-0wJfsL8_SEjGHBhFeQ==/io.growith.sky_app-zDI5JzisZvHAxO_P2mZzQw==/base.apk!classes2.dex)
E/AndroidRuntime(27546): 	at com.transistorsoft.xms.g.location.ActivityRecognitionClient.requestActivityUpdates(Unknown Source:50)
E/AndroidRuntime(27546): 	at com.transistorsoft.locationmanager.service.ActivityRecognitionService.start(Unknown Source:78)
E/AndroidRuntime(27546): 	at com.transistorsoft.locationmanager.service.TrackingService.start(Unknown Source:49)
E/AndroidRuntime(27546): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$z0.run(Unknown Source:145)
E/AndroidRuntime(27546): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime(27546): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime(27546): 	at java.lang.Thread.run(Thread.java:1012)
W/pool-3-thread-2(27546): type=1400 audit(0.0:1764994): avc: denied { search } for name="miuilog" dev="dm-42" ino=1241481 scontext=u:r:untrusted_app_30:s0:c154,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=io.growith.sky_app
W/ConnectivityThr(27546): type=1400 audit(0.0:1764995): avc: denied { search } for name="miuilog" dev="dm-42" ino=1241481 scontext=u:r:untrusted_app_30:s0:c154,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=io.growith.sky_app
W/pool-3-thread-2(27546): type=1400 audit(0.0:1764996): avc: denied { search } for name="miuilog" dev="dm-42" ino=1241481 scontext=u:r:untrusted_app_30:s0:c154,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=io.growith.sky_app
W/ConnectivityThr(27546): type=1400 audit(0.0:1764997): avc: denied { search } for name="miuilog" dev="dm-42" ino=1241481 scontext=u:r:untrusted_app_30:s0:c154,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=io.growith.sky_app
W/OOMEventManagerFK(27546): Failed to mkdir /data/miuilog/stability/memleak/heapdump/
W/OOMEventManagerFK(27546): Failed to mkdir /data/miuilog/stability/memleak/heapdump/
E/TSLocationManager(27546): [c.t.l.a.BackgroundGeolocation$w0 uncaughtException] 
E/TSLocationManager(27546):   ‼️  Uncaught Exception: Found interface com.google.android.gms.location.ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gms.location.ActivityRecognitionClient' appears in /data/app/~~C0S-0wJfsL8_SEjGHBhFeQ==/io.growith.sky_app-zDI5JzisZvHAxO_P2mZzQw==/base.apk!classes2.dex)
E/TSLocationManager(27546): {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"backgroundPermissionRationale":{"title":"Allow {applicationName} to access this device's location even when closed or not in use?","message":"[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.","positiveAction":"Change to \"{backgroundPermissionOptionLabel}\"","negativeAction":""},"batchSync":false,"configUrl":"","debug":true,"deferTime":0,"desiredAccuracy":-2,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableProviderChangeRecord":false,"disableStopDetection":false,"distanceFilter":0.5,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxMonitoredGeofences":97,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","channelId":"","smallIcon":"","largeIcon":"","priority":-1,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":true,"didLaunchInBackground":false,"didDeviceReboot":false}
E/TSLocationManager(27546): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gms.location.ActivityRecognitionClient' appears in /data/app/~~C0S-0wJfsL8_SEjGHBhFeQ==/io.growith.sky_app-zDI5JzisZvHAxO_P2mZzQw==/base.apk!classes2.dex)
E/TSLocationManager(27546): 	at com.transistorsoft.xms.g.location.ActivityRecognitionClient.requestActivityUpdates(Unknown Source:50)
E/TSLocationManager(27546): 	at com.transistorsoft.locationmanager.service.ActivityRecognitionService.start(Unknown Source:78)
E/TSLocationManager(27546): 	at com.transistorsoft.locationmanager.service.TrackingService.start(Unknown Source:49)
E/TSLocationManager(27546): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$z0.run(Unknown Source:145)
E/TSLocationManager(27546): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/TSLocationManager(27546): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/TSLocationManager(27546): 	at java.lang.Thread.run(Thread.java:1012)
E/TSLocationManager(27546): [c.t.l.a.BackgroundGeolocation$w0 uncaughtException] 
E/TSLocationManager(27546):   ‼️  Uncaught Exception: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~C0S-0wJfsL8_SEjGHBhFeQ==/io.growith.sky_app-zDI5JzisZvHAxO_P2mZzQw==/base.apk!classes2.dex)
E/TSLocationManager(27546): {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"backgroundPermissionRationale":{"title":"Allow {applicationName} to access this device's location even when closed or not in use?","message":"[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.","positiveAction":"Change to \"{backgroundPermissionOptionLabel}\"","negativeAction":""},"batchSync":false,"configUrl":"","debug":true,"deferTime":0,"desiredAccuracy":-2,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableProviderChangeRecord":false,"disableStopDetection":false,"distanceFilter":0.5,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxMonitoredGeofences":97,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","channelId":"","smallIcon":"","largeIcon":"","priority":-1,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":true,"didLaunchInBackground":false,"didDeviceReboot":false}
E/TSLocationManager(27546): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~C0S-0wJfsL8_SEjGHBhFeQ==/io.growith.sky_app-zDI5JzisZvHAxO_P2mZzQw==/base.apk!classes2.dex)
E/TSLocationManager(27546): 	at com.transistorsoft.xms.g.location.FusedLocationProviderClient.getLastLocation(Unknown Source:50)
E/TSLocationManager(27546): 	at com.transistorsoft.locationmanager.location.TSLocationManager.getLastLocation(Unknown Source:20)
E/TSLocationManager(27546): 	at com.transistorsoft.locationmanager.location.TSLocationManager.onProviderChange(Unknown Source:195)
E/TSLocationManager(27546): 	at com.transistorsoft.locationmanager.provider.TSProviderManager.a(Unknown Source:84)
E/TSLocationManager(27546): 	at com.transistorsoft.locationmanager.provider.TSProviderManager.onConnectivityChange(Unknown Source:17)
E/TSLocationManager(27546): 	at com.transistorsoft.locationmanager.http.HttpService.a(Unknown Source:8)
E/TSLocationManager(27546): 	at com.transistorsoft.locationmanager.http.HttpService.a(Unknown Source:0)
E/TSLocationManager(27546): 	at com.transistorsoft.locationmanager.http.HttpService$g.onAvailable(Unknown Source:6)
E/TSLocationManager(27546): 	at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3932)
E/TSLocationManager(27546): 	at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3914)
E/TSLocationManager(27546): 	at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:4241)
E/TSLocationManager(27546): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/TSLocationManager(27546): 	at android.os.Looper.loopOnce(Looper.java:210)
E/TSLocationManager(27546): 	at android.os.Looper.loop(Looper.java:299)
E/TSLocationManager(27546): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/Process (27546): Process is going to kill itself!
I/Process (27546): java.lang.Exception
I/Process (27546): 	at android.os.Process.killProcess(Process.java:1344)
I/Process (27546): 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:181)
I/Process (27546): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$w0.uncaughtException(Unknown Source:104)
I/Process (27546): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
I/Process (27546): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
I/Process (27546): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
I/Process (27546): Sending signal. PID: 27546 SIG: 9
Lost connection to device.


## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- What were you trying to do? -->

## Debug logs
<!-- include iOS / Android logs
- ios XCode logs,
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat -s TSLocationManager
-->
<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Please [search before posting](https://github.com/transistorsoft/flutter_background_geolocation/issues?q=IncompatibleClassChangeError).  This issue has been posted about a dozen times before.

Duplicate #933
