### ISSUE TITLE
Enable BackgroundFetch to Send Stored Locations in SQL Database When App is Killed and Phone is Stationary

### ISSUE THREAD

**Issue by bulgarian-beast** [transistorsoft/flutter_background_geolocation#1192]
## My Environment
* Plugin version: latest (using GitHub directly in pubspec.yaml)
```
flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
```
* Platform: iOS and Android
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.1.1 23B81 darwin-x64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```
* Plugin config:
```dart
/// Receive events from BackgroundGeolocation in Headless state.open
@pragma('vm:entry-point')
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  String? userID = await UCE().getUserID();
  switch (headlessEvent.name) {
    case bg.Event.BOOT:
      bg.State state = await bg.BackgroundGeolocation.state;
      break;
    case bg.Event.TERMINATE:
      try {
        bg.Location location =
            await bg.BackgroundGeolocation.getCurrentPosition(
                samples: 1, extras: {"event": "terminate", "headless": true});
      } catch (error) {}

      break;
    case bg.Event.HEARTBEAT:
      break;
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      break;
    case bg.Event.GEOFENCE:
      bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      break;
    case bg.Event.GEOFENCESCHANGE:
      bg.GeofencesChangeEvent event = headlessEvent.event;
      break;
    case bg.Event.SCHEDULE:
      bg.State state = headlessEvent.event;
      break;
    case bg.Event.ACTIVITYCHANGE:
      bg.ActivityChangeEvent event = headlessEvent.event;
      break;
    case bg.Event.HTTP:
      bg.HttpEvent response = headlessEvent.event;
      break;
    case bg.Event.POWERSAVECHANGE:
      bool enabled = headlessEvent.event;
      break;
    case bg.Event.CONNECTIVITYCHANGE:
      bg.ConnectivityChangeEvent event = headlessEvent.event;
      break;
    case bg.Event.ENABLEDCHANGE:
      bool enabled = headlessEvent.event;
      break;
    case bg.Event.AUTHORIZATION:
      bg.AuthorizationEvent event = headlessEvent.event;
      bg.BackgroundGeolocation.setConfig(
        await getBackgroundLocationConfig(userID, []),
      );
      break;
  }
}


/// Receive events from BackgroundFetch in Headless state.
@pragma('vm:entry-point')
void backgroundFetchHeadlessTask(HeadlessTask task) async {
  String taskId = task.taskId;

  // Is this a background_fetch timeout event?  If so, simply #finish and bail-out.
  if (task.timeout) {
    BackgroundFetch.finish(taskId);
    return;
  }

  try {
    var location = await bg.BackgroundGeolocation.getCurrentPosition(
      samples: 1,
      extras: {"event": "background-fetch", "headless": true},
    );
  } catch (error) {
  }

  BackgroundFetch.finish(taskId);
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
  bg.BackgroundGeolocation.registerHeadlessTask(
      backgroundGeolocationHeadlessTask);
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}

```

## Expected Behavior
I would like to enhance the application's capabilities to allow the BackgroundFetch feature to initiate the sending of stored locations even if the application is killed and the user's phone is in a stationary state. This would enable the seamless transmission of all stored locations to the server, ensuring a more comprehensive and reliable tracking of user movement.

Something like this:
// Every x time or when a specific even happened
// Check if there is some locations stored in the SQL database:  if (await bg.BackgroundGeolocation.count > 0) {}
// Sync all the remaining locations: await bg.BackgroundGeolocation.sync();

## Actual Behavior
Currently, the application successfully sends background locations when the user is driving, regardless of whether the application is in the foreground, background, or killed state. However, there is a limitation in the current functionality: When the user loss the connection during his trip, the user must keep the application open in either the foreground or background to ensure that all the locations stored in the application's SQL database are sent when he arrive at destination, or the locations are not sent when the app is killed and he don't move.

</details>

**Comment by christocracy** [comment]
You didn't post your plugin Config.

**Comment by bulgarian-beast** [comment]
Sorry, here is the config:
```
bg.Config(
    logLevel: bg.Config.LOG_LEVEL_VERBOSE,
    distanceFilter: 0.0,
    disableLocationAuthorizationAlert: Platform.isIOS,
    locationsOrderDirection: "ASC",
    locationAuthorizationRequest: 'Always',
    url: "$baseUrl/processData",
    method: "POST",
    headers: await FireAuth().getHttpHeader(forceRefresh: true),
    backgroundPermissionRationale: bg.PermissionRationale(
      title:
          "Allow app to access this device's location even when the app is closed or not in use.",
      message:
          "App collects location data to detect your trips to or for work, and calculate distance-travelled.",
      positiveAction: "Change to '{backgroundPermissionOptionLabel}'",
      negativeAction: S.current.label_cancel,
    ),
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: true,
    foregroundService: true,
    notification: bg.Notification(
      title: S.current.android_notif_title,
      text: S.current.android_notif_description,
    ),
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    debug: true,
  );
```

**Comment by christocracy** [comment]
See wiki "Debugging" and learn to fetch logs from the plug-in database using .emailLog.  Also search api docs "Logger".

**Comment by christocracy** [comment]
read api docs "HTTP Guide", linked throughout.

Also see api docs Config.autoSync and method .sync()

**Comment by bulgarian-beast** [comment]
Hello,
We tried to use BackgroundFetch, but we always got this error:

```
D/TSBackgroundFetch(15991): - Background Fetch event received: flutter_background_fetch
I/flutter (15991): [BackgroundFetch] Event received flutter_background_fetch
I/TSLocationManager(15991): [c.t.l.l.TSLocationManager a] 
I/TSLocationManager(15991): ╔═════════════════════════════════════════════
I/TSLocationManager(15991): ║ getCurrentPosition LocationResult: 28 (433987ms old)
I/TSLocationManager(15991): ╠═════════════════════════════════════════════
I/TSLocationManager(15991): ╟─ 📍  Location[fused 43.503271,1.174276 hAcc=20.0 et=+2d10h37m50s311ms alt=266.3999938964844 vAcc=1.1745107 vel=0.6596224 sAcc=0.55504364 bear=221.94394 bAcc=180.0 {Bundle[{}]}], time: 1704784824936
I/TSLocationManager(15991): [c.t.l.l.TSLocationManager onSingleLocationResult] 
I/TSLocationManager(15991):   🔵  Acquired current position
D/TSLocationManager(15991): [c.t.l.l.TSLocationManager a] Median accuracy: 20.0
I/TSLocationManager(15991): [c.t.l.d.s.SQLiteLocationDAO persist] 
I/TSLocationManager(15991):   ✅  INSERT: 6857ad52-7f6f-4c55-8d51-44800ea94636
I/TSLocationManager(15991): [c.t.l.http.HttpService flush] 
I/TSLocationManager(15991): ╔═════════════════════════════════════════════
I/TSLocationManager(15991): ║ HTTP Service (count: 1)
I/TSLocationManager(15991): ╠═════════════════════════════════════════════
I/TSLocationManager(15991): [c.t.l.u.BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 32
D/TSLocationManager(15991): [c.t.l.d.s.SQLiteLocationDAO first] 
D/TSLocationManager(15991):   ✅  Locked 1 records
I/TSLocationManager(15991): [c.t.l.http.HttpService a] 
I/TSLocationManager(15991):   🔵  HTTP POST: 6857ad52-7f6f-4c55-8d51-44800ea94636
I/TSLocationManager(15991): [c.t.l.a.BackgroundGeolocation$a1 run] 
I/TSLocationManager(15991):   🔵  HTTPService is busy with an existing request.
E/flutter (15991): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(HTTPService is busy, null, null, null)
E/flutter (15991): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (15991): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (15991): <asynchronous suspension>
E/flutter (15991): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:496:35)
E/flutter (15991): <asynchronous suspension>
E/flutter (15991): #3      BackgroundGeolocation.sync (package:flutter_background_geolocation/models/background_geolocation.dart:662:13)
E/flutter (15991): <asynchronous suspension>
E/flutter (15991): #4      backgroundFetchEventHandler (package:app/controllers/background_fetch/init_background_fetch.dart:45:5)
E/flutter (15991): <asynchronous suspension>
E/flutter (15991): #5      initBackgroundFetchPlatformState.<anonymous closure> (package:app/controllers/background_fetch/init_background_fetch.dart:109:5)
E/flutter (15991): <asynchronous suspension>
E/flutter (15991): 
```

Testes on multiple real Android devices, with good internet connection, plugged to power with more than 90% batterie, and the server is up.

**Comment by bulgarian-beast** [comment]
The problem appears to be that the function was not defined in the main.dart.
We still receive the ERROR: `[BackgroundFetch] ERROR: PlatformException(HTTPService is busy, null, null, null)`
It's strange because I see that the server receive all the locations thanks to the uuid of the loc in the adb logcat and the server.

**Comment by christocracy** [comment]
You are are calling .sync() and simply not catching exceptions.  You're using autoSync:true.

The plug-in is simply saying "I'm already busy uploading your data",

Just catch the exception and ignore it, it's harmless",
