### ISSUE TITLE
[c.t.l.a.BackgroundGeolocation ready] LocationPermission :false (App crashes when Background Geolocation clicked on the sample app))

### ISSUE THREAD

**Issue by DipanshuJuneja** [transistorsoft/flutter_background_geolocation#124]
## Your Environment
* Plugin version: 1.2.4
* Platform: Android
* OS version: Oreo
* Device manufacturer / model: Nokia 6.1 Plus

## Debug logs

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Launching lib\main.dart on Nokia 6 1 Plus in debug mode...
[flutter_background_geolocation] Purging debug resources in release build
Built build\app\outputs\apk\debug\app-debug.apk.
D/TSLocationManager(11831): [c.t.l.adapter.TSConfig c] ℹ️   Persist config, dirty: [debug, desiredAccuracy, logLevel, startOnBoot, stopOnTerminate]
D/TSLocationManager(11831): [c.t.l.a.BackgroundGeolocation ready] LocationPermission :false
I/flutter (11831): [ProviderChangeEvent enabled:true, status: 2, network: true, gps: true]
I/TSLocationManager(11831): [c.t.locationmanager.util.b a]
I/TSLocationManager(11831):   🔵  LocationAuthorization: Requesting Background permission
D/AndroidRuntime(11831): Shutting down VM
E/AndroidRuntime(11831): FATAL EXCEPTION: main
E/AndroidRuntime(11831): Process: com.example.awesome_project, PID: 11831
E/AndroidRuntime(11831): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.awesome_project/com.intentfilter.androidpermissions.PermissionsActivity}; have you declared this activity in your AndroidManifest.xml?
E/AndroidRuntime(11831): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2012)
E/AndroidRuntime(11831): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
E/AndroidRuntime(11831): 	at android.app.ContextImpl.startActivity(ContextImpl.java:917)
E/AndroidRuntime(11831): 	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
E/AndroidRuntime(11831): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
E/AndroidRuntime(11831): 	at com.intentfilter.androidpermissions.PermissionManager.startPermissionActivity(PermissionManager.java:63)
E/AndroidRuntime(11831): 	at com.intentfilter.androidpermissions.PermissionHandler.requestPermissions(PermissionHandler.java:70)
E/AndroidRuntime(11831): 	at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:47)
E/AndroidRuntime(11831): 	at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:50)
E/AndroidRuntime(11831): 	at com.transistorsoft.locationmanager.util.b$5.run(Unknown Source:31)
E/AndroidRuntime(11831): 	at android.os.Handler.handleCallback(Handler.java:874)
E/AndroidRuntime(11831): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(11831): 	at android.os.Looper.loop(Looper.java:198)
E/AndroidRuntime(11831): 	at android.app.ActivityThread.main(ActivityThread.java:6729)
E/AndroidRuntime(11831): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11831): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(11831): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/TSLocationManager(11831): [c.t.l.a.BackgroundGeolocation$e uncaughtException]
E/TSLocationManager(11831):   ‼️  Uncaught Exception: Unable to find explicit activity class {com.example.awesome_project/com.intentfilter.androidpermissions.PermissionsActivity}; have you declared this activity in your AndroidManifest.xml?
E/TSLocationManager(11831): {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"autoSync":true,"autoSyncThreshold":0,"batchSync":false,"debug":true,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableStopDetection":false,"distanceFilter":10,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"forceReloadOnBoot":false,"forceReloadOnGeofence":false,"forceReloadOnHeartbeat":false,"forceReloadOnLocationChange":false,"forceReloadOnMotionChange":false,"forceReloadOnSchedule":false,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":false,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":true,"didLaunchInBackground":false}
E/TSLocationManager(11831): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.awesome_project/com.intentfilter.androidpermissions.PermissionsActivity}; have you declared this activity in your AndroidManifest.xml?
E/TSLocationManager(11831): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2012)
E/TSLocationManager(11831): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
E/TSLocationManager(11831): 	at android.app.ContextImpl.startActivity(ContextImpl.java:917)
E/TSLocationManager(11831): 	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
E/TSLocationManager(11831): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
E/TSLocationManager(11831): 	at com.intentfilter.androidpermissions.PermissionManager.startPermissionActivity(PermissionManager.java:63)
E/TSLocationManager(11831): 	at com.intentfilter.androidpermissions.PermissionHandler.requestPermissions(PermissionHandler.java:70)
E/TSLocationManager(11831): 	at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:47)
E/TSLocationManager(11831): 	at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:50)
E/TSLocationManager(11831): 	at com.transistorsoft.locationmanager.util.b$5.run(Unknown Source:31)
E/TSLocationManager(11831): 	at android.os.Handler.handleCallback(Handler.java:874)
E/TSLocationManager(11831): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/TSLocationManager(11831): 	at android.os.Looper.loop(Looper.java:198)
E/TSLocationManager(11831): 	at android.app.ActivityThread.main(ActivityThread.java:6729)
E/TSLocationManager(11831): 	at java.lang.reflect.Method.invoke(Native Method)
E/TSLocationManager(11831): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/TSLocationManager(11831): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process (11831): Sending signal. PID: 11831 SIG: 9
Lost connection to device.
Exited (sigterm)

```

## Code
(taken from example app)
```dart <-- Syntax highlighting: DO NOT REMOVE -->

import 'package:flutter/material.dart';
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart' as bg;

////
// For pretty-printing location JSON.  Not a requirement of flutter_background_geolocation
//
import 'dart:convert';
JsonEncoder encoder = new JsonEncoder.withIndent("     ");
//
////

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'BackgroundGeolocation Demo',
      theme: new ThemeData(
        primarySwatch: Colors.amber,
      ),
      home: new MyHomePage(title: 'BackgroundGeolocation Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _isMoving;
  bool _enabled;
  String _motionActivity;
  String _odometer;
  String _content;

  @override
  void initState() {
    _isMoving = false;
    _enabled = false;
    _content = '';
    _motionActivity = 'UNKNOWN';
    _odometer = '0';

    // 1.  Listen to events (See docs for all 12 available events).
    bg.BackgroundGeolocation.onLocation(_onLocation);
    bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
    bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
    bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
    bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);

    // 2.  Configure the plugin
    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        reset: true
    )).then((bg.State state) {
      setState(() {
        _enabled = state.enabled;
        _isMoving = state.isMoving;
      });
    });
  }

  void _onClickEnable(enabled) {
    if (enabled) {
      bg.BackgroundGeolocation.start().then((bg.State state) {
        print('[start] success $state');
        setState(() {
          _enabled = state.enabled;
          _isMoving = state.isMoving;
        });
      });
    } else {
      bg.BackgroundGeolocation.stop().then((bg.State state) {
        print('[stop] success: $state');
        // Reset odometer.
        bg.BackgroundGeolocation.setOdometer(0.0);

        setState(() {
          _odometer = '0.0';
          _enabled = state.enabled;
          _isMoving = state.isMoving;
        });
      });
    }
  }

  // Manually toggle the tracking state:  moving vs stationary
  void _onClickChangePace() {
    setState(() {
      _isMoving = !_isMoving;
    });
    print("[onClickChangePace] -> $_isMoving");

    bg.BackgroundGeolocation.changePace(_isMoving).then((bool isMoving) {
      print('[changePace] success $isMoving');
    }).catchError((e) {
      print('[changePace] ERROR: ' + e.code.toString());
    });
  }

  // Manually fetch the current position.
  void _onClickGetCurrentPosition() {
    bg.BackgroundGeolocation.getCurrentPosition(
        persist: false,     // <-- do not persist this location
        desiredAccuracy: 0, // <-- desire best possible accuracy
        timeout: 30000,     // <-- wait 30s before giving up.
        samples: 3          // <-- sample 3 location before selecting best.
    ).then((bg.Location location) {
      print('[getCurrentPosition] - $location');
    }).catchError((error) {
      print('[getCurrentPosition] ERROR: $error');
    });
  }

  ////
  // Event handlers
  //

  void _onLocation(bg.Location location) {
    print('[location] - $location');

    String odometerKM = (location.odometer / 1000.0).toStringAsFixed(1);

    setState(() {
      _content = encoder.convert(location.toMap());
      _odometer = odometerKM;
    });
  }

  void _onMotionChange(bg.Location location) {
    print('[motionchange] - $location');
  }

  void _onActivityChange(bg.ActivityChangeEvent event) {
    print('[activitychange] - $event');
    setState(() {
      _motionActivity = event.activity;
    });
  }

  void _onProviderChange(bg.ProviderChangeEvent event) {
    print('$event');

    setState(() {
      _content = encoder.convert(event.toMap());
    });
  }

  void _onConnectivityChange(bg.ConnectivityChangeEvent event) {
    print('$event');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Background Geolocation'),
        actions: <Widget>[
          Switch(
            value: _enabled,
            onChanged: _onClickEnable
          ),
        ]
      ),
      body: SingleChildScrollView(
          child: Text('$_content')
      ),
      bottomNavigationBar: BottomAppBar(
        child: Container(
          padding: const EdgeInsets.only(left: 5.0, right: 5.0),
          child: Row(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              IconButton(
                icon: Icon(Icons.gps_fixed),
                onPressed: _onClickGetCurrentPosition,
              ),
              Text('$_motionActivity · $_odometer km'),
              MaterialButton(
                minWidth: 50.0,
                child: Icon((_isMoving) ? Icons.pause : Icons.play_arrow, color: Colors.white),
                color: (_isMoving) ? Colors.red : Colors.green,
                onPressed: _onClickChangePace
              )
            ]
          )
        )
      ),
    );
  }
}
```

## Actual Behavior

App boots up fine (with the usual Toast for license) but when I click on the Background location switch in the example application, it crashes

## Steps to Reproduce

1. Install the package
2. Followed the instructions here https://github.com/transistorsoft/flutter_background_geolocation/blob/master/docs/INSTALL-ANDROID.md (till before the license)
3.  Ran the example https://gist.github.com/christocracy/a0464846de8a9c27c7e9de5616082878

**Comment by christocracy** [comment]
```
flutter doctor
```

**Comment by christocracy** [comment]
It looks like you've create a simple demo app.  Can you commit it to a public Git repo so I can look at it?

**Comment by DipanshuJuneja** [comment]
Thanks for the quick response. Yes, I've been building the demo app, oddly I copied and pasted the project in a different directory (without doing any modifications) and then ran again, and it worked fine. No crashes. Not sure what was the issue (PS Flutter doctor showed no issues).

**Comment by christocracy** [comment]
>Yes, I've been building the demo app

Which demo app?  The one in this repo's [/example](https://github.com/transistorsoft/flutter_background_geolocation/tree/master/example) folder?

**Comment by DipanshuJuneja** [comment]
The hello_world one https://gist.github.com/christocracy/a0464846de8a9c27c7e9de5616082878

**Comment by christocracy** [comment]
That's just the `.dart` code.  I'm more concerned with the Flutter android app and how that was generated and configured and which version of Flutter you're using, which is why I asked for `flutter doctor`

**Comment by DipanshuJuneja** [comment]
Sure. 
Futter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale en-IN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.38.1)
[√] Connected device (1 available)

• No issues found!
```

git repo
https://github.com/DipanshuJuneja/sample_background_flutter

**Comment by christocracy** [comment]
Your `sample_background_flutter` works fine for me after [disabling this unrelated line of code](https://github.com/DipanshuJuneja/sample_background_flutter/blob/master/lib/pages/auth_screens/login.dart#L57).  Your Android setup looks fine.

![](https://dl.dropbox.com/s/u8jy0zf12vldwi5/Screenshot%202019-09-25%2011.05.44.png?dl=1)
