### ISSUE TITLE
StrictMode DiskReadViolation related to com.transistorsoft.locationmanager

### ISSUE THREAD

**Issue by radivojeostojic** [transistorsoft/flutter_background_geolocation#1257]
During the testing of our Android application using StrictMode, we observed an increased number of DiskReadViolation occurrences on our MainThread related to com.transistorsoft.locationmanager. The primary reason for testing the app in StrictMode was the higher number of ANRs reported to Crashlytics. While some policy violations are related to other aspects, we noticed a significant increase in issues regarding Transistorsoft compared to other issues. Additionally, several crash reports on Crashlytics indicated similar occurrences:

Report from Crashlytics:
```
Fatal Exception: android.app.ForegroundServiceDidNotStartInTimeException
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{4e982e6 u0 com.**/com.transistorsoft.locationmanager.service.TrackingService}

```

```
Fatal Exception: android.app.ForegroundServiceDidNotStartInTimeException
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ce2735a u0 com.***/com.transistorsoft.locationmanager.service.GeofencingService}
```
```

Fatal Exception: android.app.ForegroundServiceDidNotStartInTimeException
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{afe83f1 u0 com.***/com.transistorsoft.locationmanager.service.ActivityRecognitionService}
```
```
Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7eeb526 u0 com.gopuff.godrive2.live/com.transistorsoft.locationmanager.service.ActivityRecognitionService}
       at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2245)
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2216)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

## Your Environment
* Plugin version: 4.13.7
* Platform: Android
* OS version: Android 12, Android 13, Android 14
* Device manufacturer / model: Mostly Samsung and Motorola
* Flutter info (`flutter doctor`): 

```
> [!] Flutter (Channel [user-branch], 3.16.9, on macOS 14.0 23A344 darwin-arm64, locale en-RS)
>     ! Flutter version 3.16.9 on channel [user-branch] at /Users/radivojeostojic/Documents/development/flutter
>       Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
>       If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
>     ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.17.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
>       /Users/radivojeostojic/Documents/development/flutter. Consider adding /Users/radivojeostojic/Documents/development/flutter/bin to the front of your path.
>     ! Upstream repository unknown source is not a standard remote.
>       Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
>     • Framework revision 41456452f2 (8 weeks ago), 2024-01-25 10:06:23 -0800
>     • Engine revision f40e976bed
>     • Dart version 3.2.6
>     • DevTools version 2.28.5
>     • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
>     • Android SDK at /Users/radivojeostojic/Library/Android/sdk
>     • Platform android-34, build-tools 33.0.1
>     • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 15.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 15E204a
>     • CocoaPods version 1.12.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2022.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
> 
> [✓] VS Code (version 1.68.1)
>     • VS Code at /Users/radivojeostojic/Downloads/Visual Studio Code.app/Contents
>     • Flutter extension version 3.60.0
> 
> [✓] Connected device (4 available)
>     • SM G955U1 (mobile)         • 988bdc37395638324a                   • android-arm64  • Android 9 (API 28)
>     • iPhone 15 Pro Max (mobile) • 9D762A9B-159B-4456-B8E3-99ECD5B453D0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
>     • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
>     • Chrome (web)               • chrome                               • web-javascript • Google Chrome 122.0.6261.129
>     ! Error: Browsing on the local area network for Radivoje’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
>       network as this Mac.
>       The device must be opted into Developer Mode to connect wirelessly. (code -27)
> 
> [✓] Network resources
>     • All expected network resources are available.
> 
> ! Doctor found issues in 1 category.
```

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Config(
          notification: bg.Notification(
            title: AppLocalizations
                .current.gopuffGodriveServicesLocationServicesActive,
            // 'Location Services Active',
            text: '',
            sticky: true,
            layout: 'workday_notification_layout',
            smallIcon: 'mipmap/ic_notification',
            // <-- defaults to app icon
            largeIcon: 'mipmap/ic_notification',
          ),
          locationAuthorizationRequest: 'always',
          disableLocationAuthorizationAlert: true,
          backgroundPermissionRationale: bg.PermissionRationale(
              title: ''
              message: '',
              positiveAction: '',
              negativeAction: ''),
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10.0,
          stopOnTerminate: false,
          preventSuspend: true,
          heartbeatInterval: 60,
          stopTimeout: 1,
          startOnBoot: true,
          foregroundService: true,
          logLevel: bg.Config.LOG_LEVEL_ERROR,
          persistMode: bg.Config.PERSIST_MODE_NONE,
        )

```

## Expected Behavior
We shouldn't see DiskReadViolation

## Actual Behavior
We see DiskReadViolation related to Transistorsoft

## Steps to Reproduce
Run app in StrictMode and observe logs

## Context
Resolve ANR issues 

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
03-15 14:07:56.412  5041  5041 D StrictMode: StrictMode policy violation; ~duration=129 ms: android.os.strictmode.DiskReadViolation
03-15 14:07:56.412  5041  5041 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:206)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:163)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at dalvik.system.DexPathList$NativeLibraryElement.findNativeLibrary(DexPathList.java:833)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at dalvik.system.DexPathList.findLibrary(DexPathList.java:548)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:179)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1005)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at java.lang.System.loadLibrary(System.java:1669)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.settings.Settings.<clinit>(Unknown Source:2)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.settings.Settings.load(Unknown Source:0)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.<init>(Unknown Source:65)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.a(Unknown Source:9)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance(Unknown Source:14)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.notification.TSLocalNotification.build(Unknown Source:12)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.ForegroundNotification.build(Unknown Source:0)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.AbstractService.c(Unknown Source:89)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.AbstractService.a(Unknown Source:11)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.LocationRequestService.onCreate(Unknown Source:8)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3758)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at android.app.ActivityThread.access$1400(ActivityThread.java:238)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1803)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at android.os.Looper.loop(Looper.java:214)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at java.lang.reflect.Method.invoke(Native Method)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
03-15 14:07:56.412  5041  5041 D StrictMode: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
03-15 14:07:56.413  5041  5041 D StrictMode: StrictMode policy violation; ~duration=123 ms: android.os.strictmode.DiskReadViolation
03-15 14:07:56.413  5041  5041 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:206)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:163)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at dalvik.system.DexPathList$NativeLibraryElement.findNativeLibrary(DexPathList.java:833)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at dalvik.system.DexPathList.findLibrary(DexPathList.java:548)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:179)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1005)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at java.lang.System.loadLibrary(System.java:1669)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.a.A.<clinit>(Unknown Source:17)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.a.A.c(Unknown Source:0)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.settings.Settings.load(Unknown Source:0)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.<init>(Unknown Source:65)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.a(Unknown Source:9)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance(Unknown Source:14)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.notification.TSLocalNotification.build(Unknown Source:12)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.ForegroundNotification.build(Unknown Source:0)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.AbstractService.c(Unknown Source:89)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.AbstractService.a(Unknown Source:11)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.LocationRequestService.onCreate(Unknown Source:8)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3758)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at android.app.ActivityThread.access$1400(ActivityThread.java:238)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1803)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at android.os.Looper.loop(Looper.java:214)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at java.lang.reflect.Method.invoke(Native Method)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
03-15 14:07:56.413  5041  5041 D StrictMode: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
03-15 14:07:56.415  5041  5041 D StrictMode: StrictMode policy violation; ~duration=113 ms: android.os.strictmode.DiskReadViolation
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at java.io.File.exists(File.java:815)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:653)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:644)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:600)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:809)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:437)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:179)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.load(Unknown Source:5)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.<init>(Unknown Source:68)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.a(Unknown Source:9)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance(Unknown Source:14)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.notification.TSLocalNotification.build(Unknown Source:12)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.ForegroundNotification.build(Unknown Source:0)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.AbstractService.c(Unknown Source:89)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.AbstractService.a(Unknown Source:11)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.LocationRequestService.onCreate(Unknown Source:8)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3758)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.ActivityThread.access$1400(ActivityThread.java:238)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1803)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.os.Looper.loop(Looper.java:214)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at java.lang.reflect.Method.invoke(Native Method)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
03-15 14:07:56.415  5041  5041 D StrictMode: StrictMode policy violation; ~duration=111 ms: android.os.strictmode.DiskReadViolation
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:256)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.SharedPreferencesImpl.contains(SharedPreferencesImpl.java:334)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.load(Unknown Source:49)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.<init>(Unknown Source:68)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.a(Unknown Source:9)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance(Unknown Source:14)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.notification.TSLocalNotification.build(Unknown Source:12)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.ForegroundNotification.build(Unknown Source:0)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.AbstractService.c(Unknown Source:89)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.AbstractService.a(Unknown Source:11)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.LocationRequestService.onCreate(Unknown Source:8)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3758)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.ActivityThread.access$1400(ActivityThread.java:238)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1803)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.os.Looper.loop(Looper.java:214)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at java.lang.reflect.Method.invoke(Native Method)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
03-15 14:07:56.415  5041  5041 D StrictMode: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
03-15 14:07:56.416  5041  5041 D StrictMode: StrictMode policy violation; ~duration=66 ms: android.os.strictmode.DiskReadViolation
03-15 14:07:56.416  5041  5041 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:206)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:163)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at dalvik.system.DexPathList$NativeLibraryElement.findNativeLibrary(DexPathList.java:833)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at dalvik.system.DexPathList.findLibrary(DexPathList.java:548)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:179)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1005)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at java.lang.System.loadLibrary(System.java:1669)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.plugin.TSPlugin.<clinit>(Unknown Source:9)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.plugin.TSPlugin.getInstance(Unknown Source:0)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.load(Unknown Source:289)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.<init>(Unknown Source:68)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.a(Unknown Source:9)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance(Unknown Source:14)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.notification.TSLocalNotification.build(Unknown Source:12)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.ForegroundNotification.build(Unknown Source:0)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.AbstractService.c(Unknown Source:89)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.AbstractService.a(Unknown Source:11)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at com.transistorsoft.locationmanager.service.LocationRequestService.onCreate(Unknown Source:8)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3758)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at android.app.ActivityThread.access$1400(ActivityThread.java:238)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1803)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at android.os.Looper.loop(Looper.java:214)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at java.lang.reflect.Method.invoke(Native Method)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
03-15 14:07:56.416  5041  5041 D StrictMode: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

```

</details>

**Comment by radivojeostojic** [comment]
Thanks for the reply. Do you have any ideas what I can do to minimize this issue on my side? I am using the relatively latest plugin version, but our Crashlytics still reports these ANRs too often, especially on Android 12.
