### ISSUE TITLE
RemoteServiceException - Bad Notification (tag=null, id=9942585)

### ISSUE THREAD

**Issue by radivojeostojic** [transistorsoft/flutter_background_geolocation#1264]
## Your Environment
* Plugin version: 4.13.7
* Platform: Android
* OS version: Android 14 and Android 13 (Crash is happening 71% in the background)
* Device manufacturer / model: Google and Samsung
* Flutter info (`flutter doctor`): 
```
[!] Flutter (Channel [user-branch], 3.16.9, on macOS 14.3 23D56 darwin-arm64, locale en-US)
    ! Flutter version 3.16.9 on channel [user-branch] at /Users/radivojeostojic/Documents/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.3.1/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/radivojeostojic/Documents/development/flutter.
      Consider adding /Users/radivojeostojic/Documents/development/flutter/bin to the front of your path.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 41456452f2 (9 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/radivojeostojic/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.1)
    • VS Code at /Users/radivojeostojic/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • SM G955U1 (mobile)          • 988bdc37395638324a • android-arm64 • Android 9 (API 28)
    • sdk gphone64 arm64 (mobile) • emulator-5554      • android-arm64 • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos              • darwin-arm64  • macOS 14.3 23D56 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->

Config(
          notification: bg.Notification(
            title: title,
            // 'Location Services Active',
            text: '',
            sticky: true,
            layout: 'workday_notification_layout',
            smallIcon: 'mipmap/ic_notification',
            // <-- defaults to app icon
            largeIcon: 'mipmap/ic_notification',
          ),
          locationAuthorizationRequest: 'always',
          disableLocationAuthorizationAlert: true,
          backgroundPermissionRationale: bg.PermissionRationale(
              title: ''
              message: '',
              positiveAction: '',
              negativeAction: ''),
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10.0,
          stopOnTerminate: false,
          preventSuspend: true,
          heartbeatInterval: 60,
          stopTimeout: 1,
          startOnBoot: true,
          foregroundService: true,
          logLevel: bg.Config.LOG_LEVEL_ERROR,
          persistMode: bg.Config.PERSIST_MODE_NONE,
        )
```

![Screenshot 2024-03-26 at 17 23 39](https://github.com/transistorsoft/flutter_background_geolocation/assets/28922835/eebeb040-4798-445e-a8fb-03e1ec94d7e8)

## Expected Behavior
We should not have increased number of crashes related to bad notification.

## Actual Behavior
We are seeing increased number of these crashes in Crashlytics:

```
Fatal Exception: android.app.RemoteServiceException$BadForegroundServiceNotificationException: Bad notification(tag=null, id=9942585) posted from package ***, crashing app(uid=10269, pid=23336): Couldn't inflate contentViewsandroid.widget.RemoteViews$ActionException: android.content.res.Resources$NotFoundException: Resource ID #0x7f0d017c
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2181)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

This crash event usually happened in the first second of the user's session. (86% of crash events for this issue happened in the first 5 seconds of a user's session). The crash event for this issue happened 25 times per user on average.

## Steps to Reproduce
It's hard to reproduce it locally. 

## Context
I want to know more about this issue because it's affecting our users in production.

</details>

**Comment by christocracy** [comment]
> layout: 'workday_notification_layout

You seem to be having an issue with your custom layout.

**Comment by christocracy** [comment]
Show me your android/app/build.gradle

**Comment by radivojeostojic** [comment]
> > layout: 'workday_notification_layout
> 
> You seem to be having an issue with your custom layout.

I was thinking that it could be an issue, but after checking, I didn't find anything suspicious.

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:adjustViewBounds="true"
    android:gravity="start"
    android:orientation="vertical"
    android:padding="15dp">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="24dp"
        android:layout_marginBottom="8dp"
        android:gravity="center_vertical"
        android:orientation="horizontal">

        <ImageView
            android:id="@+id/notificationSmallIcon"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"
            tools:srcCompat="@tools:sample/avatars" />

        <TextView
            android:id="@+id/applicationName"
            android:layout_width="wrap_content"
            android:gravity="center_vertical"
            android:layout_height="match_parent"
            android:paddingLeft="10dp"
            android:text="applicationName"
            android:textAppearance="@style/TextAppearance.Compat.Notification.Title"
            android:textColor="#888888"
            android:textSize="12sp" />
    </LinearLayout>

    <TextView
        android:id="@+id/notificationTitle"
        style="@style/TextAppearance.Compat.Notification.Title"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="notificationTitle"
        android:textSize="14sp" />

    <TextView
        android:id="@+id/notificationText"
        style="@style/TextAppearance.Compat.Notification.Line2"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="notificationText"
        android:textSize="14sp" />
</LinearLayout>
```

**Comment by radivojeostojic** [comment]
> Show me your android/app/build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('keystore.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"
apply plugin: 'com.google.firebase.crashlytics'

ext.datadog_version = "1.19.2"

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
        //https://stackoverflow.com/questions/62548438/execution-failed-for-task-applintvitalrelease-flutter
        checkReleaseBuilds false //<- add this line
    }

    packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86/libfbjni.so'
        pickFirst 'lib/x86_64/libfbjni.so'
        pickFirst 'lib/armeabi-v7a/libfbjni.so'
        pickFirst 'lib/arm64-v8a/libfbjni.so'
    }

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        ndkVersion rootProject.ext.ndkVersion
        multiDexEnabled true
        testInstrumentationRunner "pl.leancode.patrol.BrowserstackPatrolJUnitRunner"
        testInstrumentationRunnerArguments clearPackageData: "true"
    }

    testOptions {
        execution "ANDROIDX_TEST_ORCHESTRATOR"
    }

    signingConfigs {
        staging {
            storeFile file(“”)
            storePassword ''
            keyAlias 'key'
            keyPassword ''
        }
        live {
            storeFile keystoreProperties['storeFile'] != null ?
                    file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources false
            ndk {
                debugSymbolLevel 'FULL'
                abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64'
            }
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro", "proguard-rules.pro"
        }
    }

    flavorDimensions "app"
    productFlavors {
        staging {
            dimension "app"
            applicationId ""
            versionCode flutterVersionCode.toInteger()
            versionName flutterVersionName
            resValue "string", "bg_geo_key", “***”*.toString()
            signingConfig signingConfigs.staging
        }
        live {
            dimension "app"
            applicationId “****”
            versionCode flutterVersionCode.toInteger()
            versionName flutterVersionName
            resValue "string", "bg_geo_key", “****”
            signingConfig signingConfigs.live
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.braze:android-sdk-ui:29.0.1'
    implementation "androidx.appcompat:appcompat:${rootProject.ext.appCompatVersion}"
    androidTestUtil "androidx.test:orchestrator:1.4.2"

    implementation ('co.ujet.android:ujet-android:2.4.1')
    constraints {
        /*
          Ujet up to v2.4.1 has a transitive dependency on ktor-utils-jvm:1.6.0
          Patrol v2 has a transitive dependency on ktor-utils-jvm:2.*.*
          v1.6.0 and v2.*.* are incompatible, so we enforce v1.6.0
        */
        liveImplementation('io.ktor:ktor-utils-jvm:1.6.0') {
            force true
            because 'Ujet and Patrol have a conflict. We need enforce version 1.6.0 for Ujet'
        }
    }

    implementation platform('com.google.firebase:firebase-bom:28.4.0')
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation "com.datadoghq:dd-sdk-android:$datadog_version"
    implementation "androidx.preference:preference-ktx:1.1.1"

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
    // workaround for coreLibraryDesugaring, more info here https://github.com/flutter/flutter/issues/110658
    implementation 'androidx.window:window:1.0.0'
    implementation 'androidx.window:window-java:1.0.0'

    implementation 'com.incode.sdk:core-light:2.6.2'
}
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'


```

**Comment by christocracy** [comment]
It’s been a while since I’ve dealt with custom layouts (it’s not a highly-used configuration).  Ultimately, a resource within your layout is not being found, resulting in your reported error:

> Resources$NotFoundException: Resource ID #0x7f0d017c

You’re not able to reproduce?

**Comment by radivojeostojic** [comment]
I cannot reproduce it locally. I tried to find that resource ID, but I don't have it in my code. The one that I am sending to 'workday_notification_layout' has a different ID.

**Comment by christocracy** [comment]
I suspect a resource *within* the layout itself.

**Comment by christocracy** [comment]
Are there any particular device model / OS version responsible?

**Comment by radivojeostojic** [comment]
I was also thinking of not passing the 'largeIcon' parameter because I don't have it in the layout, but I am not sure if that will help.

**Comment by radivojeostojic** [comment]
<img width="542" alt="Screenshot 2024-03-26 at 18 14 52" src="https://github.com/transistorsoft/flutter_background_geolocation/assets/28922835/34447a66-48c0-4b5c-9a03-c2a9bda7a51f">

I see a lot of issues on Galaxy s20

**Comment by christocracy** [comment]
The easiest short-term solution is to remove the custom-layout from your Notification config until the problem can be reproduced.

**Comment by christocracy** [comment]
I have a *Samsung Galaxy S20 FE @ 13*

**Comment by radivojeostojic** [comment]
> The easiest short-term solution is to remove the custom-layout from your Notification config until the problem can be reproduced.

Something like this?:
```
notification: bg.Notification(
            title: title,
            // 'Location Services Active',
            text: text,
            sticky: true,
            // layout: 'workday_notification_layout',
            smallIcon: 'mipmap/ic_notification',
            // // <-- defaults to app icon
            // largeIcon: 'mipmap/ic_notification',
          ),
```

**Comment by christocracy** [comment]
Yes

**Comment by radivojeostojic** [comment]
Unfortunately, we've encountered this issue again in the new version, despite the changes mentioned above.

Here is the log:
```
Fatal Exception: android.app.RemoteServiceException$BadForegroundServiceNotificationException
Bad notification(tag=null, id=9942585) posted from package com.***, crashing app(uid=10412, pid=16770): Couldn't inflate contentViewsandroid.widget.RemoteViews$ActionException: android.widget.RemoteViews$ActionException: android.view.InflateException: Binary XML file line #31 in com.***:layout/preference_category_material: Binary XML file line #38 in com.***:layout/image_frame: Error inflating class androidx.preference.internal.PreferenceImageView
```


```
Fatal Exception: android.app.RemoteServiceException$BadForegroundServiceNotificationException: Bad notification(tag=null, id=9942585) posted from package com.***, crashing app(uid=10412, pid=16770): Couldn't inflate contentViewsandroid.widget.RemoteViews$ActionException: android.widget.RemoteViews$ActionException: android.view.InflateException: Binary XML file line #31 in com.***:layout/preference_category_material: Binary XML file line #38 in com.***:layout/image_frame: Error inflating class androidx.preference.internal.PreferenceImageView
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2264)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2552)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8826)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```
