### ISSUE TITLE
cannot compile iOS: Could not resolve the package 'flutter_background_geolocation'

### ISSUE THREAD

**Issue by santiagohdzb** [transistorsoft/flutter_background_geolocation#129]
## Your Environment
* Plugin version: 1.2.0
* Platform: iOS
* OS version: 12.4.2
* Device manufacturer / model: iPad Mini
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale es-MX)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

• No issues found!
```
* Plugin config:
```dart
import 'dart:io';
import 'package:flutter_background_geolocation/flutter_background_geolocation.dart' as FBG;

void start() {
  if (Platform.isIOS) {
    FBG.BackgroundGeolocation.onLocation((FBG.Location location) {
      print('[location] - $location');
    });

    FBG.BackgroundGeolocation.ready(FBG.Config(
      desiredAccuracy: FBG.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0.1,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: true,
      logLevel: FBG.Config.LOG_LEVEL_VERBOSE
    )).then((FBG.State state) {
      if (!state.enabled) {
        FBG.BackgroundGeolocation.start();
      }
    });
  }
}
```

## Expected Behavior
Compile the app

## Actual Behavior
The compiler crashes with this:
```
Compiler message:
    Error: Could not resolve the package 'flutter_background_geolocation' in 'package:flutter_background_geolocation/flutter_background_geolocation.dart'.
```

## Steps to Reproduce
1. Follow [iOS setup guide](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/docs/INSTALL-IOS.md)
2. Put `flutter_background_geolocation: '^1.2.0'` into pubspec.yaml
3. Run `flutter build ios --debug`

## Context
I'm trying to test this plugin to receive location updates while the app is in background

## Extra information

<details>
        <summary>Compiler complete message</summary>

```

Compiler message:
    Error: Could not resolve the package 'flutter_background_geolocation' in 'package:flutter_background_geolocation/flutter_background_geolocation.dart'.
    ../../lib/src/model/bo/gps_bo.dart:2:8: Error: Not found: 'package:flutter_background_geolocation/flutter_background_geolocation.dart'
    import 'package:flutter_background_geolocation/flutter_background_geolocation.dart' as FBG;
           ^
    ../../lib/src/model/bo/gps_bo.dart:7:49: Error: 'Location' isn't a type.
          FBG.BackgroundGeolocation.onLocation((FBG.Location location) {
                                                    ^^^^^^^^
    ../../lib/src/model/bo/gps_bo.dart:7:11: Error: Getter not found: 'BackgroundGeolocation'.
          FBG.BackgroundGeolocation.onLocation((FBG.Location location) {
              ^^^^^^^^^^^^^^^^^^^^^
    ../../lib/src/model/bo/gps_bo.dart:12:30: Error: Getter not found: 'Config'.
            desiredAccuracy: FBG.Config.DESIRED_ACCURACY_HIGH,
                                 ^^^^^^
    ../../lib/src/model/bo/gps_bo.dart:17:23: Error: Getter not found: 'Config'.
            logLevel: FBG.Config.LOG_LEVEL_VERBOSE
                          ^^^^^^
    ../../lib/src/model/bo/gps_bo.dart:11:39: Error: Method not found: 'Config'.
          FBG.BackgroundGeolocation.ready(FBG.Config(
                                          ^^^^^^
    ../../lib/src/model/bo/gps_bo.dart:11:11: Error: Getter not found: 'BackgroundGeolocation'.
          FBG.BackgroundGeolocation.ready(FBG.Config(
              ^^^^^^^^^^^^^^^^^^^^^
    ../../lib/src/model/bo/gps_bo.dart:18:20: Error: 'State' isn't a type.
          )).then((FBG.State state) {
                       ^^^^^
    ../../lib/src/model/bo/gps_bo.dart:20:15: Error: Getter not found: 'BackgroundGeolocation'.
              FBG.BackgroundGeolocation.start();
                  ^^^^^^^^^^^^^^^^^^^^^
    Unhandled exception:
    FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aflutter_background_geolocation%2Fflutter_background_geolocation.dart; message=StandardFileSystem only supports file:* and data:* URIs)
    #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
    #1      asFileUri (package:vm/kernel_front_end.dart:578:37)
    <asynchronous suspension>
    #2      writeDepfile (package:vm/kernel_front_end.dart:755:21)
    <asynchronous suspension>
    #3      FrontendCompiler.compile (package:vm/frontend_server.dart:407:15)
    <asynchronous suspension>
    #4      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:29:22)
    <asynchronous suspension>
    #5      starter (package:frontend_server/server.dart:127:27)
    <asynchronous suspension>
    #6      main (file:///b/s/w/ir/k/src/flutter/frontend_server/bin/starter.dart:8:30)
    <asynchronous suspension>
    #7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
    #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
</details>
<details>
	<summary>Podfile</summary>

``` ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  # use_frameworks! # <--- add this

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

# pre_install do |installer|
# 	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      # config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end

```

</details>

**Comment by christocracy** [comment]
- Are you sure you did a *Packages Get*?
![](https://dl.dropbox.com/s/t97p7n0ewyrxzvo/Screenshot%202019-10-11%2019.10.26.png?dl=1)

- Btw, the latest release is [1.2.4](https://pub.dev/packages/flutter_background_geolocation#-readme-tab-).  I often neglect to update the REAMDE.  As noted, see [Versions](https://pub.dev/packages/flutter_background_geolocation/versions) for latest version.
![](https://dl.dropbox.com/s/lenfxv8jiid5399/Screenshot%202019-10-11%2019.12.17.png?dl=1)

**Comment by santiagohdzb** [comment]
Yeah, I ran `flutter clean` and then `flutter packages get`. Everything started working out. Thanks for this awesome solution!
