### ISSUE TITLE
release build crashes but not eh debug build

### ISSUE THREAD

**Issue by kmusham** [transistorsoft/flutter_background_geolocation#132]
## Your Environment
* Plugin version: 1.2.4
* Platform: Android
* OS version: 10
* Device manufacturer / model: Google Pixel 3 
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.15-pre.139, on Microsoft Windows [Version 10.0.18362.418], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.37.0)
[√] Connected device (1 available)

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
App should not crash

## Actual Behavior
App crashes

## Steps to Reproduce

1. create a release build with a license and install on android device.
2.app crashes
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
2019-10-16 11:49:00.786 23102-23102/? I/Adreno: QUALCOMM build                   : bc00834, I609ab310b2
    Build Date                       : 04/11/19
    OpenGL ES Shader Compiler Version: EV031.26.07.00
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2019-10-16 11:49:00.786 23102-23102/? I/Adreno: Build Config                     : S L 8.0.6 AArch64
2019-10-16 11:49:00.790 23102-23102/? I/Adreno: PFP: 0x005ff110, ME: 0x005ff066
2019-10-16 11:49:00.790 13950-13971/? I/MicroDetectionState: Should stop hotword detection immediately - false
2019-10-16 11:49:00.821 637-637/? E/RenderEngine: GL error 0x0501
2019-10-16 11:49:00.853 23102-23102/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2019-10-16 11:49:00.855 23102-23102/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.compliahealth.mobileedge, PID: 23102
    java.lang.ExceptionInInitializerError
        at com.transistorsoft.locationmanager.b.a.b(Unknown Source:0)
        at c.d.a.a.a.&lt;init&gt;(Unknown Source:36)
        at c.d.a.a.a.a(Unknown Source:2)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:67)
        at com.compliahealth.mobileedge.MainActivity.onCreate(Unknown Source:3)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at c.d.b.a.a(Unknown Source:27)
        at com.transistorsoft.locationmanager.b.a.&lt;clinit&gt;(Unknown Source:2)
        at com.transistorsoft.locationmanager.b.a.b(Unknown Source:0)&nbsp;
        at c.d.a.a.a.&lt;init&gt;(Unknown Source:36)&nbsp;
        at c.d.a.a.a.a(Unknown Source:2)&nbsp;
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:67)&nbsp;
        at com.compliahealth.mobileedge.MainActivity.onCreate(Unknown Source:3)&nbsp;
        at android.app.Activity.performCreate(Activity.java:7802)&nbsp;
        at android.app.Activity.performCreate(Activity.java:7791)&nbsp;
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)&nbsp;
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)&nbsp;
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)&nbsp;
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)&nbsp;
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)&nbsp;
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)&nbsp;
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)&nbsp;
        at android.os.Handler.dispatchMessage(Handler.java:107)&nbsp;
        at android.os.Looper.loop(Looper.java:214)&nbsp;
        at android.app.ActivityThread.main(ActivityThread.java:7356)&nbsp;
        at java.lang.reflect.Method.invoke(Native Method)&nbsp;
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)&nbsp;
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)&nbsp;
2019-10-16 11:49:00.860 1276-3020/? W/ActivityTaskManager:   Force finishing activity com.compliahealth.mobileedge/.MainActivity
Thanks
```

</details>

**Comment by christocracy** [comment]
In your `android/app/build.gradle`, have you [`minifyEnabled true`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/app/build.gradle#L66)?

**Comment by kmusham** [comment]
Yes and No.
I tried both cases but did not work. Last buil I tried was with the following configuration.
(see the commented out parameters).

 buildTypes {
        release {
            signingConfig signingConfigs.release
            //minifyEnabled true
            //shrinkResources true
            //useProguard true
            //proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
}

**Comment by christocracy** [comment]
Review the [Android Setup](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/docs/INSTALL-ANDROID.md#androidappbuildgradle) and the CHANGELOG.

Clean your build.

**Comment by kmusham** [comment]
Now I followed all the steps and resolved couple of other issues. Now, I see following error . coupled you please help me.

[   +2 ms] [flutter_background_geolocation] Purging debug resources in release build
[   +1 ms] [flutter_background_geolocation] Purging debug resources in release build
[+6978 ms]          *********************************************************
[   +5 ms] WARNING: This version of connectivity will break your Android build if it or its dependencies aren't compatible with AndroidX.
[   +3 ms]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[   +1 ms]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[   +2 ms]          *********************************************************
[   +2 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[   +1 ms] Could not determine the dependencies of task ':flutter_background_geolocation:compileReleaseAidl'.
[   +2 ms] > Could not resolve all task dependencies for configuration ':flutter_background_geolocation:releaseCompileClasspath'.
[   +5 ms]    > Could not find com.google.android.gms:play-services-location:17.3.0.
[   +1 ms]      Required by:
[   +2 ms]          project :flutter_background_geolocation
[   +2 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
[   +7 ms] * Get more help at https://help.gradle.org
[   +3 ms] BUILD FAILED in 8s

**Comment by kmusham** [comment]
buildscript {
    ext.kotlin_version = '1.3.50'
    ext {
        compileSdkVersion   = 29
        targetSdkVersion    = 29
        //appCompatVersion    = '1.0.2'
        playServicesLocationVersion = '17.3.0'
    }
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.2'
    }
}

**Comment by christocracy** [comment]
Where did you get the idea to use `playServicesLocationVersion = '17.3.0'`?  The most recent version is `17.0.0` and the [Setup Docs](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/docs/INSTALL-ANDROID.md#androidbuildgradle) suggest `17.0.0`.

See http://maven.google.com: `com.google.android.gms.play-services-location`:
![](https://dl.dropbox.com/s/pp7ibfv36mimgg4/Screenshot%202019-10-16%2016.36.56.png?dl=1)

**Comment by kmusham** [comment]
This is where I found the latest version info
https://developers.google.com/android/guides/releases

Anyway, changing to 17.0.0 solved my issue.
Thank you.

**Comment by christocracy** [comment]
That's talking about **`play-services-auth-api-phone`**.  That has nothing at all to do with `play-services-location`.  Every single Google API has its own distinct version.

![](https://dl.dropbox.com/s/ee36402b51kqfx1/Screenshot%202019-10-16%2016.52.30.png?dl=1)

**Comment by christocracy** [comment]
The ultimate source for google api version is  http://maven.google.com

**Comment by kmusham** [comment]
Wow! not sure why and how I got that version. Right, I'm supposed to look for 'location' in that page, I just copy pasted the first one without searching..

Thanks for your help.
