### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient

### ISSUE THREAD

**Issue by asafvaron90** [transistorsoft/flutter_background_geolocation#1336]
## Your Environment
* Plugin version: 4.15.5
* Platform: Android
* OS version: 
* Device manufacturer / model: Pixel 6 Pro
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.5 23F79 darwin-arm64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (6 available)
    ! Error: Browsing on the local area network for Miriam’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Inabit’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for  MixoFoss. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Michel’s Apple Watch. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)
[✓] Network resources

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10.0,
            stopOnTerminate: false,
            enableHeadless: true,
            startOnBoot: true,
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE)
```

## Expected Behavior
No to crash :)

## Actual Behavior
Crashing as soon as application start (on Splash)

## Context
I am trying to use the library to get the GeoFencing service. to trigger entry to Points on interest

## Debug logs

<details>
	<summary>
	
	

``` <!-- syntax-highligting:  DO NOT REMOVE -->
E/TSLocationManager(27045): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~s64XD8JwiidSUpprT9GPaQ==/com.ofermalls.myofer.stage-N5YS5VdvuvpqMWgZz5AI7w==/base.apk!classes8.dex)
E/TSLocationManager(27045):     at com.transistorsoft.xms.g.location.FusedLocationProviderClient.getLastLocation(Unknown Source:50)
E/TSLocationManager(27045):     at com.transistorsoft.locationmanager.location.TSLocationManager.getLastLocation(Unknown Source:20)
E/TSLocationManager(27045):     at com.transistorsoft.locationmanager.location.TSLocationManager.getCurrentPosition(Unknown Source:8)
E/TSLocationManager(27045):     at com.transistorsoft.locationmanager.service.GeofencingService.changePace(Unknown Source:149)
E/TSLocationManager(27045):     at com.transistorsoft.locationmanager.service.TrackingService.start(Unknown Source:146)
E/TSLocationManager(27045):     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$z0.run(Unknown Source:146)
E/TSLocationManager(27045):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/TSLocationManager(27045):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/TSLocationManager(27045):     at java.lang.Thread.run(Thread.java:1012)
W/FirebaseCrashlytics(27045): Unable to read App Quality Sessions session id.
E/FA      (27045): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
D/AudioTrack(27045): stop(1004): called with 145408 frames delivered
W/FirebaseCrashlytics(27045): Timeout exceeded while awaiting app exception callback from Analytics listener.
E/TSLocationManager(27045): [c.t.l.a.BackgroundGeolocation$w0 uncaughtException] 
E/TSLocationManager(27045):   ‼️  Uncaught Exception: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/~~s64XD8JwiidSUpprT9GPaQ==/com.ofermalls.myofer.stage-N5YS5VdvuvpqMWgZz5AI7w==/base.apk!classes8.dex)
E/TSLocationManager(27045): {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"backgroundPermissionRationale":{"title":"Allow {applicationName} to access this device's location even when closed or not in use?","message":"[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.","positiveAction":"Change to \"{backgroundPermissionOptionLabel}\"","negativeAction":""},"batchSync":false,"configUrl":"","crashDetector":{"enabled":false,"accelerometerThresholdHigh":20,"accelerometerThresholdLow":4.5,"gyroscopeThresholdHigh":20,"gyroscopeThresholdLow":4.5},"debug":true,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableProviderChangeRecord":false,"disableStopDetection":false,"distanceFilter":10,"elasticityMultiplier":1,"enableHeadless":true,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxMonitoredGeofences":97,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","channelId":"","smallIcon":"","largeIcon":"","priority":-1,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":0,"odometer":0,"isFirstBoot":false,"didLaunchInBackground":false,"didDeviceReboot":false}
E/TSLocationManager(27045): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/~~s64XD8JwiidSUpprT9GPaQ==/com.ofermalls.myofer.stage-N5YS5VdvuvpqMWgZz5AI7w==/base.apk!classes8.dex)
E/TSLocationManager(27045):     at com.transistorsoft.xms.g.location.SettingsClient.checkLocationSettings(Unknown Source:70)
E/TSLocationManager(27045):     at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.a(Unknown Source:29)
E/TSLocationManager(27045):     at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.a(Unknown Source:39)
E/TSLocationManager(27045):     at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.onCreate(Unknown Source:14)
E/TSLocationManager(27045):     at android.app.Activity.performCreate(Activity.java:8960)
E/TSLocationManager(27045):     at android.app.Activity.performCreate(Activity.java:8938)
E/TSLocationManager(27045):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
E/TSLocationManager(27045):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3975)
E/TSLocationManager(27045):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
E/TSLocationManager(27045):     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
E/TSLocationManager(27045):     at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
E/TSLocationManager(27045):     at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
E/TSLocationManager(27045):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
E/TSLocationManager(27045):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
E/TSLocationManager(27045):     at android.os.Handler.dispatchMessage(Handler.java:107)
E/TSLocationManager(27045):     at android.os.Looper.loopOnce(Looper.java:232)
E/TSLocationManager(27045):     at android.os.Looper.loop(Looper.java:317)
E/TSLocationManager(27045):     at android.app.ActivityThread.main(ActivityThread.java:8592)
E/TSLocationManager(27045):     at java.lang.reflect.Method.invoke(Native Method)
E/TSLocationManager(27045):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/TSLocationManager(27045):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
I/Process (27045): Sending signal. PID: 27045 SIG: 9
Lost connection to device.
```
	</summary>
</details>

**Comment by christocracy** [comment]
This has been posted *dozens* of times before.  Please *search the issues* before posting.

Duplicate #933

**Comment by asafvaron90** [comment]
Thanks, my bad.. I found the solution after opening the issue. Thanks
