### ISSUE TITLE
Error after app crashes doesnt run anymore

### ISSUE THREAD

**Issue by gcervantes2005** [transistorsoft/flutter_background_geolocation#160]
## Your Environment
* Plugin version: 
We get from GIT
flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git

* Platform: iOS or Android
Android
* OS version:
9.0.9
* Device manufacturer / model:
Oneplus 5
* Flutter info (`flutter doctor`):
~/development/mdcV4/mdc_v4$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
 static Map<String, dynamic> getDefaultConfig() {
    Map<String, dynamic> _toReturn = Map<String, dynamic>();
    //backgroundGeolocator
    _toReturn['bggeo_'] = 'aaa';
    _toReturn['desiredAccuracy'] = bg.Config.DESIRED_ACCURACY_HIGH;
    //_toReturn['bgeo_url']= _urlGpsData;
    _toReturn['bgeo_enableTimestampMeta'] = true;
    _toReturn['bgeo_forceReloadOnBoot'] = true;
    _toReturn['bgeo_distanceFilter'] = 10.0;
    _toReturn['bgeo_stopOnTerminate'] = false;
    _toReturn['bgeo_startOnBoot'] = true;
    _toReturn['bgeo_heartbeatInterval'] = 60;
    _toReturn['bgeo_preventSuspend'] = true;
    _toReturn['bgeo_autoSync'] = true;
    _toReturn['bgeo_autoSyncThreshold'] = 2;
    _toReturn['bgeo_maxBatchSize'] = 100;
    _toReturn['bgeo_batchSync'] = true;
    _toReturn['bgeo_debug'] = false;
    _toReturn['bgeo_logLevel'] = bg.Config.LOG_LEVEL_OFF;
    _toReturn['bgeo_reset'] = true;
    return _toReturn;
  }
```

## Expected Behavior
After a crash user shou;ld open app

## Actual Behavior
After app closes sometimes it can not be opened again, and on android console we get the log below on Debug Logs section
## Steps to Reproduce

1.
2.
3.
4.

## Context

Run on background the app on Android, it has been working ok but after last release we get this error.
## Debug logs

2019-12-08 15:05:25.211 30267-30267/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mdd.l, PID: 30267
    java.lang.RuntimeException: Unable to start service com.transistorsoft.locationmanager.service.HeartbeatService@25fab60 with Intent { flg=0x4 cmp=mdd.l/com.transistorsoft.locationmanager.service.HeartbeatService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3831)
        at android.app.ActivityThread.access$1800(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1789)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at com.transistorsoft.locationmanager.config.TSAuthorization.toJson(Unknown Source:11)
        at com.transistorsoft.locationmanager.adapter.TSConfig$Builder.b(Unknown Source:195)
        at com.transistorsoft.locationmanager.adapter.TSConfig$Builder.a(Unknown Source:0)
        at com.transistorsoft.locationmanager.adapter.TSConfig.toJson(Unknown Source:2)
        at com.transistorsoft.locationmanager.adapter.TSConfig.print(Unknown Source:20)
        at com.transistorsoft.locationmanager.adapter.TSConfig.load(Unknown Source:310)
        at com.transistorsoft.locationmanager.adapter.TSConfig.<init>(Unknown Source:67)
        at com.transistorsoft.locationmanager.adapter.TSConfig.a(Unknown Source:9)
        at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance(Unknown Source:14)
        at com.transistorsoft.locationmanager.service.AbstractService.a(Unknown Source:4)
        at com.transistorsoft.locationmanager.service.HeartbeatService.onStartCommand(Unknown Source:1)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3812)
        at android.app.ActivityThread.access$1800(ActivityThread.java:207) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1789) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-12-08 15:06:10.300 30330-30330/mdc.lertek E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mdc.lertek, PID: 30330
    java.lang.RuntimeException: Unable to start service com.transistorsoft.locationmanager.service.HeartbeatService@25fab60 with Intent { flg=0x4 cmp=mdc.lertek/com.transistorsoft.locationmanager.service.HeartbeatService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3831)
        at android.app.ActivityThread.access$1800(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1789)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at com.transistorsoft.locationmanager.config.TSAuthorization.toJson(Unknown Source:11)
        at com.transistorsoft.locationmanager.adapter.TSConfig$Builder.b(Unknown Source:195)
        at com.transistorsoft.locationmanager.adapter.TSConfig$Builder.a(Unknown Source:0)
        at com.transistorsoft.locationmanager.adapter.TSConfig.toJson(Unknown Source:2)
        at com.transistorsoft.locationmanager.adapter.TSConfig.print(Unknown Source:20)
        at com.transistorsoft.locationmanager.adapter.TSConfig.load(Unknown Source:310)
        at com.transistorsoft.locationmanager.adapter.TSConfig.<init>(Unknown Source:67)
        at com.transistorsoft.locationmanager.adapter.TSConfig.a(Unknown Source:9)
        at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance(Unknown Source:14)
        at com.transistorsoft.locationmanager.service.AbstractService.a(Unknown Source:4)
        at com.transistorsoft.locationmanager.service.HeartbeatService.onStartCommand(Unknown Source:1)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3812)
        at android.app.ActivityThread.access$1800(ActivityThread.java:207) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1789) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-12-08 15:06:10.322 2436-30372/? E/ndroid.systemu: Invalid ID 0x00000000.
2019-12-08 15:06:10.322 2436-30372/? E/ndroid.systemu: Invalid ID 0x00000000.
2019-12-08 15:06:11.497 30139-21304/? E/neplus.launche: Invalid ID 0x00000000.
2019-12-08 15:06:11.498 30139-21304/? E/neplus.launche: Invalid ID 0x00000000.
2019-12-08 15:06:11.570 5635-5716/? E/bt_osi_wakelock: wakelock_acquire wakelock acquired
2019-12-08 15:06:11.571 5635-5717/? E/bt_osi_wakelock: wakelock_release wakelock released
2019-12-08 15:06:11.572 5635-5716/? E/bt_osi_wakelock: wakelock_acquire wakelock acquired

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>flutter_background_geolocation:

So read the plugin's `pubspec.yaml`.  It has a version.

**Comment by gcervantes2005** [comment]
Sorry Chris, its

version: 0.3.4

**Comment by christocracy** [comment]
Do you know what the current version is?

Have you looked at the [CHANGELOG](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md)

**Comment by gcervantes2005** [comment]
I have my .YAML with

  ## Geolocation
   flutter_background_geolocation:
     git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
to hacve the latest version

I changed to
 ## Geolocation
  flutter_background_geolocation: '^1.3.2'
 

Will run tests again to see if it works

**Comment by gcervantes2005** [comment]
After adding this version it is working OK now, thanks for the guidance.

Isnt
flutter_background_geolocation:
git:
url: https://github.com/transistorsoft/flutter_background_geolocation.git

Suposed to get the latest version?
