### ISSUE TITLE
Crash on Android, only with appbundle

### ISSUE THREAD

**Issue by huulbaek** [transistorsoft/flutter_background_geolocation#165]
* Plugin version: Latest
* Platform: Android
* OS version: 10
* Device manufacturer / model: Google Pixel 3
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale da-DK)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (version 3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.40.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

## Expected Behavior
No crash

## Actual Behavior
The app crashes right away on the device. Works fine on emulators and on the device – but only when using APK. Appbundle only have started failing since latest flutter / plugin.

## Context
Publishing appbundle to Play as usual. Can publish fine without plugin (no crash).

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
2019-12-13 22:56:39.369 21583-21583/? I/Adreno: Build Config                     : S P 8.0.6 AArch64
2019-12-13 22:56:39.372 21583-21583/? I/Adreno: PFP: 0x016ee183, ME: 0x00000000
2019-12-13 22:56:39.423 21583-21583/? D/AndroidRuntime: Shutting down VM
2019-12-13 22:56:39.425 21583-21583/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.sikker.lodgeapp, PID: 21583
    java.lang.ExceptionInInitializerError
        at com.transistorsoft.locationmanager.b.C.d(Unknown Source:0)
        at c.f.a.a.F.<init>(:8)
        at c.f.a.a.F.a(:6)
        at g.a.c.a.a(:7)
        at net.sikker.lodgeapp.MainActivity.onCreate(:2)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at c.f.b.a.a(Unknown Source:27)
        at com.transistorsoft.locationmanager.b.C.<clinit>(Unknown Source:2)
        at com.transistorsoft.locationmanager.b.C.d(Unknown Source:0) 
        at c.f.a.a.F.<init>(:8) 
        at c.f.a.a.F.a(:6) 
        at g.a.c.a.a(:7) 
        at net.sikker.lodgeapp.MainActivity.onCreate(:2) 
        at android.app.Activity.performCreate(Activity.java:7825) 
        at android.app.Activity.performCreate(Activity.java:7814) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```
</details>

**Comment by christocracy** [comment]
>Plugin version: Latest

What version?

**Comment by huulbaek** [comment]
I notice that the app download size on Play with the plugin is 4.15 to 11.5 MB and 10.3 to 10.8 MB **without** the plugin which seems strange.

Also, native platforms is reported to **3** without plugin and **4** with plugin in Play.

Sorry about version, pulled directly from dev and then master minutes ago. Had to remove plugin to make a new build because the error made it into production without me noticing.

**Comment by christocracy** [comment]
I have the latest version `1.4.5` [published to Play Store](https://play.google.com/store/apps/details?id=com.transistorsoft.flutterbackgroundgeolocationexample) built to Bundle.

See the Android setup and make sure you've done *everything*, particularly the part about `proguard-rules`.

**Comment by huulbaek** [comment]
Thank you – it was the proguard stuff.
