### ISSUE TITLE
An error in my release application and I don't know what proves it

### ISSUE THREAD

**Issue by daviidmorales** [transistorsoft/flutter_background_geolocation#187]
An error in my release application and I don't know what proves it, the error is reported by crashlitycs
## Your Environment
* Plugin version: ^1.4.5
* Platform: Android
* OS version: 5.0.1, 5.1, 5.1.1, 6.0.1, 6.0, 7.0
* Device manufacturer / model: samsung (Galaxy J7,Galaxy J2,Galaxy J3), HUAWEI (Y6,P8 Lite)
* Plugin config:
```dart
await bg.BackgroundGeolocation.ready(
      bg.Config(
        reset: true,
        //debug: true,
        logLevel: bg.Config.LOG_LEVEL_OFF,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        distanceFilter: 75,
        //locationUpdateInterval: 5000,
        stopOnTerminate: false,
        forceReloadOnHeartbeat: true,
        foregroundService: true,
        //speedJumpFilter: 800,
        startOnBoot: true,
        enableHeadless: true,
        notification: bg.Notification(
          title: "Estas activo",
          text: "Servicio de localización activa",
        ),
      ),
    );
```

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
       at android.util.ContainerHelpers.binarySearch(ContainerHelpers.java:28)
       at android.util.ArrayMap.indexOf(ArrayMap.java:96)
       at android.util.ArrayMap.put(ArrayMap.java:465)
       at android.os.BaseBundle.putFloat(BaseBundle.java:407)
       at android.os.Bundle.putFloat(Bundle.java:324)
       at com.transistorsoft.locationmanager.location.TSLocationManager.buildTSLocation()
       at com.transistorsoft.locationmanager.location.TSLocationManager.onSingleLocationResult()
       at com.transistorsoft.locationmanager.service.LocationRequestService.a()
       at com.transistorsoft.locationmanager.service.LocationRequestService.a()
       at com.transistorsoft.locationmanager.service.LocationRequestService$a.run()
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```
``` <!-- syntax-highligting:  DO NOT REMOVE -->
Crashlytics Exception Handler1
       at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
       at java.lang.Thread.getStackTrace(Thread.java:580)
       at java.lang.Thread.getAllStackTraces(Thread.java:522)
       at com.crashlytics.android.core.CrashlyticsController.writeSessionEvent(CrashlyticsController.java:1340)
       at com.crashlytics.android.core.CrashlyticsController.writeFatal(CrashlyticsController.java:1027)
       at com.crashlytics.android.core.CrashlyticsController.access$500(CrashlyticsController.java:69)
       at com.crashlytics.android.core.CrashlyticsController$7.call(CrashlyticsController.java:328)
       at com.crashlytics.android.core.CrashlyticsController$7.call(CrashlyticsController.java:321)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:818)
```
```
pool-2-thread-1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```
</details>

**Comment by christocracy** [comment]
Weird.  How often does this happen?

**Comment by daviidmorales** [comment]
In the last 30 days we receive 47 reports of 16 user

**Comment by christocracy** [comment]
Show me some application code where you're using the plugin.

**Comment by christocracy** [comment]
I suggest you update to latest `1.7.0`.

also, it's not necessary to `removeListeners`.  If the plugin is `#stop`ped, location events are not going to fire.  Think of adding listeners like wiring up speakers to your stereo -- when you turn the power off on your stereo, you don't need to disconnect your speaker wires.  No music is going to play anyway.
