### ISSUE TITLE
After Gradle update, the app crashes on open

### ISSUE THREAD

**Issue by ms-facegraph** [transistorsoft/flutter_background_geolocation#192]
## Your Environment
* Plugin version: 1.6.1
* Platform:  Android
* OS version: Android 7.0
* Device manufacturer / model: Samsung Galaxy Note 5
* Flutter info (`flutter doctor`):

[√] Flutter (Channel stable, v1.12.13+hotfix.9-pre.1, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.35.1)
[√] Connected device (1 available)

• No issues found!

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
await bg.BackgroundGeolocation.ready(bg.Config(
        enableHeadless: true,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_INFO));
```
the app crashes before this code execution

## Expected Behavior
the app just open well !

## Actual Behavior
the app crashes on open after installing apk, while running well when run from Android Studio 

## Steps to Reproduce

1. build apk
2. install
3. open

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->

2020-02-16 21:19:55.027 17792-17792/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.facegraph.smilemein, PID: 17792
    java.lang.ExceptionInInitializerError
        at com.transistorsoft.locationmanager.b.a.a()
        at d.e.a.a.a.a()
        at d.e.a.a.b.a()
        at e.a.e.a.b()
        at com.facegraph.smilemein.MainActivity.onCreate()
        at android.app.Activity.performCreate(Activity.java:6942)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at d.e.b.a.a()
        at com.transistorsoft.locationmanager.b.a.<clinit>()
        at com.transistorsoft.locationmanager.b.a.a() 
        at d.e.a.a.a.a() 
        at d.e.a.a.b.a() 
        at e.a.e.a.b() 
        at com.facegraph.smilemein.MainActivity.onCreate() 
        at android.app.Activity.performCreate(Activity.java:6942) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
        at android.app.ActivityThread.-wrap14(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
```

</details>

**Comment by c-mendoza** [comment]
I'm having this issue as well. Installed the release apk on an emulator, Android 9, API 28, x86_64, when I run I seed the splash screen and then a crash. My is stack trace. the same as @ms-facegraph. Exception is the same:

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference`

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G3020, locale
    en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
[✓] VS Code (version 1.40.1)
[✓] Connected device (1 available)

**Comment by christocracy** [comment]
Show me your android/app/build.gradle

**Comment by c-mendoza** [comment]
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
// flutter_background_geolocation (must be placed after the lines above)
Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

    lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "net.terirueb.timesbeach"
        minSdkVersion 24
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release

//            minifyEnabled true
//            useProguard true
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.2-alpha02'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0-alpha02'
}
```

It compiles and runs in debug mode, but crashes right after starting in release mode, in either the emulator (x64) or any of the physical devices I tried.

**Comment by christocracy** [comment]
//            minifyEnabled true
//            useProguard true

Set minifyEnabled false.  You have it commented out.

**Comment by c-mendoza** [comment]
It fails with the following error when minifyEnabled is set to false:

```
* What went wrong:                                      A problem occurred evaluating root project 'android'.   > A problem occurred configuring project ':app'.           > Removing unused resources requires unused code shrinking to be turned on. See http://d.android.com/r/tools/shrink-resources.html for more information.
```

**Comment by christocracy** [comment]
There’s a link there with further instructions.

Removing unused resources requires unused code shrinking to be turned on. See http://d.android.com/r/tools/shrink-resources.html for more information.

**Comment by christocracy** [comment]
The plugin’s library is *already minified*.  If you don’t instruct your app to avoid re-minifying it (via its proguard-rules File), its namespaces are destroyed and you get error as in this issue.

**Comment by leetworx** [comment]
I'm seeing something similar (crash on release startup). Looks like perhaps I need to tweak proguard rules as well based on the error:

```
02-16 23:22:59.338 14238 14238 E AndroidRuntime: java.lang.ExceptionInInitializerError
02-16 23:22:59.338 14238 14238 E AndroidRuntime: 	at com.transistorsoft.locationmanager.b.a.a(Unknown Source:0)
02-16 23:22:59.338 14238 14238 E AndroidRuntime: 	at c.c.a.b.a.a(Unknown Source:28)
02-16 23:22:59.338 14238 14238 E AndroidRuntime: 	at c.c.a.b.b.a(Unknown Source:25)
02-16 23:22:59.338 14238 14238 E AndroidRuntime: 	at e.a.e.a.b(Unknown Source:103)
```

Do you have specific rules for use with the plugin (i.e. what to keep so things don't get mangled?)

**Comment by christocracy** [comment]
The required proguard-rules are included in the Android Setup document.

**Comment by christocracy** [comment]
```diff
apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

// flutter_background_geolocation (must be placed after the lines above)
+Project background_geolocation = project(':flutter_background_geolocation')
+apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

android {
+   compileSdkVersion rootProject.ext.compileSdkVersion
    .
    .
    .
    defaultConfig {
        .
        .
        .
+       targetSdkVersion rootProject.ext.targetSdkVersion
    }
    buildTypes {
        release {
            .
            .
            .
            minifyEnabled true
            // background_geolocation requires custom Proguard Rules with minifyEnabled
+           proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
        }
    }
}
```

**Comment by c-mendoza** [comment]
I get that some complexities are unavoidable, but I don't think that you should expect that the users of a cross-platform plugin and framework should be well versed in the intricacies of a specific platform. This runs against the whole point of Flutter and this very plugin. 

In any case, the following worked:

```
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            useProguard true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
        }
    }
```

**Comment by christocracy** [comment]
and can probably safely minifyEnabled true now.

This is a complex plugin.  Yes, you’re going to need to touch your app/build.gradle once in a while.  Do not blindly update the gradle version beyond that used by a freshly generated flutter app, even when prompted to do so by Android Studio.  You will get burned more often than not.

**Comment by ms-facegraph** [comment]
setting both 'minifyEnabled' and 'shrinkResources' to false solved the problem to me
I also had to set 'android.enableR8=false' in gradle.properties file

the line 'android.enableR8=true' was added after a gradle update, you're right we shouldn't just update gradle so often

the R8 is the new minifier, I think the documentation should contain a hint for it
