### ISSUE TITLE
Flutter Release Crash Channel stable, v1.12.13+hotfix.8 with flutter_background_geolocation: ^1.6.1

### ISSUE THREAD

**Issue by sago-traventures** [transistorsoft/flutter_background_geolocation#194]
## Your Environment
* Plugin version: 1.6.1
* Platform: iOS or Android
* OS version: 
* Device manufacturer / model: iPhone 6s and Samsung 
* Flutter info (`flutter doctor`):
Flutter Details:

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

Error:
--------- beginning of crash
2020-02-13 16:02:48.907 31340-31340/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sagotraventures.sago, PID: 31340
    java.lang.ExceptionInInitializerError
        at com.transistorsoft.locationmanager.b.E.a(Unknown Source:0)
        at f.n.a.a.G.a(:17)
        at f.n.a.a.H.a(:4)
        at h.a.d.a.a(:13)
        at com.sagotraventures.sago.MainActivity.onCreate(:2)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at f.n.b.a.a(Unknown Source:27)
        at com.transistorsoft.locationmanager.b.E.<clinit>(Unknown Source:2)
        at com.transistorsoft.locationmanager.b.E.a(Unknown Source:0) 
        at f.n.a.a.G.a(:17) 
        at f.n.a.a.H.a(:4) 
        at h.a.d.a.a(:13) 
        at com.sagotraventures.sago.MainActivity.onCreate(:2) 
        at android.app.Activity.performCreate(Activity.java:7458) 
        at android.app.Activity.performCreate(Activity.java:7448) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by christocracy** [comment]
Duplicate #192
