### ISSUE TITLE
NPE crash in BackgroundFetchPlugin.registerWith on app startup

### ISSUE THREAD

**Issue by livotov** [transistorsoft/flutter_background_geolocation#207]
## Your Environment
* Plugin version: 1.7.0
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: Google Nexus 5
* Flutter info:

[✓] Flutter (Channel dev, v1.15.20, on Mac OS X 10.14.6 18G1012, locale en-BG)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
[✓] Connected device (3 available)

* Plugin config:
```dart
bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 0,
            locationUpdateInterval: 60000,
            heartbeatInterval: 60000,
            stopOnTerminate: false,
            startOnBoot: true,
            debug: false,
            enableHeadless: true,
            logLevel: bg.Config.LOG_LEVEL_INFO,
            notification: bg.Notification(smallIcon: "drawable/ic_notification", largeIcon: "mipmap/ic_launcher", channelName: "orderStatusChanges"),
            reset: true))
```

## Expected Behavior
Normal app start

## Actual Behavior
App crashes on flutter plugin init

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'android.content.Context io.flutter.plugin.common.PluginRegistry$Registrar.context()' on a null object reference
       at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin.registerWith(BackgroundFetchPlugin.java:18)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:26)
       at io.papu.papuio.MainActivity.onCreate(MainActivity.kt:16)
       at android.app.Activity.performCreate(Activity.java:6251)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

## Steps to Reproduce
We see this from play store reports after rolling out app update with plugin v 1.7.0 included.
As per the current moment - only Nexus 5 Android 6.0.1 users are affected.

**Comment by christocracy** [comment]
Have you [upgraded your Flutter SDK to `> 1.12`](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)?  A custom Android `Application` extension is no longer required (thus [`registerWith` is no longer required](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md#headless-mechanism-with-enableheadless-true)?

**Comment by livotov** [comment]
Oh, that piece was missed... Will upgrade it now.
Thanks, I'll let you know how it goes

**Comment by livotov** [comment]
Thanks, this issue seems to be resolved after proper upgrade procedures.
