### ISSUE TITLE
Error crashing app release

### ISSUE THREAD

**Issue by marcosvcr84** [transistorsoft/flutter_background_geolocation#267]
*****************************************************************
Hello, my app is working well with flutter_background_geolocation library just on debug version.
When I released sometimes i'm getting the error above withe app crashing:

```
java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-3-thread-12
at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:793)
at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:726)
at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:153)
at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:239)
at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule$16.onFailure(BackgroundGeolocationModule.java:605)
at com.transistorsoft.locationmanager.http.HttpService.flush(Unknown Source:49)
at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$w0.run(Unknown Source:48)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
```
*****************************************************************

## Your Environment
* Plugin version: 1.7.3
* Platform: Android
* OS version: 9.0
* Device manufacturer / model: Samsung Galaxy A10
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.1 19B88, locale en-BR)
    • Flutter version 1.12.13+hotfix.9 at /Users/marcosvinicius/Development/flutter
    • Framework revision f139b11009 (6 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/marcosvinicius/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/marcosvinicius/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • SM A105M • RX8M80BTGED • android-arm • Android 9 (API 28)

! Doctor found issues in 2 categories.
```

* Plugin config:
```dart
void _configureBackgroundGeolocation() async {
    // 1.  Listen to events (See docs for all 13 available events).
    bg.BackgroundGeolocation.onLocation(_onLocation, _onLocationError);
    bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
    bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
    bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
    bg.BackgroundGeolocation.onHttp(_onHttp);
    bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);
    bg.BackgroundGeolocation.onHeartbeat(_onHeartbeat);
    bg.BackgroundGeolocation.onGeofence(_onGeofence);
    bg.BackgroundGeolocation.onSchedule(_onSchedule);
    bg.BackgroundGeolocation.onPowerSaveChange(_onPowerSaveChange);
    bg.BackgroundGeolocation.onEnabledChange(_onEnabledChange);
    bg.BackgroundGeolocation.onNotificationAction(_onNotificationAction);

    SharedPreferences prefs = await SharedPreferences.getInstance();
    String precision = prefs.get("precision");

    if (precision == "" || precision == null) {
      precision = "2";
    }

    var sound = prefs.get("sound");

    if (sound == null) {
      sound = false;
    }

    if (precision == '1') {
      var extraParams = {
        "identifier": this.widget.identifier,
        "precisionLevel": _selectedConfig
      };
      Map<String, Object> extras = new Map();
      extras.addAll(extraParams);

      // 2.  Configure the plugin
      bg.BackgroundGeolocation.ready(bg.Config(
              // Convenience option to automatically configure the SDK to post to Transistor Demo server.
              //transistorAuthorizationToken: token,
              // Logging & Debug
              reset: false,
              debug: sound,
              logLevel: bg.Config.LOG_LEVEL_VERBOSE,
              // Geolocation options
              desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
              distanceFilter: 0,
              locationUpdateInterval: 10000,
              stopTimeout: 1,
              // HTTP & Persistence
              url: "http://api.webrota.com.br:1200",
              method: "POST",
              extras: extras,
              autoSync: true,
              batchSync: true,
              // Application options
              stopOnTerminate: false,
              startOnBoot: true,
              enableHeadless: true,
              heartbeatInterval: 60))
          .then((bg.State state) {
        print('[ready] ${state.toMap()}');

        if (state.schedule.isNotEmpty) {
          bg.BackgroundGeolocation.startSchedule();
        }
        setState(() {
          _enabled = state.enabled;
          _isMoving = state.isMoving;
        });
      }).catchError((error) {
        print('[ready] ERROR: $error');
      });
    } else if (precision == '2') {
      var extraParams = {
        "identifier": this.widget.identifier,
        "precisionLevel": _selectedConfig
      };
      Map<String, Object> extras = new Map();
      extras.addAll(extraParams);
      // 2.  Configure the plugin
      bg.BackgroundGeolocation.ready(bg.Config(
              // Convenience option to automatically configure the SDK to post to Transistor Demo server.
              //transistorAuthorizationToken: token,
              // Logging & Debug
              reset: false,
              debug: sound,
              logLevel: bg.Config.LOG_LEVEL_VERBOSE,
              // Geolocation options
              desiredAccuracy: bg.Config.DESIRED_ACCURACY_MEDIUM,
              distanceFilter: 0,
              locationUpdateInterval: 30000,
              stopTimeout: 1,
              // HTTP & Persistence
              url: "http://api.webrota.com.br:1200",
              method: "POST",
              extras: extras,
              autoSync: true,
              batchSync: true,
              // Application options
              stopOnTerminate: false,
              startOnBoot: true,
              enableHeadless: true,
              heartbeatInterval: 60))
          .then((bg.State state) {
        print('[ready] ${state.toMap()}');

        if (state.schedule.isNotEmpty) {
          bg.BackgroundGeolocation.startSchedule();
        }
        setState(() {
          _enabled = state.enabled;
          _isMoving = state.isMoving;
        });
      }).catchError((error) {
        print('[ready] ERROR: $error');
      });
    } else if (precision == '3') {
      var extraParams = {
        "identifier": this.widget.identifier,
        "precisionLevel": _selectedConfig
      };
      Map<String, Object> extras = new Map();
      extras.addAll(extraParams);
      // 2.  Configure the plugin
      bg.BackgroundGeolocation.ready(bg.Config(
              // Convenience option to automatically configure the SDK to post to Transistor Demo server.
              //transistorAuthorizationToken: token,
              // Logging & Debug
              reset: false,
              debug: sound,
              logLevel: bg.Config.LOG_LEVEL_VERBOSE,
              // Geolocation options
              desiredAccuracy: bg.Config.DESIRED_ACCURACY_VERY_LOW,
              distanceFilter: 0,
              locationUpdateInterval: 60000,
              stopTimeout: 1,
              // HTTP & Persistence
              url: "http://api.webrota.com.br:1200",
              method: "POST",
              extras: extras,
              autoSync: true,
              batchSync: true,
              // Application options
              stopOnTerminate: false,
              startOnBoot: true,
              enableHeadless: true,
              heartbeatInterval: 60))
          .then((bg.State state) {
        print('[ready] ${state.toMap()}');

        if (state.schedule.isNotEmpty) {
          bg.BackgroundGeolocation.startSchedule();
        }
        setState(() {
          _enabled = state.enabled;
          _isMoving = state.isMoving;
        });
      }).catchError((error) {
        print('[ready] ERROR: $error');
      });
    }
  }
```

## Expected Behavior
When user plays one button to start capturing location I call backgroundgeolocation plugin to start getting geolocations and send to my server. 

## Actual Behavior
Sometimes it's working well, but on my phone with Android 9 when I play start on my app and stop and play again the app crashes with the error above.

## Steps to Reproduce

1. User play start button on the app calling this code:

```dart
void _onClickEnableV2(enabled) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setBool("alarm", true);

    _configureBackgroundGeolocation();
    _configureBackgroundFetch();

    _showLoading();
    if (enabled) {
      dynamic callback = (bg.State state) {
        print('[start] success: $state');
        setState(() {
          _enabled = state.enabled;
          _isMoving = state.isMoving;
        });
      };
      bg.State state = await bg.BackgroundGeolocation.state;
      if (state.trackingMode == 1) {
        bg.BackgroundGeolocation.start().then(callback);
      } else {
        bg.BackgroundGeolocation.startGeofences().then(callback);
      }
    } else {
      dynamic callback = (bg.State state) {
        print('[stop] success: $state');
        setState(() {
          _enabled = state.enabled;
          _isMoving = state.isMoving;
        });
      };
      bg.BackgroundGeolocation.stop().then(callback);
      _hideLoading();
    }
  }
```

2. The code about _configureBackgroundGeolocation() is above
3. Here we have the code about _configureBackgroundFetch() :

```dart
void _configureBackgroundFetch() async {
    BackgroundFetch.configure(
        BackgroundFetchConfig(
            minimumFetchInterval: 15,
            startOnBoot: true,
            stopOnTerminate: false,
            enableHeadless: true,
            requiresStorageNotLow: false,
            requiresBatteryNotLow: false,
            requiresCharging: false,
            requiresDeviceIdle: false,
            requiredNetworkType: NetworkType.NONE), (String taskId) async {
      print("[BackgroundFetch] received event $taskId");

      SharedPreferences prefs = await SharedPreferences.getInstance();
      int count = 0;
      if (prefs.get("fetch-count") != null) {
        count = prefs.getInt("fetch-count");
      }
      prefs.setInt("fetch-count", ++count);
      print('[BackgroundFetch] count: $count');

      if (taskId == 'flutter_background_fetch') {
        // Test scheduling a custom-task in fetch event.
        BackgroundFetch.scheduleTask(TaskConfig(
            taskId: "com.transistorsoft.customtask",
            delay: 5000,
            periodic: false,
            forceAlarmManager: true,
            stopOnTerminate: false,
            enableHeadless: true));
      }
      BackgroundFetch.finish(taskId);
    });

    // Test scheduling a custom-task.
    BackgroundFetch.scheduleTask(TaskConfig(
        taskId: "com.transistorsoft.customtask",
        delay: 10000,
        periodic: true,
        forceAlarmManager: true,
        stopOnTerminate: false,
        enableHeadless: true));
  }
```
4.

## Context
Get user update locations and send to my server

## Debug logs

<details>
	<summary>Logs</summary>

```
2020-05-11 19:16:13.451 4477-4535/? E/RequestManager_FLP: [FusedLocationApi] Location remove ad0f27e from br.com.webrota.wrtracker
2020-05-11 19:16:13.562 4477-4535/? E/RequestManager_FLP: [FusedLocationApi] Location request 4dd3df(PendingIntent) PRIORITY_HIGH_ACCURACY interval=0 from br.com.webrota.wrtracker (10313 foreground)
2020-05-11 19:16:13.623 4477-4535/? E/RequestManager_FLP: [LocationManagerService] Location request 65e4881(Listener) gps interval=0 from com.google.android.gms.persistent (10016 foreground)
2020-05-11 19:16:13.673 3622-5043/? E/BufferQueueProducer: [br.com.webrota.wrtracker/com.transistorsoft.locationmanager.activity.TSLocationManagerActivity[5827]#0] disconnect: not connected (req=1)
2020-05-11 19:16:14.640 4477-4535/? E/RequestManager_FLP: [FusedLocationApi] Location remove 4dd3df from br.com.webrota.wrtracker
2020-05-11 19:16:14.659 4477-4535/? E/RequestManager_FLP: [LocationManagerService] Location remove 65e4881 from com.google.android.gms.persistent
2020-05-11 19:16:14.659 4477-4535/? E/AppState_FLP: No active app info in refreshAppStateMap, time=700891687
2020-05-11 19:16:14.683 4477-4535/? E/RequestManager_FLP: [FusedLocationApi] Location remove 985b88a from br.com.webrota.wrtracker
2020-05-11 19:16:14.720 4477-4535/? E/GeofenceRequestManager_FLP: [GeofencingApi] AddGeofence 1 fences from br.com.webrota.wrtracker
2020-05-11 19:16:21.253 4477-4535/? E/RequestManager_FLP: [FusedLocationApi] Location remove 80bcb18 from br.com.webrota.wrtracker
2020-05-11 19:16:21.262 4477-4535/? E/RequestManager_FLP: [FusedLocationApi] Location remove 176f971 from br.com.webrota.wrtracker
2020-05-11 19:16:21.271 4477-4535/? E/GeofenceRequestManager_FLP: [GeofencingApi] RemoveGeofence from br.com.webrota.wrtracker / remaining fence = 0
2020-05-11 19:16:22.029 4033-4471/? E/Watchdog: !@Sync 1094 [2020-05-11 19:16:22.029] FD count : 474
2020-05-11 19:16:24.349 4477-4535/? E/RequestManager_FLP: [FusedLocationApi] Location remove e0ed356 from br.com.webrota.wrtracker
2020-05-11 19:16:24.359 4477-4535/? E/RequestManager_FLP: [FusedLocationApi] Location remove b385fd7 from br.com.webrota.wrtracker
2020-05-11 19:16:24.503 4477-4535/? E/RequestManager_FLP: [FusedLocationApi] Location remove b7e80c4 from br.com.webrota.wrtracker
2020-05-11 19:16:24.537 4477-4535/? E/RequestManager_FLP: [FusedLocationApi] Location request bb0bbad(PendingIntent) PRIORITY_HIGH_ACCURACY interval=0 from br.com.webrota.wrtracker (10313 foreground)
2020-05-11 19:16:24.543 5827-5935/? E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-10
    Process: br.com.webrota.wrtracker, PID: 5827
    java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-3-thread-10
        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:793)
        at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:726)
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:153)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:239)
        at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule$16.onFailure(BackgroundGeolocationModule.java:605)
        at com.transistorsoft.locationmanager.http.HttpService.flush(Unknown Source:49)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$w0.run(Unknown Source:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-05-11 19:16:24.548 5827-5935/? E/TSLocationManager: [c.t.l.a.BackgroundGeolocation$r0 uncaughtException] 
      ‼️  Uncaught Exception: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-3-thread-10
    {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"batchSync":true,"configUrl":"","debug":false,"deferTime":0,"desiredAccuracy":10,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableStopDetection":false,"distanceFilter":0,"elasticityMultiplier":1,"enableHeadless":true,"enableTimestampMeta":false,"encrypt":false,"extras":{"identifier":"41435239"},"fastestLocationUpdateInterval":-1,"forceReloadOnBoot":false,"forceReloadOnGeofence":false,"forceReloadOnHeartbeat":false,"forceReloadOnLocationChange":false,"forceReloadOnMotionChange":false,"forceReloadOnSchedule":false,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":60,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":30000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":1,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"http:\/\/api.webrota.com.br:1200","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":206.37351989746094,"isFirstBoot":false,"didLaunchInBackground":false}
    java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-3-thread-10
        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:793)
        at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:726)
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:153)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:239)
        at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule$16.onFailure(BackgroundGeolocationModule.java:605)
        at com.transistorsoft.locationmanager.http.HttpService.flush(Unknown Source:49)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$w0.run(Unknown Source:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-05-11 19:16:24.595 5978-5978/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-05-11 19:16:24.596 5978-5978/? E/Zygote: accessInfo : 1
2020-05-11 19:16:24.613 4477-4535/? E/RequestManager_FLP: [LocationManagerService] Location request 1447fca(Listener) gps interval=0 from com.google.android.gms.persistent (10016 foreground)
2020-05-11 19:16:24.615 5978-5978/? E/ng.android.loo: Not starting debugger since process cannot load the jdwp agent.
2020-05-11 19:16:24.675 4033-4178/? E/InputDispatcher: channel '4bed03e br.com.webrota.wrtracker/br.com.webrota.wrtracker.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-05-11 19:16:24.715 4033-4850/? E/WindowManager: win=Window{4bed03e u0 br.com.webrota.wrtracker/br.com.webrota.wrtracker.MainActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5436 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:2405 com.android.server.wm.AppWindowToken.setVisibility:551 
2020-05-11 19:16:24.737 3577-3577/? E/audit: type=1400 audit(1589235384.733:2015): avc:  denied  { write } for  pid=5978 comm="ng.android.lool" name="com.samsung.android.lool-ZXLR6cKSzkDPZQE1rVIxrA==" dev="mmcblk0p32" ino=723512 scontext=u:r:system_app:s0 tcontext=u:object_r:apk_data_file:s0 tclass=dir permissive=0 SEPF_SM-A105M_9_0002 audit_filtered
2020-05-11 19:16:24.737 3577-3577/? E/audit: type=1300 audit(1589235384.733:2015): arch=40000028 syscall=334 per=8 success=no exit=-13 a0=ffffff9c a1=e40fc500 a2=2 a3=0 items=0 ppid=3592 pid=5978 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 comm="ng.android.lool" exe="/system/bin/app_process32" subj=u:r:system_app:s0 key=(null)
2020-05-11 19:16:24.737 3577-3577/? E/audit: type=1327 audit(1589235384.733:2015): proctitle="com.samsung.android.lool"
2020-05-11 19:16:24.737 3577-3577/? E/audit: type=1400 audit(1589235384.733:2016): avc:  denied  { write } for  pid=5978 comm="ng.android.lool" name="com.samsung.android.lool-ZXLR6cKSzkDPZQE1rVIxrA==" dev="mmcblk0p32" ino=723512 scontext=u:r:system_app:s0 tcontext=u:object_r:apk_data_file:s0 tclass=dir permissive=0 SEPF_SM-A105M_9_0002 audit_filtered
2020-05-11 19:16:24.737 3577-3577/? E/audit: type=1300 audit(1589235384.733:2016): arch=40000028 syscall=322 per=8 success=no exit=-13 a0=ffffff9c a1=dc2b8780 a2=20042 a3=1b6 items=0 ppid=3592 pid=5978 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 comm="ng.android.lool" exe="/system/bin/app_process32" subj=u:r:system_app:s0 key=(null)
2020-05-11 19:16:24.737 3577-3577/? E/audit: type=1327 audit(1589235384.733:2016): proctitle="com.samsung.android.lool"
2020-05-11 19:16:24.757 5257-6946/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2020-05-11 19:16:24.758 4477-4535/? E/PowerMonitor_FLP: Add GPS power, powerConsume=0.0, total duration=0.0, for br.com.webrota.wrtracker
2020-05-11 19:16:24.758 5257-6946/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2020-05-11 19:16:24.773 6399-6453/? E/PBSessionCacheImpl: sessionId[28144688842015969] not persisted.
2020-05-11 19:16:24.779 5998-5998/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-05-11 19:16:24.780 5998-5998/? E/Zygote: accessInfo : 1
2020-05-11 19:16:24.802 5998-5998/? E/brota.wrtracke: Not starting debugger since process cannot load the jdwp agent.
2020-05-11 19:16:24.806 4477-4535/? E/RequestManager_FLP: [LocationManagerService] Location remove 1447fca from com.google.android.gms.persistent
2020-05-11 19:16:24.816 4477-4535/? E/PowerMonitor_FLP: Add GPS power, powerConsume=0.001475, total duration=0.059, for br.com.webrota.wrtracker
2020-05-11 19:16:24.869 4477-4535/? E/RequestManager_FLP: [LocationManagerService] Location request 8bd4ff6(Listener) gps interval=0 from com.google.android.gms.persistent (10016 foreground)
2020-05-11 19:16:24.967 6027-6027/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-05-11 19:16:24.968 6027-6027/? E/Zygote: accessInfo : 1
2020-05-11 19:16:24.985 6027-6027/? E/android.dqagen: Not starting debugger since process cannot load the jdwp agent.
2020-05-11 19:16:25.101 3704-3784/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
2020-05-11 19:16:25.788 4477-4535/? E/RequestManager_FLP: [FusedLocationApi] Location remove bb0bbad from br.com.webrota.wrtracker
2020-05-11 19:16:25.808 4477-4535/? E/RequestManager_FLP: [LocationManagerService] Location remove 8bd4ff6 from com.google.android.gms.persistent
2020-05-11 19:16:25.809 4477-4535/? E/AppState_FLP: No active app info in refreshAppStateMap, time=700902836
2020-05-11 19:16:25.894 5978-6023/? E/FasUtils: pkg=null userId=0 has no information
2020-05-11 19:16:26.014 5978-6023/? E/FasUtils: pkg=null userId=0 has no information
2020-05-11 19:16:26.132 5978-6023/? E/FasUtils: pkg=null userId=0 has no information
2020-05-11 19:16:26.176 5978-6023/? E/FasUtils: pkg=null userId=0 has no information
2020-05-11 19:16:26.340 5978-6023/? E/FasUtils: pkg=null userId=0 has no information
2020-05-11 19:16:26.498 5978-6023/? E/FasUtils: pkg=null userId=0 has no information
2020-05-11 19:16:27.938 6101-6101/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-05-11 19:16:27.939 6101-6101/? E/Zygote: accessInfo : 1
2020-05-11 19:16:27.958 6101-6101/? E/.devicesecurit: Not starting debugger since process cannot load the jdwp agent.
2020-05-11 19:16:28.232 6116-6116/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-05-11 19:16:28.234 6116-6116/? E/Zygote: accessInfo : 1
2020-05-11 19:16:28.262 6116-6116/? E/ng.storyservic: Not starting debugger since process cannot load the jdwp agent.
2020-05-11 19:16:52.041 4033-4471/? E/Watchdog: !@Sync 1095 [2020-05-11 19:16:52.041] FD count : 473

```

</details>

**Comment by christocracy** [comment]
>Plugin version: latest from Git

This is meaningless the the next time I post a commit, which might be in an hour from now.

**Comment by christocracy** [comment]
Please **syntax highlight** your code.
![](https://dl.dropbox.com/s/fshg1w6w22gtixp/Screenshot%202020-05-11%2018.35.32.png?dl=1)

**Comment by marcosvcr84** [comment]
Editted post

**Comment by christocracy** [comment]
And the version hash.

**Comment by marcosvcr84** [comment]
Editted version

**Comment by christocracy** [comment]
I see the problem.  Fix is coming today.

**Comment by marcosvcr84** [comment]
Ok, thank you very much , I will wait for solution

**Comment by upmauro** [comment]
any prediction for the correction?

**Comment by christocracy** [comment]
*soon*.

**Comment by christocracy** [comment]
Merged to master.  Try installing [from git](https://github.com/transistorsoft/flutter_background_geolocation#or-latest-from-git)

**Comment by christocracy** [comment]
Once I get feedback, this version is ready to publish.

**Comment by marcosvcr84** [comment]
I'm still getting the same error, installing from git.

`2020-05-13 18:54:12.166 28375-28422/? E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: br.com.webrota.wrtracker, PID: 28375
    java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-3-thread-1
        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:793)
        at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:726)
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:153)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:239)
        at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule$16.onFailure(BackgroundGeolocationModule.java:605)
        at com.transistorsoft.locationmanager.http.HttpService.flush(Unknown Source:49)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$w0.run(Unknown Source:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-05-13 18:54:12.174 28375-28422/? E/TSLocationManager: [c.t.l.a.BackgroundGeolocation$r0 uncaughtException] 
      ‼️  Uncaught Exception: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-3-thread-1
    {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"batchSync":true,"configUrl":"","debug":false,"deferTime":0,"desiredAccuracy":10,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableStopDetection":false,"distanceFilter":0,"elasticityMultiplier":1,"enableHeadless":true,"enableTimestampMeta":false,"encrypt":false,"extras":{"identifier":"073335"},"fastestLocationUpdateInterval":-1,"forceReloadOnBoot":false,"forceReloadOnGeofence":false,"forceReloadOnHeartbeat":false,"forceReloadOnLocationChange":false,"forceReloadOnMotionChange":false,"forceReloadOnSchedule":false,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":60,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":30000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":1,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"http:\/\/api.webrota.com.br:1200","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":true,"didLaunchInBackground":false}`

**Comment by christocracy** [comment]
Show me your commit hash from pubspec.lock

**Comment by marcosvcr84** [comment]
Here comes:

`flutter_background_geolocation:
    dependency: "direct main"
    description:
      path: "."
      ref: HEAD
      resolved-ref: cf0ccd53a1615f5479d75bb6f09d209e5b23eb29
      url: "https://github.com/transistorsoft/flutter_background_geolocation.git"
    source: git
    version: "1.7.3"`

**Comment by christocracy** [comment]
You've not installed the latest **from git `master`**, which is commit #783b7a2cddd488e171e9824eee6ab8655fef7730 (and version `1.8.0`)

Btw, protip:  *multiline* syntax-highlighting is engaged with **3 backticks** + optional language:
![](https://dl.dropbox.com/s/2yckzkixgwifru1/Screenshot%202020-05-13%2018.16.19.png?dl=1)

**Comment by marcosvcr84** [comment]
Now it's ok, we will continue on testings, but it didn't crash anymore
Thank you very much
