### ISSUE TITLE
Crash report by Play Store pre-launch report details - urgent help

### ISSUE THREAD

**Issue by oemdaro** [transistorsoft/flutter_background_geolocation#323]
## Your Environment
* Plugin version: 1.9.0
* Platform: Android
* OS version: 7.0 (SDK 24), 8.0 (SDK 26) and 10 (SDK 29)
* Device manufacturer / model: 

  - Huawei Mate 9 Android 7.0 (SDK 24)
  - Motorola Moto Z Droid Android 7.0 (SDK 24)
  - Samsung Galaxy S9 Android 8.0 (SDK 26)
  - Sony Xperia XZ1 Compact Android 8.0 (SDK 26)
  - Google Pixel 3 Android 9 (SDK 28)
  - Google Pixel 4 Android 10 (SDK 29)
  - Nokia Nokia 1 Android 8.1 (SDK 27)

* Flutter info (`flutter doctor`):
```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-KH)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

• No issues found!
```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Future<void> _initBackgroundGeolocation() async {
    bg.BackgroundGeolocation.onLocation(_updateLocation, _onLocationError);

    bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      // distanceFilter: 10,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      enableHeadless: true,
      stopOnTerminate: false,
      startOnBoot: true,
      autoSync: false,
      reset: true,
      maxDaysToPersist: 1,
      // Just to make sure it not sent user data to another server.
      url: 'https://selfquarantine.jizo.io/api/locations',
      debug: false,
      logLevel: bg.Config.LOG_LEVEL_INFO,
      locationAuthorizationRequest: "Always",
      locationAuthorizationAlert: {
        'titleWhenNotEnabled': 'Location Services not enabled',
        'titleWhenOff': 'Location Services OFF',
        'instructions':
            'Update your settings to Always Allow so Self-Quarantine can working properly.',
        'cancelButton': 'Cancel',
        'settingsButton': 'Turn on',
      },
    )).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start().then((bg.State state) {
          print('[start] success - $state');
        });
      }
    });
  }
```

## Steps to Reproduce

1. Release build:

```shell
flutter build appbundle \
	--flavor prod \
	--obfuscate \
	--split-debug-info=build/debug/info/appbundle
```

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
FATAL EXCEPTION: main
Process: io.jizo.selfquarantine, PID: 10830
java.lang.ExceptionInInitializerError
	at com.transistorsoft.locationmanager.b.a.d0()
	at e.e.a.a.a.a0()
	at e.e.a.a.b.onAttachedToActivity()
	at io.flutter.embedding.engine.c.h()
	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith()
	at io.jizo.selfquarantine.MainActivity.w()
	at io.flutter.embedding.android.e.g()
	at io.flutter.embedding.android.d.onCreate()
	at android.app.Activity.performCreate(Activity.java:6910)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at e.e.b.a.e()
	at com.transistorsoft.locationmanager.b.a.<clinit>()
	... 20 more
```

</details>

**Comment by christocracy** [comment]
Are you *sure* you implemented *all* the [Setup Instructions](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#androidappbuildgradle)?

Before deploying to Play Store, you should *always* first install the build onto your device connected to USB.

**Comment by oemdaro** [comment]
Yes, it's working on my friend's phone: Samsung Note 8, Samsung Galaxy A10.

**Comment by oemdaro** [comment]
This below settings require?
```
+       appCompatVersion    = "1.0.2"           // or higher
+       playServicesLocationVersion = "17.0.0"  // or higher
```

My build.gradle

```
buildscript {
    ext.kotlin_version = '1.3.72'
    ext.appdistribution_version = '1.3.1'
    ext.gms_version = '4.3.3'
    ext {
        compileSdkVersion   = 29
        targetSdkVersion    = 29
    }
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.google.gms:google-services:$gms_version"
        classpath "com.google.firebase:firebase-appdistribution-gradle:$appdistribution_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            // [required] flutter_background_geolocation
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by christocracy** [comment]
Please follow the *Android Setup* **exactly**.

**Comment by oemdaro** [comment]
Yes, Let me try.

This is app/build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.appdistribution'

// flutter_background_geolocation
Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
    }

    defaultConfig {
        applicationId "io.jizo.selfquarantine"
        minSdkVersion 16
        targetSdkVersion rootProject.ext.targetSdkVersion
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            firebaseAppDistribution {
                releaseNotesFile = "../release-notes.txt"
                groupsFile = "../tester-groups.txt"
            }
        }
    }

    flavorDimensions "app"

    productFlavors {
        dev {
            dimension "app"
            resValue "string", "app_name", "Dev Quarantine"
        }
        prod {
            dimension "app"
            resValue "string", "app_name", "Quarantine"
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'androidx.multidex:multidex:2.0.1'
}
```

**Comment by christocracy** [comment]
You have **NOT** followed the *Android Setup* **exactly**.  Read the *Android Setup* and follow the directions **exactly**, adding all the **green** lines.

**Comment by oemdaro** [comment]
After adding all green lines (but not `minifyEnabled true`, because it cause Google maps to error), and downgrade Android Gradle plugin from `4.0.0` back to `3.5.0` and Gradle version to `gradle-5.6.2-all`, it works.

Sorry about that.

**Comment by christocracy** [comment]
>(but not minifyEnabled true)

Yes you *are*:
```
flutter build appbundle \
	--flavor prod \
	--obfuscate \. <------------------------------------ minifyEnabled
	--split-debug-info=build/debug/info/appbundle
```

**Comment by christocracy** [comment]
>Gradle plugin from 4.0.0 back to 3.5.0

I develop with `gradle-plugin @ 4.0.0` and so does the [`/example` in this repo](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/build.gradle#L16)

**Comment by oemdaro** [comment]
Thank you so much. I misunderstand about `--obfuscate`. I think it's just minify the dart code.
