### ISSUE TITLE
Help - java.lang.ExceptionInInitializerError on APK build

### ISSUE THREAD

**Issue by Davestring** [transistorsoft/flutter_background_geolocation#380]
Hi, I'm using the flutter_background_geolocation plugin in my app, I have bought the license to unlock android and the problem that I have it's that when I'm run "flutter run" and "flutter run --release" everything goes OK, but when I'm run "flutter build apk" and then install that APK in my device the app crashes at open. I attach the required info bellow.

* Plugin version: ^1.9.3
* Platform: Android
* OS version: 9
* Device manufacturer / model: Nokia
* Flutter info (`flutter doctor`):

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale es-MX)
    • Flutter version 1.17.5 at /Users/davidmartinez/flutter
    • Framework revision 8af6b2f038 (8 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/davidmartinez/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • TA 1025 • PLEGAR2770217092 • android-arm64 • Android 9 (API 28)

• No issues found!

* Plugin config:

```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.BackgroundGeolocation.ready(
      bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 1.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        preventSuspend: true,
        heartbeatInterval: 60,
      ),
    ).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
});
```

## Expected Behavior
The app must not crash on open

## Actual Behavior
The app crashes on open only when "flutter build apk" and "flutter install" is run, with "flutter run --debug or --release" I have no issue.

## Context
I'm trying to test the heartbeat and the plugin to use it in deep, im putting this code after the plugin config in the initState function:

```dart
bg.BackgroundGeolocation.onHeartbeat((bg.HeartbeatEvent event) {
      _logger.wtf('MapScreen - Heartbeat: $event');
});
```

## Debug logs

<details>
	<summary> Android studio logcat

``` <!-- syntax-highligting:  DO NOT REMOVE -->
020-08-23 15:34:39.750 30502-30502/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.test PID: 30502
    java.lang.ExceptionInInitializerError
        at com.transistorsoft.locationmanager.b.a.r(Unknown Source:0)
        at e.h.a.a.a.a(Unknown Source:31)
        at e.h.a.a.b.onAttachedToActivity(Unknown Source:8)
        at io.flutter.embedding.engine.c.a(Unknown Source:106)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:83)
        at com.test.test.MainActivity.b(Unknown Source:5)
        at io.flutter.embedding.android.e.a(Unknown Source:64)
        at io.flutter.embedding.android.d.onCreate(Unknown Source:22)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at e.h.b.a.a(Unknown Source:27)
        at com.transistorsoft.locationmanager.b.a.<clinit>(Unknown Source:2)
        at com.transistorsoft.locationmanager.b.a.r(Unknown Source:0) 
        at e.h.a.a.a.a(Unknown Source:31) 
        at e.h.a.a.b.onAttachedToActivity(Unknown Source:8) 
        at io.flutter.embedding.engine.c.a(Unknown Source:106) 
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:83) 
        at com.test.test.MainActivity.b(Unknown Source:5) 
        at io.flutter.embedding.android.e.a(Unknown Source:64) 
        at io.flutter.embedding.android.d.onCreate(Unknown Source:22) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:198) 
        at android.app.ActivityThread.main(ActivityThread.java:6729)
```

</summary>

</details>

## app/build.gradle config

```Gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "..."
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        targetSdkVersion rootProject.ext.targetSdkVersion
    }

    signingConfigs {
        release {
           ...
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
}

apply plugin: 'com.google.gms.google-services'
```

## build.gradle config

```Gradle
buildscript {
    ext.kotlin_version = '1.3.50'
    ext {
        compileSdkVersion = 28
        targetSdkVersion = 28
        appCompatVersion = "1.1.0"
        playServicesLocationVersion = "17.0.0"
    }
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by christocracy** [comment]
Review the *Android Setup*.  Ensure you’ve applied all the steps.  You’ve missed a step.

**Comment by Davestring** [comment]
> Review the _Android Setup_. Ensure you’ve applied all the steps. You’ve missed a step.

Oh, sorry, yes the proguard config was missing. Thanks you so much, I'm gonna close this issue.
