### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by luisbazan** [transistorsoft/flutter_background_geolocation#415]
I'm using the Crashlytics tool to monitor my app and I'm getting this error message sometimes:

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.b.b.d' on a null object reference
       at io.flutter.embedding.engine.loader.FlutterLoader.initResources(FlutterLoader.java)
       at io.flutter.view.FlutterMain.ensureInitializationComplete(FlutterMain.java)
       **at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.startBackgroundIsolate(HeadlessTask.java)
       at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.dispatch(HeadlessTask.java)
       at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.run(HeadlessTask.java)**
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6351)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)

But I cannot reproduce the issue locally, any idea which value could throw this NullPointerException?

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
// 2.  Configure the plugin
    bg.BackgroundGeolocation.ready(bg.
    Config(
        url: '${ENV.API_LOCATION}',
        headers: {"Authorization": 'Bearer ' + tokenResult.token},
        params: {
              "user_email": widget.user.email,
              "isVendor": widget.isCallFromVendor,
              "route": widget.user.route,
              "jobId": _dateSelected,
              "mobile": deviceParams,
              "device": apiAuth.deviceInfo.toMap()
            },
        reset: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        // Geolocation options
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
        notification: bg.Notification(
          text: "Servicio de ubicación activado"
        ),
        distanceFilter: widget.user.setting.config.distanceFilter,
        stopTimeout: widget.user.setting.config.stopTimeout,
        // HTTP & Persistence
        autoSync: true,
        autoSyncThreshold: widget.user.setting.config.autoSyncThreshold,
        batchSync: widget.user.setting.config.autoSyncThreshold > 0,
        schedule: widget.user.setting.config.schedule,
        scheduleUseAlarmManager: true,
        // Application options
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        maxDaysToPersist: widget.user.setting.config.maxDaysToPersist,
        logMaxDays: widget.user.setting.config.logMaxDays,
        heartbeatInterval: widget.user.setting.config.heartbeatInterval
    )).then((bg.State state) {
      print('[ready] ${state.toMap()}');

      dynamic callback = (bg.State state) {
        print('[start] success: $state');
        if(state.enabled) {
          Utils.snackBarMessage(_scaffoldKey, "El servicio de ubicación fue activado 😎");
          bg.BackgroundGeolocation.changePace(true).catchError((onError)=> Utils.snackBarError(_scaffoldKey,'$onError'));
        }
        setState(() {
          _enabled = state.enabled;
        });
      };

      if(forceStart) {
        bg.BackgroundGeolocation.start().then(callback).catchError((onError)=> Utils.snackBarError(_scaffoldKey,'Error al iniciar servicio de ubicacion: $onError'));
      } else {
        if (state.schedule.isNotEmpty) {
          bg.BackgroundGeolocation.startSchedule().then(callback).catchError((onError)=> Utils.snackBarError(_scaffoldKey,'Error al iniciar servicio de ubicacion: $onError'));
        }
      }

    }).catchError((onError)=> Utils.snackBarError(_scaffoldKey,'$onError'));
  }
```
![image](https://user-images.githubusercontent.com/17059693/94744578-d61ccf00-033e-11eb-83eb-cd635eb57267.png)
![image](https://user-images.githubusercontent.com/17059693/94744731-17ad7a00-033f-11eb-8b0e-40571abe0ff7.png)

**Comment by christocracy** [comment]
Crash is within Flutter framework, not the library.

**Comment by luisbazan** [comment]
Hello Chris,

I need your help, do you know what does the below issue mean?

10-14 08:53:01.637 INFO [BackgroundTaskManager onStartJob] ⏳ startBackgroundTask: 1
**10-14 08:53:01.661 ERROR [a d]** 
  **‼️  Failed to deduce Application's BuildConfig class for package name:com.grupovega.vmaps or com.grupovega**
10-14 08:53:01.666 DEBUG [TSGeofenceManager$e run] evaluation buffer timer elapsed
10-14 08:53:01.672 DEBUG [AbstractService onDestroy] 
  
or how can I get more details of the issue?

On another hand, how can I configure the logs to  be sent to a server when it encounters such errors? is that possible to do that?

Thank so much for your time.

**Comment by christocracy** [comment]
- Post your `android/app/build.gradle`
- From your `AndroidManifest.xml`, post the `<manifest>` element, eg:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.foo7">
```

**Comment by luisbazan** [comment]
Here you are:

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

// flutter_background_geolocation (must be placed after the lines above)
Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.grupovega.vmaps"
        minSdkVersion 21
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources false
            useProguard true 
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
        }
    }

}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
}

```

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.grupovega.vmaps">
```

**Comment by christocracy** [comment]
With the plugin configured for `LOG_LEVEL_VERBOSE`, show me `$ adb logcat *:S TSLocationManager:V` of your app booting.

**Comment by christocracy** [comment]
Also, the issue template asked for the following information:

>Flutter info (flutter doctor):
