### ISSUE TITLE
Android: Failed to deduce Application's BuildConfig class for package name

### ISSUE THREAD

**Issue by IRIG** [transistorsoft/flutter_background_geolocation#417]
## Your Environment
* Plugin version: 1.10.1
* Platform: Android
* OS version: 7 and 11
* Device manufacturer / model: Samsung Galaxy S6 and Google Pixel 4
* Flutter info (`flutter doctor`): Flutter stable, 1.20.4, Dart version 2.9.2
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
BackgroundFetchConfig(
          minimumFetchInterval: 15,
          startOnBoot: true,
          stopOnTerminate: false,
          enableHeadless: true,
          requiresStorageNotLow: false,
          requiresBatteryNotLow: false,
          requiresCharging: false,
          requiresDeviceIdle: false,
          requiredNetworkType: NetworkType.NONE), (String taskId) async {
  ...
```

## Expected Behavior

When background geo location is running it should not cause a java.lang.ClassNotFoundException.
## Actual Behavior

Console output displays the follwing error message:
```
D/TSLocationManager(23699): [c.t.l.service.AbstractService a] 
D/TSLocationManager(23699):   🎾  LocationRequestService [eventCount: 1]
I/TSLocationManager(23699): [c.t.l.s.LocationRequestService b] 
I/TSLocationManager(23699): ╔═════════════════════════════════════════════
I/TSLocationManager(23699): ║ getCurrentPosition LocationResult: 7
I/TSLocationManager(23699): ╠═════════════════════════════════════════════
I/TSLocationManager(23699): ╟─ 📍  Location[fused 47.308129,8.518898 hAcc=14 et=+4d8h41m0s778ms alt=558.699951171875 vel=0.09314235 bear=161.82611 vAcc=3 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 1031ms, time: 1602002202761
D/TSLocationManager(23699): [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 20.0
D/TSLocationManager(23699): [c.t.l.s.LocationRequestService b] SingleLocationRequest 7 isFinished? false
D/TSLocationManager(23699): [c.t.l.service.AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
E/TSLocationManager(23699): [c.t.locationmanager.util.a d]
E/TSLocationManager(23699):   ‼️  Failed to deduce Application's BuildConfig class for package name:[name of app package is displayed here]
java.lang.ClassNotFoundException: [name of app package is displayed here].BuildConfig
W/System.err(23699): 	at java.lang.Class.classForName(Native Method)
W/System.err(23699): 	at java.lang.Class.forName(Class.java:454)
W/System.err(23699): 	at java.lang.Class.forName(Class.java:379)
W/System.err(23699): 	at com.transistorsoft.locationmanager.util.a.d(Unknown Source:39)
W/System.err(23699): 	at com.transistorsoft.locationmanager.util.a.a(Unknown Source:11)
W/System.err(23699): 	at com.transistorsoft.locationmanager.util.a.b(Unknown Source:0)
W/System.err(23699): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.isMainActivityActive(Unknown Source:105)
W/System.err(23699): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation._onLocationChange(Unknown Source:0)
W/System.err(23699): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(23699): 	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
W/System.err(23699): 	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
W/System.err(23699): 	at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
W/System.err(23699): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(23699): 	at android.os.Looper.loop(Looper.java:223)
W/System.err(23699): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
W/System.err(23699): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(23699): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/System.err(23699): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
W/System.err(23699): Caused by: java.lang.ClassNotFoundException: Didn't find class "[name of app package is displayed here].BuildConfig" on path: DexPathList[[zip file "/data/app/~~N8Ly5ijXXrGvQBo2ZPnRqw==/[name of app package is displayed here]-FJP_9TYksiiEAKh4Q-4JVw==/base.apk"],nativeLibraryDirectories=[/data/app/~~N8Ly5ijXXrGvQBo2ZPnRqw==/[name of app package is displayed here]-FJP_9TYksiiEAKh4Q-4JVw==/lib/arm64, /data/app/~~N8Ly5ijXXrGvQBo2ZPnRqw==/[name of app package is displayed here]-FJP_9TYksiiEAKh4Q-4JVw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
W/System.err(23699): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
W/System.err(23699): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err(23699): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err(23699): 	... 18 more

```

**Important: Background geo location seems to work well but in the console output the above error message appears whenever TSLocationManager is firing/processing an event.

## Steps to Reproduce

1. buiild the app in debug mode
2. run the app on a physical device
3. look at the console log
4.

## Context

Testing the app on physical Android devices.
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Please see example log output above.
```

</details>

**Comment by christocracy** [comment]
Show me your `android/app.build.gradle`

**Comment by christocracy** [comment]
Also, you've posted your config for `BackgroundFetchConfig`, not the one for `flutter_background_geolocation`

**Comment by IRIG** [comment]
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.firebase.crashlytics'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

// flutter_background_geolocation (must be placed after the lines above)
Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "[package name]"
        minSdkVersion 23
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            shrinkResources false
            // background_geolocation requires custom Proguard Rules with minifyEnabled
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.google.firebase:firebase-messaging:20.2.4'
    implementation 'com.google.firebase:firebase-crashlytics:17.2.1'
    implementation 'com.google.firebase:firebase-analytics:17.5.0'
}
apply plugin: 'com.google.gms.google-services'
```

**Comment by christocracy** [comment]
Knowing your `applicationId` is *crucial* to debugging this.

**Comment by IRIG** [comment]
> Also, you've posted your config for `BackgroundFetchConfig`, not the one for `flutter_background_geolocation`

Sorry! Here is the one for background geolocation

```
bg.BackgroundGeolocation.ready(bg.Config(
      reset: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10.0,
      stopOnTerminate: false,
      startOnBoot: true,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      enableHeadless: true,
      heartbeatInterval: 15 * 60, // interval in seconds, works for iOS only, if preventSuspend true
    )).then((bg.State state) async {
```

**Comment by christocracy** [comment]
`enableHeadless: true,` did you `BackgroundGeolocation.registerHeadlessTask` in your `main.dart`?

**Comment by IRIG** [comment]
> Knowing your `applicationId` is _crucial_ to debugging this.

```
applicationId "ch.creagy.freewalker.app.pu"
```

**Comment by christocracy** [comment]
Does that `applicationId` match that in `AndroidManifest.xml` `package` attribute?

**Comment by IRIG** [comment]
> `enableHeadless: true,` did you `BackgroundGeolocation.registerHeadlessTask` in your `main.dart`?

Yes, as described in your instructions. And when killing the app and looking at the healdless console output, it works fine and without the above exception.

**Comment by IRIG** [comment]
> Does that `applicationId` match that in `AndroidManifest.xml` `package` attribute?

Do you mean the value for android:name in the manifest file?

**Comment by christocracy** [comment]
No:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.transistorsoft.foo7">        // <------------------ THIS
```

**Comment by IRIG** [comment]
> No:
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     xmlns:tools="http://schemas.android.com/tools"
>     package="com.transistorsoft.foo7">        // <------------------ THIS
> ```

No, you're right! There was one different letter. I had to change it in different AndroidManifest.XML files, in Application.kt and MainActivity.kt.

Now the error message disappeared.

Thank you for your fast and effective support!

Just for curiosity: Did this exception have an impact on the proper running of your plugin?

**Comment by christocracy** [comment]
I've just generated a fresh new Flutter app, installed & setup the plugin according to the Setup docs.  Enabled `enableHeadless: true` and registered the headless-task.  Everything works fine.

**Comment by IRIG** [comment]
> I've just generated a fresh new Flutter app, installed & setup the plugin according to the Setup docs. Enabled `enableHeadless: true` and registered the headless-task. Everything works fine.

After having made the mentioned change in the package name, everything works fine. Strange is, that I have this app running since four months and never noticed this exception before...

**Comment by christocracy** [comment]
>Did this exception have an impact on the proper running of your plugin?

No.  It was a recent change for detecting when app is headless (where the app's `MainActivity` no longer exists).  The plugin uses this information to determine where to fire its events, either to the standard flutter event handler (eg: `BackgroundGeolocation.onLocation` or to the registered headless-task.

The change added the ability for the plugin to properly detect the `MainActivity` activate when using android "product flavours" setup.

Where an app could have multiple flavours, such as `com.foo.bar.free`, `com.foo.bar.premium` where the `MainActivity` class-name still exists in the package `com.foo.bar` (ie: `com.foo.bar.MainActivity`)

**Comment by christocracy** [comment]
The change is at the top of the [CHANGELOG](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md#1101--2020-09-30) for `1.10.1`

>- [Fixed][Android] isMainActivityActive reported incorrect results for Android apps configured with "product flavors". This would cause the SDK to fail to recognize app is in "headless" state and fail to transmit headless events.

**Comment by IRIG** [comment]
That's good to know!

In fact, there were no complaints with the app that the background geo location would not work.

**Comment by christocracy** [comment]
I will let you close this issue.

**Comment by IRIG** [comment]
Thanks again for the fast and professional support!
