### ISSUE TITLE
incompatible types: PluginRegistry cannot be converted to FlutterEngine

### ISSUE THREAD

**Issue by WUKS87** [transistorsoft/flutter_background_geolocation#491]
## Flutter
* Plugin version: 1.10.3
* Platform: Android
* OS version: Any
* Device manufacturer / model: Any
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.52.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

* Plugin config:
```dart
bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 100.0,
      elasticityMultiplier: 5.0,
      enableHeadless: true,
      isMoving: true,
      stopOnTerminate: false,
      startOnBoot: true,
      debug: true,
      logLevel: bg.Config.LOG_LEVEL_VERBOSE
  ));
```
* Application.java:
```dart
package my_package_for_project;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

import com.transistorsoft.flutter.backgroundgeolocation.FLTBackgroundGeolocationPlugin;

public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        FLTBackgroundGeolocationPlugin.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}
```

AndroidManifest.xml
```dart
<application
        tools:replace="android:label"
        android:name=".Application"
        android:label="project_label"
        android:icon="@mipmap/ic_launcher">
```

## Expected Behavior
Flutter build should go through.

## Actual Behavior
Build can't pass.

## Steps to Reproduce
1. Build APK like this: flutter build apk --release
2. Build doesn't go through.

## Context
I created headlessTask:
```dart
void headlessTask(bg.HeadlessEvent headlessEvent) async {
  print('[BackgroundGeolocation HeadlessTask]: $headlessEvent');

  switch(headlessEvent.name) {
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      print('- Location: $location');

      saveLocation(location);

      break;
  }
}
```

## Debug logs
``` <!-- syntax-highligting:  DO NOT REMOVE -->
error: incompatible types: PluginRegistry cannot be converted to FlutterEngine
        GeneratedPluginRegistrant.registerWith(registry);
```

## Note:
I managed to make it pass with this modification:
```
GeneratedPluginRegistrant.registerWith((FlutterEngine) registry);
```
After successful release build app should not crash on real device.

## Expected Behavior - After build pass
Flutter build went through.

## Actual Behavior - After build pass
App crash on real device. Testing device: Samsung S9

## Debug logs - After build pass
```
Fatal Exception: java.lang.ClassCastException: io.flutter.embedding.engine.g.g.a cannot be cast to io.flutter.embedding.engine.a
       at com.load_market.Application.registerWith(Application.java)
       at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.startBackgroundIsolate(HeadlessTask.java:131)
       at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.dispatch(HeadlessTask.java:4)
       at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.run(HeadlessTask.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by christocracy** [comment]
Why did you add this to your `Application.java`?

```java
public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        FLTBackgroundGeolocationPlugin.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}
```

The [*Headless Mode Setup Guide*](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-Headless-Mode#step-1--which-flutter-sdk) tells you when using `flutter >= 1.12` there there **are no additional steps required -- everything is now automatic**.  **Skip to Step 3**.

![](https://dl.dropbox.com/s/ktzeb6na9ju6lm2/Screen%20Shot%202021-01-05%20at%2010.06.50%20AM.png?dl=1)

**Comment by WUKS87** [comment]
Uhhh, yeah, you are right @christocracy . I misunderstood it somehow.
Now app is not crashing anymore.
I will post here when I test headless task on real device.
Thank you!
