### ISSUE TITLE
E/TSLocationManager(20030):   ‼️  Failed to deduce Application's BuildConfig class for package abc.prod or abc.dev

### ISSUE THREAD

**Issue by bhanuka96** [transistorsoft/flutter_background_geolocation#492]
I attached my crash log. 

config

 ```
 void configure() async {
    bg.TransistorAuthorizationToken token = await bg.TransistorAuthorizationToken.findOrCreate(...);

    bg.BackgroundGeolocation.ready(bg.Config(
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 0.0,
            locationUpdateInterval: 1000,
            locationTimeout: 60,
            persistMode: 1,
            desiredOdometerAccuracy: 10,
            stationaryRadius: 25,
            foregroundService: true,
            disableMotionActivityUpdates: true,
            enableHeadless: false,
            stopOnTerminate: false,
            startOnBoot: true,
            disableStopDetection: true,
            pausesLocationUpdatesAutomatically: false,
            allowIdenticalLocations: true,
            useSignificantChangesOnly: false,
            transistorAuthorizationToken: token,
            debug: kDebugMode,
            logLevel: kReleaseMode ? bg.Config.LOG_LEVEL_OFF : bg.Config.LOG_LEVEL_VERBOSE,
            notificationPriority: kReleaseMode ? -2 : 1,
            showsBackgroundLocationIndicator: kDebugMode,
            locationAuthorizationRequest: 'Always',
            backgroundPermissionRationale: PermissionRationale(
               )))
        .then((bg.State state) {
      if (!state.enabled) {
        start();
      }
    });
  }
```

Logs

```
D/TSLocationManager(20030): [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 68.4
D/TSLocationManager(20030): [c.t.l.s.LocationRequestService b] SingleLocationRequest 1 isFinished? false
D/TSLocationManager(20030): [c.t.l.service.AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
E/TSLocationManager(20030): [c.t.locationmanager.util.a d] 
E/TSLocationManager(20030):   ‼️  Failed to deduce Application's BuildConfig class for package name:com.packageName or com.packageName
W/System.err(20030): java.lang.ClassNotFoundException: com.packageName.prod.BuildConfig
W/System.err(20030): 	at java.lang.Class.classForName(Native Method)
W/System.err(20030): 	at java.lang.Class.forName(Class.java:453)
W/System.err(20030): 	at java.lang.Class.forName(Class.java:378)
W/System.err(20030): 	at com.transistorsoft.locationmanager.util.a.d(Unknown Source:37)
W/System.err(20030): 	at com.transistorsoft.locationmanager.util.a.a(Unknown Source:11)
W/System.err(20030): 	at com.transistorsoft.locationmanager.util.a.b(Unknown Source:0)
W/System.err(20030): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.isMainActivityActive(Unknown Source:126)
W/System.err(20030): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation._onLocationChange(Unknown Source:0)
W/System.err(20030): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(20030): 	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
W/System.err(20030): 	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
W/System.err(20030): 	at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
W/System.err(20030): 	at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err(20030): 	at android.os.Looper.loop(Looper.java:164)
W/System.err(20030): 	at android.app.ActivityThread.main(ActivityThread.java:6942)
W/System.err(20030): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(20030): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
W/System.err(20030): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
W/System.err(20030): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.packageName.prod.BuildConfig" on path: DexPathList[[zip file "/data/app/com.packageName.prod-aoHK0u99ppA8Thx4PURXGg==/base.apk"],nativeLibraryDirectories=[/data/app/com.packageName.prod-aoHK0u99ppA8Thx4PURXGg==/lib/arm64, /data/app/com.orelgodriver.prod-aoHK0u99ppA8Thx4PURXGg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
W/System.err(20030): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
W/System.err(20030): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err(20030): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err(20030): 	... 18 more
D/TSLocationManager(20030): [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
V/MediaPlayerNative(20030): message received msg=6, ext1=0, ext2=0
V/MediaPlayerNative(20030): unrecognized message: (6, 0, 0)
V/MediaPlayerNative(20030): callback application
V/MediaPlayerNative(20030): back from callback
V/MediaPlayer-JNI(20030): getCurrentPosition: 0 (msec)
V/MediaPlayerNative(20030): message received msg=2, ext1=0, ext2=0
V/MediaPlayerNative(20030): playback complete
V/MediaPlayerNative(20030): callback application
V/MediaPlayerNative(20030): back from callback
V/MediaPlayer(20030): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(20030): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer-JNI(20030): release
V/MediaPlayerNative(20030): setListener
V/MediaPlayerNative(20030): disconnect
V/MediaPlayerNative(20030): destructor
V/MediaPlayerNative(20030): disconnect
```

**Comment by bhanuka96** [comment]
@christocracy Can you check this crash log?

**Comment by christocracy** [comment]
It's not a *crash*, it's a *caught exception* which happened to log a stacktrace.

Show me the following **three** files:
- `AndroidManifest.xml`
- `android/build.gradle`
- `android/app/build.gradle`

**Comment by christocracy** [comment]
Please [search the issues](https://github.com/transistorsoft/flutter_background_geolocation/issues?q=Failed+to+deduce) *before* posting a new one.

**Comment by christocracy** [comment]
Also, never ignore the issue template.

*****************************************************************
*
* WARNING:  DO NOT IGNORE THIS TEMPLATE
*
*****************************************************************



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by bhanuka96** [comment]
androidManifest.xml

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.name.dev">

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.CAMERA" />

    <application
        android:label="@string/app_name"
        android:resizeableActivity="false"
        android:requestLegacyExternalStorage="true"
        tools:replace="android:label"
        android:icon="@mipmap/ic_launcher">
        <service android:name="com.transistorsoft.locationmanager.service.TrackingService" android:foregroundServiceType="location" />
        <service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" android:foregroundServiceType="location" />
        <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="@string/bgApplicationKey"/>
        <meta-data
            android:name="com.google.firebase.ml.vision.DEPENDENCIES"
            android:value="ocr" />
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <meta-data android:name="com.google.android.geo.API_KEY"
            android:value="@string/google_maps_api_key"/>
        <!-- To use multiple models: android:value="ocr,label,barcode,face" -->
        <activity
            android:name="com.name.dev.MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background" />
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme"
                />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
    </application>
</manifest>

```



> Please [search the issues](https://github.com/transistorsoft/flutter_background_geolocation/issues?q=Failed+to+deduce) _before_ posting a new one.
