### ISSUE TITLE
[Android] Third-party dependencies throw MissingPluginException when the app is terminated in headless task

### ISSUE THREAD

**Issue by efraespada** [transistorsoft/flutter_background_geolocation#498]
## Your Environment
* Plugin version: 1.10.3
* Platform: Android (using `flutterEmbedding v2`)
* OS version: Any
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
[✓] Connected device (5 available)
```
* Plugin config:
```dart 
bg.Config(
              locationAuthorizationRequest: authRequest,
              enableHeadless: true,
              notification: bg.Notification(
                  title: Constants.name,
                  text: AppLocalizations.of(context)
                      .translate(Res.geo_task_subtitle),
                  smallIcon: "drawable/ic_notification_launcher"),
              desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
              backgroundPermissionRationale: bg.PermissionRationale(
                  title: AppLocalizations.of(context)
                      .translate(Res.geo_permission_rationale_title),
                  message: AppLocalizations.of(context)
                      .translate(Res.geo_permission_rationale_message),
                  positiveAction: AppLocalizations.of(context)
                      .translate(Res.geo_permission_rationale_change_button),
                  negativeAction: AppLocalizations.of(context)
                      .translate(Res.geo_permission_rationale_change_cancel)),
              distanceFilter: 0,
              locationUpdateInterval: 5,
              isMoving: true,
              foregroundService: true,
              stopOnTerminate: false,
              startOnBoot: true)
```

## Expected Behavior
Headless task (with third-party plugins) working even the app is terminated (As a month ago).

## Actual Behavior
Third-party dependencies throw a MissingPluginException when the app is terminated. It is really strange because there is no significant change in the Android configuration (`Application.kt`, `MainActivity.kt`, `build.gradle` files..) since months ago (when everything worked fine), and now any extra dependency throws that exception (Firebase, Sqlite..).

## Steps to Reproduce
1. Run the app with the given configuration.
2. Run any application to mock the location (Lockito - Fake GPS in my case)
3. The background location process can send the location to a Firebase server, search for local info (Sqlite), etc...
4. Kill the app. The headless task starts working (the notification appears too).
5. Then, no plugin works in the headless task. 

## Context
When the background location is running, I store the location in a Firebase server. I do some other checks with Sqlite.

## Debug logs
``` 
I/flutter (11749): UPDATING LOCATION location 40.515230183123656, -3.6714343495834023
E/flutter (11749): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
E/flutter (11749): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (11749): <asynchronous suspension>
E/flutter (11749): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (11749): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345:41)
E/flutter (11749): #3      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:30:36)
E/flutter (11749): #4      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:75:13)
E/flutter (11749): #5      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:25)
E/flutter (11749): #6      processPosition (package:landa/background/tracking/geolocation.dart:229:18)
E/flutter (11749): #7      headlessTask (package:landa/background/tracking/geolocation.dart:49:7)
E/flutter (11749): #8      _headlessCallbackDispatcher.<anonymous closure> (package:flutter_background_geolocation/models/background_geolocation.dart:1665:15)
E/flutter (11749): #9      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:430:55)
E/flutter (11749): #10     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:383:34)
E/flutter (11749): #11     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:283:33)
E/flutter (11749): #12     _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
E/flutter (11749): #13     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (11749): #14     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (11749): #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (11749): #16     _invoke3 (dart:ui/hooks.dart:279:10)
E/flutter (11749): #17     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)
```

**Comment by christocracy** [comment]
Show me your `main.dart` where you headless code is running.

**Comment by efraespada** [comment]
My `main.dart` where I define the headless task:
```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
  Admob.initialize();
  if (Platform.isAndroid) {
    await bg.BackgroundGeolocation.registerHeadlessTask(headlessTask);
  }
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  
  MyApp() {
    if (kDebugMode) {
      FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(false);
    }
  }

  @override
  MyAppState createState() => MyAppState();

}
```

I start the background geolocation on my splash screen.

How I start the background geolocation:
```dart
// geolocation.dart

const String whenInUse = "WhenInUse";
const String always = "Always";
const String any = "Any";

void headlessTask(bg.HeadlessEvent headlessEvent) async {
  switch (headlessEvent.name) {
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      print('- Location process: $location');
      processPosition(location);
      break;
    case bg.Event.POWERSAVECHANGE:
      bool enabled = headlessEvent.event;
      print('ProviderChangeEvent: $enabled');
      break;
    case bg.Event.CONNECTIVITYCHANGE:
      bg.ConnectivityChangeEvent event = headlessEvent.event;
      print('ConnectivityChangeEvent: $event');
      break;
    case bg.Event.ENABLEDCHANGE:
      bool enabled = headlessEvent.event;
      print('EnabledChangeEvent: $enabled');
      break;
  }
}

Future<void> processPosition(bg.Location _position) async {
  if (_position == null) {
    print("NULL location");
    return;
  }

  print("UPDATING LOCATION location ${_position.coords.latitude}, ${_position.coords.longitude}");

  await Firebase.initializeApp(); // <-- crash

  // more stuff with 3rd-party libraries..
}

class Geo {

  static Future<void> startGeolocation(BuildContext context) async {
    if (!geoLocationRunning) {
      geoLocationRunning = true;

      bg.BackgroundGeolocation.onLocation((bg.Location location) {
        processPosition(location);
      }, (bg.LocationError error) {
        print(error);
      });

      var authRequest;
      if (Platform.isAndroid) {
        authRequest = always;
      } else if (Platform.isIOS) {
        authRequest = whenInUse;
      } else {
        authRequest = any;
      }

      await bg.BackgroundGeolocation.ready(bg.Config(
              locationAuthorizationRequest: authRequest,
              enableHeadless: true,
              notification: bg.Notification(
                  title: Constants.name,
                  text: AppLocalizations.of(context)
                      .translate(Res.geo_task_subtitle),
                  smallIcon: "drawable/ic_notification_launcher"),
              desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
              backgroundPermissionRationale: bg.PermissionRationale(
                  title: AppLocalizations.of(context)
                      .translate(Res.geo_permission_rationale_title),
                  message: AppLocalizations.of(context)
                      .translate(Res.geo_permission_rationale_message),
                  positiveAction: AppLocalizations.of(context)
                      .translate(Res.geo_permission_rationale_change_button),
                  negativeAction: AppLocalizations.of(context)
                      .translate(Res.geo_permission_rationale_change_cancel)),
              distanceFilter: 0,
              locationUpdateInterval: 5,
              isMoving: true,
              foregroundService: true,
              stopOnTerminate: false,
              startOnBoot: true))
          .then((bg.State state) async {
        if (!state.enabled) {
          await bg.BackgroundGeolocation.start();
          if (Platform.isIOS) {
            await Future.delayed(Duration(seconds: 8));
            await bg.BackgroundGeolocation.setConfig(
                bg.Config(locationAuthorizationRequest: always));
          }
        }
      });
    }
  }
  
  static Future<void> stopGeolocation() async {
    if (geoLocationRunning) {
      geoLocationRunning = false;
      await bg.BackgroundGeolocation.stop();
    }
  }
}
```

Then, from my splash screen:
```dart
await Geo.startGeolocation(view.getContext());
```

**Comment by christocracy** [comment]
Have you tried seeking support with your Firebase plugins' repo?

**Comment by efraespada** [comment]
In the beginning, I thought it was a problem with the Firebase plugins, but the problem happens with any plugin I used. When I comment this line
```dart
await Firebase.initializeApp();
```
the `MissingPluginException` happens again with the next 3rd-party plugin used (Sqlite).
```
I/flutter (30440): location: 40.422341930262355 -3.704984199783785
E/flutter (30440): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
E/flutter (30440): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (30440): <asynchronous suspension>
E/flutter (30440): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (30440): #2      invokeMethod (package:sqflite/src/sqflite_impl.dart:17:13)
E/flutter (30440): #3      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:82:7)
E/flutter (30440): #4      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:41:35)
E/flutter (30440): #5      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:32)
E/flutter (30440): #6      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
E/flutter (30440): #7      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite_common/src/factory_mixin.dart:41:7)
E/flutter (30440): #8      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:169:26)
E/flutter (30440): #9      getDatabasesPath (package:sqflite/sqflite.dart:161:54)
E/flutter (30440): #10     Data.database (package:landa/data/data.dart:14:18)
E/flutter (30440): #11     Local.getLoggedUser (package:landa/data/users_repository.dart:129:36)
E/flutter (30440): #12     updateLocation (package:landa/background/tracking/geolocation.dart:269:49)
E/flutter (30440): #13     processPosition (package:landa/background/tracking/geolocation.dart:232:3)
E/flutter (30440): <asynchronous suspension>
E/flutter (30440): #14     headlessTask (package:landa/background/tracking/geolocation.dart:49:7)
E/flutter (30440): #15     _headlessCallbackDispatcher.<anonymous closure> (package:flutter_background_geolocation/models/background_geolocation.dart:1665:15)
E/flutter (30440): #16     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:430:55)
E/flutter (30440): #17     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:383:34)
E/flutter (30440): #18     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:283:33)
E/flutter (30440): #19     _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
E/flutter (30440): #20     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (30440): #21     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (30440): #22     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (30440): #23     _invoke3 (dart:ui/hooks.dart:279:10)
E/flutter (30440): #24     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)
```
That turns the headless task completely unusable.

**Comment by efraespada** [comment]
I'm gonna review the dependencies versions.

**Comment by efraespada** [comment]
After too many tests I confirm some 3rd-party dependencies break the headless task. Specifically:
- `aeyrium_sensor`: Makes the `MissingPluginException` of `firebase_core`
- `gallery_saver`: Makes the `MissingPluginException` of `sqflite`

There is no problem in the headless task when those dependencies are removed from the `pubspec.yaml`.
