### ISSUE TITLE
flutter_background_geolocation_helloworld.dart crash

### ISSUE THREAD

**Issue by gkrawiec** [transistorsoft/flutter_background_geolocation#50]
## Your Environment
* Plugin version: **1.0.0**
* Platform: **Android**
* OS version: **MacOS 10.14.4**
* Device manufacturer / model: **Pixel XL with Android v9 April 5, 2019 patch**
* Flutter info (`flutter doctor`): 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.4 18E226, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    ✗ libimobiledevice and ideviceinstaller are not installed. 
    ✗ ios-deploy not installed. 
    ✗ CocoaPods not installed.
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.33.0)
[✓] Connected device (1 available)
```
* Plugin config

## Expected Behavior
code from "Full Example" as of today April 5
*flutter_background_geolocation_helloworld.dart*
https://gist.github.com/christocracy/a0464846de8a9c27c7e9de5616082878

should run by simply adding the
  `flutter_background_geolocation: '^1.0.0'`
dependency to pubscpec.yaml and making a couple of changes to avoid the 
AndroidManifest to avoid the `android:label` build error
but it does not.

## Actual Behavior
App crashes when starting the Debug session. All the debug console shows is
```
Launching lib/main.dart on Pixel XL in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
```
when ran using 
`Flutter run -verbose`
the log stops at
```
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.bg_location_test/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
```
and just stays there. Need to ctrl-c to get out.

If I look at the logcat there is a section describing the crash, this section of the log is included further down in the Debug Logs section

## Steps to Reproduce

1. Create new flutter project
2. Replace *main.dart* with code from *flutter_background_geolocation_helloworld.dart*
3. Add `flutter_background_geolocation: '^1.0.0'`to *pubspec.yaml* `dependencies:`
4. Fix *android/app/src/main/AndroidManifest.xml* according to *INSTALL-ANDROID.md*
5. Start with Debug

## Context
I should note, the example included in the cloned git repo works fine. This problem is in the helloworld app 

## Debug logs
```
beginning of crash
04-05 20:21:00.346 22372 22372 E AndroidRuntime: FATAL EXCEPTION: main
04-05 20:21:00.346 22372 22372 E AndroidRuntime: Process: com.example.bg_location_test, PID: 22372
04-05 20:21:00.346 22372 22372 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.transistorsoft.locationmanager.util.LogFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.transistorsoft.locationmanager.util.LogFileProvider" on path: DexPathList[[zip file "/data/app/com.example.bg_location_test-8IGXETpHwNsMRZwZ4tfFEA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.bg_location_test-8IGXETpHwNsMRZwZ4tfFEA==/lib/arm64, /data/app/com.example.bg_location_test-8IGXETpHwNsMRZwZ4tfFEA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at android.app.ActivityThread.installProvider(ActivityThread.java:6445)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at android.app.ActivityThread.installContentProviders(ActivityThread.java:5987)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5902)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at android.app.ActivityThread.access$1100(ActivityThread.java:200)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at android.os.Looper.loop(Looper.java:193)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6718)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.transistorsoft.locationmanager.util.LogFileProvider" on path: DexPathList[[zip file "/data/app/com.example.bg_location_test-8IGXETpHwNsMRZwZ4tfFEA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.bg_location_test-8IGXETpHwNsMRZwZ4tfFEA==/lib/arm64, /data/app/com.example.bg_location_test-8IGXETpHwNsMRZwZ4tfFEA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:62)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at android.app.ActivityThread.installProvider(ActivityThread.java:6429)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: ... 10 more
04-05 20:21:00.346 22372 22372 E AndroidRuntime: Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/FileProvider;
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at java.lang.VMClassLoader.findLoadedClass(Native Method)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: ... 14 more
04-05 20:21:00.346 22372 22372 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.example.bg_location_test-8IGXETpHwNsMRZwZ4tfFEA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.bg_location_test-8IGXETpHwNsMRZwZ4tfFEA==/lib/arm64, /data/app/com.example.bg_location_test-8IGXETpHwNsMRZwZ4tfFEA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-05 20:21:00.346 22372 22372 E AndroidRuntime: ... 17 more
04-05 20:21:00.352   903  2747 W ActivityManager:   Force finishing activity com.example.bg_location_test/.MainActivity
04-05 20:21:00.360 22372 22372 I Process : Sending signal. PID: 22372 SIG: 9
```

**Comment by christocracy** [comment]
I see the problem.  I thought that Flutter had updated their application template to use AndroidX.  This seems not to be the case.

1.  `android/gradle.properties`
```diff
+ android.enableJetifier=true
+ android.useAndroidX=true
```

2.  `android/build.gradle`
```diff
buildscript {
+    ext {
+       compileSdkVersion   = 28
+        targetSdkVersion    = 28
+        supportLibVersion   = "1.0.2"
+        playServicesLocationVersion = "16.0.0"
+        removeBackgroundGeolocationDebugSoundsInRelase = true
+    }
```

3.  `android/app/build.gradle`
```diff
dependencies {
     testImplementation 'junit:junit:4.12'
-    androidTestImplementation 'com.android.support.test:runner:1.0.2'
-    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
+   androidTestImplementation 'androidx.test:runner:1.1.1'
+   androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
+   implementation "androidx.appcompat:appcompat:$supportLibVersion"

}
```

**Comment by gkrawiec** [comment]
These changes fixed it. Thank you!

**Comment by christocracy** [comment]
Also see [AndroidX Compatibility](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility)

```diff
buildscript {
   ...
    dependencies {
+        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}
```

**Comment by christocracy** [comment]
Also relevant https://github.com/flutter/flutter/issues/27792
