### ISSUE TITLE
Example app does not work on iOS in nullsafety branch

### ISSUE THREAD

**Issue by hlavki** [transistorsoft/flutter_background_geolocation#534]
## Your Environment
* Plugin version: 4.0.0-nullsafety.0
* Platform: iOS
* OS version: 14.4
* Device manufacturer / model: iOS Simulator
* Flutter info (`flutter doctor`):

    ```
    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [✓]** Xcode - develop for iOS and macOS
    [✓] Chrome - develop for the web
    [✓] Android Studio (version 4.1)
    [✓] Connected device (2 available)
    
    • No issues found!
    ```

## Expected Behavior
working example application

## Actual Behavior
Application fails

## Steps to Reproduce
1. Run example application from branch nullsafety on iOS

## Context
Migrate my application to flutter 2.0

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Running "flutter pub get" in example...
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Upgrading contents.xcworkspacedata
Running pod install...
Running Xcode build...
Xcode build done.                                           48.4s
[TSBackgroundFetch load]: (
)
[TSBGAppRefreshSubscriber load]: {
}
[TSBackgroundFetch registerForTaskWithIdentifier: com.transistorsoft.customtask
Debug service listening on ws://127.0.0.1:57751/5GhgnBU6C7Q=/ws
Syncing files to device iPhone 12 Pro Max...
[TSBackgroundFetch removeListener] WARNING:  Failed to find listener for identifier: TSLocationManager
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'FutureOr<Map<dynamic, dynamic>>' in type cast
#0      DeviceInfo.getInstance (package:flutter_background_geolocation/models/device_info.dart:35:11)
#1      _HomeViewState._initPlatformState (package:flutter_background_geolocation_example/app.dart:78:39)
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'FutureOr<Map<dynamic, dynamic>>' in type cast
#0      DeviceInfo.getInstance (package:flutter_background_geolocation/models/device_info.dart:35:11)
#1      _RegistrationViewState._initPlatformState (package:flutter_background_geolocation_example/registration_view.dart:45:19)
<asynchronous suspension>
```

</details>

**Comment by christocracy** [comment]
The /example app *cannot* work because it has dependencies on plugin's not yet migrated to nullsafety, eg: `flutter_map: ^0.12.0`.

I suggest you generate yourself a fresh new *hello world* app.

**Comment by hlavki** [comment]
Ok, thanks
