### ISSUE TITLE
Papertrail Class Cast Exception

### ISSUE THREAD

**Issue by tonespy** [transistorsoft/flutter_background_geolocation#565]
## Your Environment
* Plugin version: ^1.11.1
* Platform: Android
* OS version: 11
* Device manufacturer / model: Google Pixel 4
* Flutter info (`flutter doctor`):
```
[✓] Flutter (Channel master, 1.27.0-9.0.pre.1, on macOS 11.0.1 20B29 darwin-x64, locale en-NG)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (3 available)

```
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
Config(
        locationAuthorizationRequest: 'Always',
        geofenceModeHighAccuracy: true,
        desiredOdometerAccuracy: 10,
        //allowIdenticalLocations: false,
        desiredAccuracy: (Platform.isAndroid) ? Config.DESIRED_ACCURACY_HIGH : Config.DESIRED_ACCURACY_NAVIGATION,
        stopOnTerminate: false,
        startOnBoot: true,
        pausesLocationUpdatesAutomatically: false,
        preventSuspend: true,
        enableHeadless: true,
        foregroundService: true,
        stopOnStationary: false,
        locationUpdateInterval: fastestLocationUpdateInterval == 0 ? 2000 : fastestLocationUpdateInterval, // Consider
        heartbeatInterval: 60, // <-- every minute, this will prevent the app from going into suspension mode on iOS
        distanceFilter: distanceFilter < 0.1 ? 5.0 : distanceFilter.toDouble(),
        fastestLocationUpdateInterval: fastestLocationUpdateInterval == 0 ? 2000 : fastestLocationUpdateInterval, // Consider
        geofenceInitialTriggerEntry: true,
        logLevel: Config.LOG_LEVEL_VERBOSE,
        logMaxDays: 5,
        notification: Notification(
          smallIcon: 'drawable/icon',
        ),
        backgroundPermissionRationale: PermissionRationale(
            title:
                'Title',
            message:
                'Message',
            positiveAction: 'Yes, Allow.',
            negativeAction: 'Not'),),)
```

* Gradle Config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
dependencies {
    ...
    implementation 'org.slf4j:slf4j-api:1.7.27'
    implementation 'com.github.tony19:logback-android:2.0.0'
    implementation ('com.papertrailapp:logback-syslog4j:1.0.0') {
        exclude group: 'ch.qos.logback'
    }
}
```

## Expected Behavior

Run without crashing

## Actual Behavior

Crash immediately at launch

## Steps to Reproduce

1. Add papertrail to Android gradle pluggin
2. Add this line to any file `var LOG = LoggerFactory.getLogger(MainActivity::class.java)`
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
E/AndroidRuntime: FATAL EXCEPTION: pool-8-thread-1
    Process: com.appname, PID: 18627
    java.lang.ExceptionInInitializerError
        at com.transistorsoft.locationmanager.logger.TSLog.setLogLevel(Unknown Source:0)
        at com.transistorsoft.locationmanager.adapter.TSConfig.load(Unknown Source:294)
        at com.transistorsoft.locationmanager.adapter.TSConfig.<init>(Unknown Source:59)
        at com.transistorsoft.locationmanager.adapter.TSConfig.a(Unknown Source:9)
        at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance(Unknown Source:14)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:163)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.b(Unknown Source:9)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:10)
        at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule$1.run(BackgroundGeolocationModule.java:145)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ClassCastException: org.slf4j.helpers.SubstituteLogger cannot be cast to ch.qos.logback.classic.Logger
        at com.transistorsoft.locationmanager.logger.TSLog.getRootLogger(Unknown Source:11)
        at com.transistorsoft.locationmanager.logger.TSLog.initialize(Unknown Source:0)
        at com.transistorsoft.locationmanager.logger.TSLog.<clinit>(Unknown Source:339)
        at com.transistorsoft.locationmanager.logger.TSLog.setLogLevel(Unknown Source:0) 
        at com.transistorsoft.locationmanager.adapter.TSConfig.load(Unknown Source:294) 
        at com.transistorsoft.locationmanager.adapter.TSConfig.<init>(Unknown Source:59) 
        at com.transistorsoft.locationmanager.adapter.TSConfig.a(Unknown Source:9) 
        at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance(Unknown Source:14) 
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:163) 
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.b(Unknown Source:9) 
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:10) 
        at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule$1.run(BackgroundGeolocationModule.java:145) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923)
```

</details>

**Comment by christocracy** [comment]
I think I know the cause.  Fix will be applied to next release.

**Comment by christocracy** [comment]
>Plugin version: ^1.11.1

I don't think you're using v1.11.1.  You must be using at least `2.x`

**Comment by tonespy** [comment]
> I think I know the cause. Fix will be applied to next release.

Next release? When is that? @christocracy

**Comment by tonespy** [comment]
> > Plugin version: ^1.11.1
> 
> I don't think you're using v1.11.1. You must be using at least `2.x`

Well, the pubspec.lock says `1.11.1` I am updating to `^2.0.5` to check if there's any change

**Comment by christocracy** [comment]
Are you aware that this plugin [*also* imports `logback-android`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/android/build.gradle#L64-L65)?

**Comment by christocracy** [comment]
>I think I know the cause. Fix will be applied to next release.

I was wrong.  If you're using `1.11.1`, the problem is not what I thought it was.

**Comment by tonespy** [comment]
> Are you aware that this plugin [_also_ imports `logback-android`](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/android/build.gradle#L64-L65)?

Yeah. That's the cause of the error in the first place.

**Comment by tonespy** [comment]
Well, @christocracy I updated to 2.0.5, and iOS is working fine, Android only works if I do not do this:
```
var LOG = LoggerFactory.getLogger(MainActivity::class.java)
```

**Comment by christocracy** [comment]
As I said, my plugin too is using `logback-Android` is this "papertrail" is.  

There's obviously a conflict in both libraries using logback that I'm not aware of.
