### ISSUE TITLE
LateInitializationError: Field 'event' has not been initialized.

### ISSUE THREAD

**Issue by christinachimi** [transistorsoft/flutter_background_geolocation#682]
## Your Environment
* Plugin version: 4.3.2
* Platform: Android
* OS version: Emulator, so far Pixel 3 API 29
* Device manufacturer / model: Pixel 3 emulator
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 12.2)
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.1)
[✓] Connected device (2 available)
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
          notification: bg.Notification(
            title:  'placeholder text'
            text:  'placeholder text',
            sticky: true,
            layout: 'workday_notification_layout',
            smallIcon: 'mipmap/ic_notification',
            // <-- defaults to app icon
            largeIcon: 'mipmap/ic_notification',
          ),
          locationAuthorizationRequest: 'always',
          disableLocationAuthorizationAlert: true,
          backgroundPermissionRationale: bg.PermissionRationale(
              title: 'placeholder text',
              message:  'placeholder text',
              positiveAction: 'placeholder text'
              negativeAction: 'placeholder text',
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10.0,
          stopOnTerminate: false,
          preventSuspend: true,
          heartbeatInterval: 60,
          startOnBoot: true,
          foregroundService: true,
          logLevel: bg.Config.LOG_LEVEL_ERROR,
          persistMode: bg.Config.PERSIST_MODE_NONE,
        )
```

## Expected Behavior
We have some code like this:

```dart
  void _onLocation(bg.Location location) async {
    if (!location.sample!) {
      _location = location;
      await sendCoordinates(reason: location.event ?? 'heartbeat');
    }
  }
```

Which would send the coordinates (we are not currently using the plugin's sync capability) along with the event.

## Actual Behavior
We are in the middle of migrating to Flutter 2 and updating our plugins. The change needed to that code is to remove ` ?? 'heartbeat'`. I am seeing a `[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field 'event' has not been initialized.` It seems like heartbeat events have `params['event']` but other events don't. Because `event` is marked late I can only work around this by try/catching `location.event` (it won't return null, it will just throw that error). Can the fields that are marked late in `bg.Location` but are only set if the params envelope contains them be marked nullable so I can do `location.event ?? 'unknown' (or, even better, a reasonable value be applied to `event` when `params['event']` is null)?

## Steps to Reproduce
1. See code above.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
E/flutter ( 7528): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field 'event' has not been initialized.
E/flutter ( 7528): #0      Location.event (package:flutter_background_geolocation/models/location.dart)
package:flutter_background_geolocation/models/location.dart:1
E/flutter ( 7528): #1      TransistorsoftProvider._onLocation
package:gopuff_godrive_v2/…/providers/transistorsoft.dart:114
E/flutter ( 7528): #2      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 7528): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 7528): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 7528): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 7528): #6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 7528): #7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 7528): #8      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter ( 7528): #9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 7528): #10     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 7528): #11     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 7528): #12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 7528): #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 7528): #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 7528): #15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 7528): #16     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
E/flutter ( 7528): #17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 7528): #18     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 7528): #19     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 7528): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 7528): #21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 7528): #22     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter ( 7528): #23     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter ( 7528): #24     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter ( 7528): #25     _rootRun (dart:async/zone.dart:1420:47)
E/flutter ( 7528): #26     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 7528): #27     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 7528): #28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 7528): #29     _rootRun (dart:async/zone.dart:1428:13)
E/flutter ( 7528): #30     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 7528): #31     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 7528): #32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 7528): #33     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 7528): #34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

</details>

**Comment by christinachimi** [comment]
Just following up here - is this something that will be addressed? We are assuming "heartbeat" in these cases but would prefer to avoid the case.

**Comment by christocracy** [comment]
When there is no value for `Location.event`, it will be initialized to empty-string `""`.

Try testing branch `release-4.3.3`

```yaml
dependencies:
  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
      ref: release-4.3.3
```

**Comment by christinachimi** [comment]
This does avoid the error, which is great. On the emulator I only get events with empty string, but I'll try to build it onto a real device soon and double-check.

**Comment by christocracy** [comment]
You can get a motionchange event in sim
