### ISSUE TITLE
App is crashing due to RuntimeException

### ISSUE THREAD

**Issue by pawlowskim** [transistorsoft/flutter_background_geolocation#697]
## Your Environment
* Plugin version: 4.0.2
* Platform: Android
* OS version: So far on Android 10 and 11
* Device manufacturer / model: So far LG LM-K420 K31 K51, and Nokia 2.3 and motorola moto g pure
* Flutter info (`flutter doctor`):  Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-GB) (but app installed from play store)
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 10.0,
      disableLocationAuthorizationAlert: true,
      disableElasticity: true,
      disableStopDetection: true,
      stopOnTerminate: false,
      startOnBoot: true,
      preventSuspend: true,
      stopOnStationary: false,
      pausesLocationUpdatesAutomatically: false,
      heartbeatInterval: 60,
      debug: false,
      reset: true,
      foregroundService: true,
      notification: bg.Notification(
          sticky: true,
          text: "xxx",
          title: "xxx",
          channelName: "xxx",
          layout: 'notification_layout',
          color: "#${AppColor.main.value.toRadixString(16).padLeft(8, '0')}",
          largeIcon: "mipmap/ic_launcher",
          smallIcon: "mipmap/ic_launcher_notification"
          // strings: {'myCustomElement': 'custom TextBox element'}
          )));
```

## Expected Behavior
App shouldn't crash unexpectedly.

## Actual Behavior
App crashes

## Steps to Reproduce
We don't have steps to reproduce this behaviour yet, it happens on production. Most likely just after app is started, because we don't have any additional information from crashlytics.

## Context
Run the app I guess, it happen for end users, not during development.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Fatal Exception: java.lang.RuntimeException: Unable to start service com.transistorsoft.locationmanager.service.TrackingService@80a58b8 with Intent { cmp=app.aglet.mobile/com.transistorsoft.locationmanager.service.TrackingService (has extras) }: java.lang.RuntimeException: Could not copy bitmap to parcel blob.
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4404)
       at android.app.ActivityThread.access$1800(ActivityThread.java:244)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1958)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7868)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

Caused by java.lang.RuntimeException: Could not copy bitmap to parcel blob.
       at android.graphics.Bitmap.nativeWriteToParcel(Bitmap.java)
       at android.graphics.Bitmap.writeToParcel(Bitmap.java:2135)
       at android.graphics.drawable.Icon.writeToParcel(Icon.java:889)
       at android.app.Notification.writeToParcelImpl(Notification.java:2752)
       at android.app.Notification.writeToParcel(Notification.java:2687)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7022)
       at android.app.Service.startForeground(Service.java:709)
       at com.transistorsoft.locationmanager.service.AbstractService.e(AbstractService.java:22)
       at com.transistorsoft.locationmanager.service.AbstractService.a(AbstractService.java:8)
       at com.transistorsoft.locationmanager.service.TrackingService.onStartCommand(TrackingService.java:1)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4386)
       at android.app.ActivityThread.access$1800(ActivityThread.java:244)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1958)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7868)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
```

</details>

**Comment by christocracy** [comment]
You seem to have a problem with your Config.notification.

**Comment by pawlowskim** [comment]
Could it be problem on both sides? I mean configuration (+ assets potentially) and library itself? If it would be in configuration only it should crash for each users on any device, isn't it? We can try to deep dive into problem if we get appropriate devices but for me it seems that there are missing some sanity checks in library.

**Comment by christocracy** [comment]
> it seems that there are missing some sanity checks in library.

It could be.  You are using a rather complex `notification` config.

```
layout: 'notification_layout',
color: "#${AppColor.main.value.toRadixString(16).padLeft(8, '0')}",
largeIcon: "mipmap/ic_launcher",
smallIcon: "mipmap/ic_launcher_notification"
```

Can you provide me a simple *HelloWorld* app with an identical notification setup?  I have a number of devices I can test upon:

- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 12
- Samsung Galaxy S20 FE @ 11.0.0
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 10.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

**Comment by pawlowskim** [comment]
You can try to play around with this app https://github.com/pawlowskim/flutter_bg_location_sample
It displays custom icons, but I'm not sure if this would trigger the error, since main application is much more complicated that this...

Tap on start tracking should start the location services and display custom notification.

Thanks in advance.

**Comment by pawlowskim** [comment]
Could you provide any hints related to the code that caused the crash (since source is not available)? So we can try to simulate some behaviours to try to reproduce it?
