### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by atul-srvnsh** [transistorsoft/flutter_background_geolocation#720]
## Your Environment
* Plugin version: 1.9.0
* Platform: Android
* OS version: 6.0
* Device manufacturer / model:
* Flutter info (`flutter doctor`): 2.2.2
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior
As debug build is working fine release build should also work on device. 

## Actual Behavior
Release build is freezes on Splash Screen

## Steps to Reproduce

1.
2.
3.
4.

## Context

Trying to run release build before uploading it to play store
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
[+1365 ms] E/AndroidRuntime(17019): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(17019): Process: com.eatura.driver, PID: 17019
[        ] E/AndroidRuntime(17019): java.lang.ExceptionInInitializerError
[        ] E/AndroidRuntime(17019):     at b7.a.Y()
[        ] E/AndroidRuntime(17019):     at com.transistorsoft.locationmanager.BootReceiver.onReceive()
[        ] E/AndroidRuntime(17019):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2914)
[        ] E/AndroidRuntime(17019):     at android.app.ActivityThread.-wrap14(ActivityThread.java)
[        ] E/AndroidRuntime(17019):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1569)
[        ] E/AndroidRuntime(17019):     at android.os.Handler.dispatchMessage(Handler.java:111)
[        ] E/AndroidRuntime(17019):     at android.os.Looper.loop(Looper.java:207)
[        ] E/AndroidRuntime(17019):     at android.app.ActivityThread.main(ActivityThread.java:5737)
[        ] E/AndroidRuntime(17019):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(17019):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
[        ] E/AndroidRuntime(17019):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
[        ] E/AndroidRuntime(17019): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a
null object reference
```

</details>

**Comment by christocracy** [comment]
post your `android/app/build.gradle`

**Comment by atul-srvnsh** [comment]
Hi, Please suggest

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'
Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "***********"
        minSdkVersion 19
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        configurations.all {
            resolutionStrategy { force 'androidx.core:core:1.6.0' }
        }
    }

    signingConfigs {
        release {
            keyAlias '*****'
            keyPassword '************'
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword '********'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
        debug{

        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "androidx.multidex:multidex:2.0.1"
    implementation "androidx.appcompat:appcompat:${rootProject.ext.appCompatVersion}"
}

**Comment by christocracy** [comment]
Why have you omitted part of the [Setup Instructions](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md#androidappbuildgradle)?

![](https://dl.dropbox.com/s/1n1pairhqyb1juh/Screen%20Shot%202022-03-14%20at%209.24.18%20AM.png?dl=1)

Also, I see you have imported `multidex` but [not fully configured it](https://developer.android.com/studio/build/multidex)

![](https://www.dropbox.com/s/6onm2838rgtxwfh/Screen%20Shot%202022-03-14%20at%209.27.55%20AM.png?dl=1)

**Comment by atul-srvnsh** [comment]
Thanks for the explanation. It is working now
