### ISSUE TITLE
Hide/ Reduce IOS notificaiton.

### ISSUE THREAD

**Issue by jigarfumakiya** [transistorsoft/flutter_background_geolocation#721]
## Your Environment
* Plugin version:4.3.4
* Platform: iOS 
* OS version:IOS 15
* Device manufacturer / model: IOS / Simulator
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
 bg.BackgroundGeolocation.ready(
      bg.Config(
          reset: false,
          // <-- lets the Settings screen drive the config rather than re-applying each boot.
          // Convenience option to automatically configure the SDK to post to Transistor Demo server.
          transistorAuthorizationToken: token,
          // Logging & Debug
          debug: false,
          disableLocationAuthorizationAlert: false,
          logLevel: bg.Config.LOG_LEVEL_VERBOSE,

          // notification options
          foregroundService: true,
          stopOnStationary: true,
          notification: bg.Notification(
              priority: bg.Config.NOTIFICATION_PRIORITY_DEFAULT),

          // Geolocation options
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
          distanceFilter: 10.0,
          // Activity recognition options
          // locationUpdateInterval:5000,

          stopTimeout: 5,
          locationAuthorizationAlert: {
            'titleWhenNotEnabled': 'Yo, location-services not enabled',
            'titleWhenOff': 'Yo, location-services OFF',
            'instructions':
                'You must enable \'Always\' in location-services, buddy',
            'cancelButton': 'Cancel',
            'settingsButton': 'Settings'
          },
          backgroundPermissionRationale: bg.PermissionRationale(
              title:
                  "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
              message:
                  "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
              positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
              negativeAction: 'Cancel'),

          // HTTP & Persistence
          autoSync: true,
          // Application options
          stopOnTerminate: false,
          startOnBoot: true,
          enableHeadless: true,
          heartbeatInterval: 60),
    ).then((bg.State state) async {
      print('[ready] ${state.toMap()}');
      print('[didDeviceReboot] ${state.didDeviceReboot}');

      // if (state.schedule!.isNotEmpty) {
      //   bg.BackgroundGeolocation.startSchedule();
      // }
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });
    
   ```
```dart
  Future<bool> startBackgroundLocation() async {
    bg.BackgroundGeolocation.playSound(
        GeoFencingUtils.getSoundId("BUTTON_CLICK"));
    final state = await bg.BackgroundGeolocation.start();
    if (state.enabled) {
      
      return true;
    }
    return false;
  }
```

```dart
  Future<bool> stopBackgroundLocation() async {
    await bg.BackgroundGeolocation.changePace(false);
    final state = await bg.BackgroundGeolocation.stop();

    bg.BackgroundGeolocation.removeListener(() {});
    if (!state.enabled) {
      bg.BackgroundGeolocation.playSound(GeoFencingUtils.getSoundId("CLOSE"));

      return true;
    }
    return false;
  }
```

## Expected Behavior
When I set debug to false there no notification should fire and when the app is in the foregroup then the notification should not come.

## Actual Behavior
When I set debug to false still I am able to get all notifications on IOS. Even when the app is in the foreground still I am getting notifications. Please let me know how to stop notification when the app starts.

## Steps to Reproduce

1.
2.
3.
4.

## Context
I don't what notification at every time user moves Is there any way I can reduce some notifications in ios or maybe stop notifications Or is there any way to customize notifications like notification will fire only after 15,20 sec ETC.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
flutter: [enabledchange] - true
flutter: [connectivitychange] - [ConnectivityChangeEvent connected: true]
flutter: [location] - [Location {coords: {speed_accuracy: 0.0, speed: 32.85, longitude: -122.42104766, floor: 0, heading_accuracy: 0.0, latitude: 37.73175391, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 78.75}, sample: true, extras: {}, is_moving: false, odometer: 16994.9, uuid: 6458C47D-2A57-4F70-B03C-9C052B3B4C63, activity: {type: unknown, confidence: 100}, battery: {level: -1.0, is_charging: false}, timestamp: 2022-03-10T09:44:56.641Z}]
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(CANNOT_SEND_MAIL, null, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
<asynchronous suspension>
#2      Logger.emailLog (package:flutter_background_geolocation/models/logger.dart:281:12)
<asynchronous suspension>
flutter: [location] - [Location {coords: {speed_accuracy: 0.0, speed: 32.85, longitude: -122.42104766, floor: 0, heading_accuracy: 0.0, latitude: 37.73175391, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 78.75}, sample: true, extras: {}, is_moving: true, odometer: 16994.9, uuid: 9FA0A84B-4E4F-4951-8CD0-73D3D872C1C3, activity: {type: unknown, confidence: 100}, battery: {level: -1.0, is_charging: false}, timestamp: 2022-03-10T09:44:56.641Z}]
flutter: [motionchange] - [Location {coords: {speed_accuracy: 0.0, speed: 25.6, longitude: -122.40525775, floor: 0, heading_accuracy: 0.0, latitude: 37.76297864, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 21.45}, extras: {}, is_moving: true, event: motionchange, odometer: 16994.9, uuid: A6E94647-2F25-46FC-A143-B8CFDC5CBBEE, activity: {type: unknown, confidence: 100}, battery: {level: -1.0, is_charging: false}, timestamp: 2022-03-10T09:47:09.618Z}]
flutter: device is moving
flutter: [location] - [Location {coords: {speed_accuracy: 0.0, speed: 25.6, longitude: -122.40525775, floor: 0, heading_accuracy: 0.0, latitude: 37.76297864, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 21.45}, extras: {}, is_moving: true, event: motionchange, odometer: 16994.9, uuid: A6E94647-2F25-46FC-A143-B8CFDC5CBBEE, activity: {type: unknown, confidence: 100}, battery: {level: -1.0, is_charging: false}, timestamp: 2022-03-10T09:47:09.618Z}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [location] ERROR - [LocationError code: 0, message: LOCATION_ERROR]
flutter: [location] - [Location {coords: {speed_accuracy: 0.0, speed: 1.67, longitude: -122.03254703, floor: 0, heading_accuracy: 0.0, latitude: 37.33527476, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 178.24}, extras: {}, is_moving: true, odometer: 74771.6, uuid: BE530DBB-466E-4AE2-833D-044425521597, activity: {type: unknown, confidence: 100}, battery: {level: -1.0, is_charging: false}, timestamp: 2022-03-10T09:47:12.698Z}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [location] - [Location {coords: {speed_accuracy: 0.0, speed: 2.41, longitude: -122.03255055, floor: 0, heading_accuracy: 0.0, latitude: 37.33517518, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 184.57}, extras: {}, is_moving: true, odometer: 74782.6, uuid: 032D5641-E6BC-4FEE-9E39-07279B28303D, activity: {type: unknown, confidence: 100}, battery: {level: -1.0, is_charging: false}, timestamp: 2022-03-10T09:47:17.722Z}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [location] - [Location {coords: {speed_accuracy: 0.0, speed: 4.47, longitude: -122.0326037, floor: 0, heading_accuracy: 0.0, latitude: 37.33507162, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 218.67}, extras: {}, is_moving: true, odometer: 74795.1, uuid: 0C6C2BEC-97A7-4050-A6E0-1E6105781F17, activity: {type: unknown, confidence: 100}, battery: {level: -1.0, is_charging: false}, timestamp: 2022-03-10T09:47:20.758Z}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [location] - [Location {coords: {speed_accuracy: 0.0, speed: 9.18, longitude: -122.03281282, floor: 0, heading_accuracy: 0.0, latitude: 37.33497737, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 251.37}, extras: {}, is_moving: true, odometer: 74816.3, uuid: 75D1F9DF-24A4-41AE-86B5-01B627AC1A1E, activity: {type: unknown, confidence: 100}, battery: {level: -1.0, is_charging: false}, timestamp: 2022-03-10T09:47:23.759Z}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [location] - [Location {coords: {speed_accuracy: 0.0, speed: 13.66, longitude: -122.03318372, floor: 0, heading_accuracy: 0.0, latitude: 37.33489242, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 254.88}, extras: {}, is_moving: true, odometer: 74850.5, uuid: 1FA85837-7C20-475A-9999-EA78F3463921, activity: {type: unknown, confidence: 100}, battery: {level: -1.0, is_charging: false}, timestamp: 2022-03-10T09:47:26.725Z}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [location] - [Location {coords: {speed_accuracy: 0.0, speed: 17.21, longitude: -122.03369603, floor: 0, heading_accuracy: 0.0, latitude: 37.33477977, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 255.59}, extras: {}, is_moving: true, odometer: 74897.6, uuid: 5EA6ED23-EF6F-418E-9F1E-DBA22895C9D8, activity: {type: unknown, confidence: 100}, battery: {level: -1.0, is_charging: false}, timestamp: 2022-03-10T09:47:29.783Z}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [location] - [Location {coords: {speed_accuracy: 0.0, speed: 20.07, longitude: -122.03432425, floor: 0, heading_accuracy: 0.0, latitude: 37.33467638, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 259.45}, extras: {}, is_moving: true, odometer: 74954.5, uuid: 411FEC57-CD7C-40C6-B212-B69E71C1D70E, activity: {type: unknown, confidence: 100}, battery: {level: -1.0, is_charging: false}, timestamp: 2022-03-10T09:47:32.754Z}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [location] - [Location {coords: {speed_accuracy: 0.0, speed: 22.45, longitude: -122.0350347, floor: 0, heading_accuracy: 0.0, latitude: 37.33460316, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 265.08}, extras: {}, is_moving: true, odometer: 75017.9, uuid: 1DB86851-B600-4ECE-912E-B8F28708DC24, activity: {type: unknown, confidence: 100}, battery: {level: -1.0, is_charging: false}, timestamp: 2022-03-10T09:47:35.773Z}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [location] - [Location {coords: {speed_accuracy: 0.0, speed: 24.28, longitude: -122.03583308, floor: 0, heading_accuracy: 0.0, latitude: 37.3345597, accuracy: 5.0, altitude_accuracy: -1.0, altitude: 0.0, heading: 267.19}, extras: {}, is_moving: true, odometer: 75088.9, uuid: D61E06F5-3CD9-4B4B-8489-699A2F0731C0, activity: {type: unknown, confidence: 100}, battery: {level: -1.0, is_charging: false}, timestamp: 2022-03-10T09:47:38.793Z}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]
flutter: [http] - [HttpEvent {success: true, status: 200, responseText: {"success":true}}]

```

</details>

![Simulator Screen Shot - iPhone 12 Pro Max - 2022-03-09 at 15 41 40](https://user-images.githubusercontent.com/11865669/157637461-983834e7-016c-43be-b502-1fac338fb1a8.png)

![Simulator Screen Shot - iPhone 12 Pro Max - 2022-03-10 at 15 03 54](https://user-images.githubusercontent.com/11865669/157637504-4ec70fa4-3db2-4361-8165-3121c00fc36c.png)

**Comment by christocracy** [comment]
See api docs Config.debug.

those are there to assist you during development during field testing.

**Comment by jigarfumakiya** [comment]
@christocracy 

As you can see in my code I have set debug as false why I am still getting the notifications?

**Comment by christocracy** [comment]
>reset: false,

Yes, and you've also done this, causing your Config provided to `.ready()` to be consumed only on the first install of your app.

Do you know what `reset: false` does?  99% of people do not need that.

**Comment by jigarfumakiya** [comment]
@christocracy 
One more question, please.
If I have set stopOnStationary to true and the plugin turns off the location service but if the user starts moving again then 
do the plugin start automatically or not?

In my case plugin is not starting

Thanks

**Comment by christocracy** [comment]
> do the plugin start automatically or not?

No.  stopOnStationary literally means `.stop()` *on stationary.*

Have you read the api docs for that option?

**Comment by jigarfumakiya** [comment]
Yes, I have but I did find anything on the automatically start plugin?
Just making sure that functionality exists or not?

**Comment by jigarfumakiya** [comment]
ok, thanks @christocracy

**Comment by jigarfumakiya** [comment]
@christocracy 
What if the plugin working in the background and the user manually changes permission? At that time plugin does not give any callback, not even a headless trigger?
that happens when the app in the background is not closed and when the app is terminated

Any idea?
