### ISSUE TITLE
ForegroundServiceStartNotAllowedException & SQLiteCantOpenDatabaseException in Android 11 and 12

### ISSUE THREAD

**Issue by Intellitrack2017** [transistorsoft/flutter_background_geolocation#747]
<summary>Logs</summary>

**Crash 1:**

`Fatal Exception: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.affluence.clu/com.transistorsoft.locationmanager.service.TrackingService
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
       at android.os.Parcel.readParcelable(Parcel.java:3349)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2436)
       at android.os.Parcel.createException(Parcel.java:2425)
       at android.os.Parcel.readException(Parcel.java:2408)
       at android.os.Parcel.readException(Parcel.java:2350)
       at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6069)
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1849)
       at android.app.ContextImpl.startForegroundService(ContextImpl.java:1825)
       at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:789)
       at com.transistorsoft.locationmanager.service.AbstractService$a.run(AbstractService.java:10)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8184)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)`

**Crash 2:**

`Caused by android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14 SQLITE_CANTOPEN): , while compiling: PRAGMA journal_mode
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
       at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:788)
       at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:405)
       at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:335)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:258)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:918)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:898)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:762)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:751)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:373)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:4)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:4)
       at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:2)
       at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java)
       at androidx.work.impl.model.SystemIdInfoDao_Impl.getWorkSpecIds(SystemIdInfoDao_Impl.java:9)
       at androidx.work.impl.background.systemjob.SystemJobScheduler.reconcileJobs(SystemJobScheduler.java:20)
       at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:11)
       at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java)
       at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:31)
       at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)`

```

**Comment by Intellitrack2017** [comment]
I raised another issue with proper details
