### ISSUE TITLE
Android crashes on release build

### ISSUE THREAD

**Issue by santa112358** [transistorsoft/flutter_background_geolocation#780]
## Your Environment
* Plugin version: 4.6.3
* Platform: Android
* OS version: Android9
* Device manufacturer / model: Xperia XZ1
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.0.1 21A559 darwin-arm, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.65.2)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

* Plugin config:
This is called only when the user permitted always location permission.
```dart <-- Syntax highlighting: DO NOT REMOVE -->

    bg.BackgroundGeolocation.onLocation(
      (bg.Location location) {
        _onLocationUpdated(
          latitude: location.coords.latitude,
          longitude: location.coords.longitude,
        );
      },
    );

    await bg.BackgroundGeolocation.ready(
      bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: _distanceFilter,
        stopOnTerminate: false,
        startOnBoot: true,
        logLevel: bg.Config.LOG_LEVEL_OFF,
      ),
    ).then((bg.State state) {
      if (!state.enabled) {
        bg.BackgroundGeolocation.start();
      }
    });

```

## Expected Behavior

Does not crash on release build.

## Actual Behavior

Crashes.

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
Fatal Exception: java.lang.ExceptionInInitializerError
       at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance()
       at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule.ready(BackgroundGeolocationModule.java:345)
       at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule.onMethodCall(BackgroundGeolocationModule.java:223)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:320)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java)
       at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(lambda:12)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:280)
       at android.app.ActivityThread.main(ActivityThread.java:6710)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.transistorsoft.tslocationmanager.Application.A(Application.java:27)
       at com.transistorsoft.locationmanager.adapter.TSConfig.<clinit>(:2)
       at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance()
       at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule.ready(BackgroundGeolocationModule.java:345)
       at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule.onMethodCall(BackgroundGeolocationModule.java:223)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:320)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java)
       at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(lambda:12)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:280)
       at android.app.ActivityThread.main(ActivityThread.java:6710)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

</details>

**Comment by christocracy** [comment]
You have something unusual in your Android setup.  Post the following 3 files;
- android/build.gradle
- android/app/build.gradle
- AndroidManifest.xml

**Comment by santa112358** [comment]
@christocracy 
Thank you for the response.


- android/build.gradle
```
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
        maven { url 'https://artifacts.applovin.com/android' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
        classpath "com.applovin.quality:AppLovinQualityServiceGradlePlugin:+"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://imobile-maio.github.io/maven" }
        maven { url "http://fan-adn.github.io/nendSDK-Android-lib/library" }
        maven { url "https://artifact.bytedance.com/repository/pangle" }
        maven { url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea" }
        maven { url "${project(':background_fetch').projectDir}/libs" }
        maven { url "${project(':flutter_background_geolocation').projectDir}/libs" }

    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

- android/app/build.gradle
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 31
    ndkVersion '23.1.7779620'

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
    }

    apply from: 'signingConfigs/debug.gradle', to: android
    apply from: 'signingConfigs/release.gradle', to: android

    defaultConfig {
        applicationId "com.dash.enryaku"
        minSdkVersion 23
        targetSdkVersion 31
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        signingConfig signingConfigs.debug
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            debuggable true

            ndk {
                debugSymbolLevel 'SYMBOL_TABLE'
            }
        }
        release {
            signingConfig signingConfigs.release
            debuggable false

            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            ndk {
                debugSymbolLevel 'SYMBOL_TABLE'
            }
        }
    }

    flavorDimensions "flavor-type"
    productFlavors {
        development {
            dimension "flavor-type"
            applicationIdSuffix ".development"
            versionNameSuffix "-development"
            resValue "string", "app_name", "CASHMART-D"
        }
        staging {
            dimension "flavor-type"
            applicationIdSuffix ".staging"
            versionNameSuffix "-staging"
            resValue "string", "app_name", "CASHMART-S"
        }
        production {
            dimension "flavor-type"
            resValue "string", "app_name", "CASHMART"
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "androidx.browser:browser:1.4.0"
    implementation 'androidx.work:work-runtime-ktx:2.7.1'
    implementation 'com.google.android.exoplayer:exoplayer:2.17.1'
    implementation 'com.applovin.mediation:google-adapter:21.0.0.0'
    implementation 'com.applovin.mediation:line-adapter:2021.10.29.2'
    implementation 'com.applovin.mediation:maio-adapter:1.1.16.2'
    implementation 'com.applovin.mediation:nend-adapter:8.0.1.1'
    implementation 'com.applovin.mediation:bytedance-adapter:4.5.0.3.0'
    implementation 'com.applovin.mediation:mintegral-adapter:16.1.11.2'
    implementation 'com.applovin.mediation:unityads-adapter:4.2.1.0'
}

apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'applovin-quality-service'
applovin {
       apiKey "V47L4HsGmmTLOR-9xH5QW84OtEmol3ttBymQBPoATkCMN9QFMJBqaD6rCyVo-1o17DNbH5AKRu5aGab6r92hz8"
}

```
- AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.dash.enryaku">

    <application
        android:icon="@mipmap/launcher_icon"
        android:label="@string/app_name"
        tools:replace="android:label">
        <!-- flutter_background_geolocation licence -->
        <meta-data
            android:name="com.transistorsoft.locationmanager.license"
            android:value="0b01af22379d7928ec725695055b8d4448f528ccf1a7cf149d492d4a22fbdeae" />
        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:exported="true"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:requestLegacyExternalStorage="true"
            android:screenOrientation="portrait"
            android:showWhenLocked="true"
            android:theme="@style/LaunchTheme"
            android:turnScreenOn="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />
            <meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background" />

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="cashmartd.page.link"
                    android:pathPrefix=".*"
                    android:scheme="https" />
                <data
                    android:host="cashmarts.page.link"
                    android:pathPrefix=".*"
                    android:scheme="https" />
                <data
                    android:host="invite.cashmart.jp"
                    android:pathPrefix=".*"
                    android:scheme="https" />
                <data
                    android:host="cashmart.page.link"
                    android:pathPrefix=".*"
                    android:scheme="https" />
            </intent-filter>
        </activity>

        <!-- apple login -->
        <activity
            android:name="com.aboutyou.dart_packages.sign_in_with_apple.SignInWithAppleCallback"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="signinwithapple" />
                <data android:path="callback" />
            </intent-filter>
        </activity>

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-9590637134858990~9037049161" />
        <meta-data
            android:name="applovin.sdk.key"
            android:value="oGfucyanS8JmP56VIA5TAbwvZIGeEmBCT4qS4wx1MveQTuC99HOOfgs1_MULrTudwi6m6VTx9FTEzE5dPc2iB7" />
        <meta-data
            android:name="applovin.sdk.verbose_logging"
            android:value="false" />
        <meta-data
            android:name="delivery_metrics_exported_to_big_query_enabled"
            android:value="true" />

        <service
            android:name="rekab.app.background_locator.IsolateHolderService"
            android:exported="true"
            android:foregroundServiceType="location"
            android:permission="android.permission.FOREGROUND_SERVICE" />
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>

    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

    <queries>
        <intent>
            <action android:name="android.support.customtabs.action.CustomTabsService" />
        </intent>
    </queries>
</manifest>

```

**Comment by christocracy** [comment]
See here at the Android Developer docs about recommendation for using [*Project-wide `ext` properties*](https://developer.android.com/studio/build/gradle-tips#configure-project-wide-properties)

<img width="906" alt="Screen Shot 2022-06-27 at 10 09 45 AM" src="https://user-images.githubusercontent.com/14999/175961463-c362bf70-8593-4b3b-9503-e2e43bff66b0.png">

**Comment by christocracy** [comment]
Also, you should upgrade to the latest `4.7.0` which was significantly refactored for much improved *Android 12* support.

**Comment by santa112358** [comment]
@christocracy 
After added the missing settings, it worked completely fine on release build.
Thank you for your quick support!!!
