### ISSUE TITLE
VerifyError in Google pre-launch report

### ISSUE THREAD

**Issue by ozzy1873** [transistorsoft/flutter_background_geolocation#786]
## Your Environment
* Plugin version: 4.7.0
* Platform: Android
* OS version: 12
* Device manufacturer / model: Google Pixel 6
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.22000.739], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.15)
[√] Android Studio (version 2021.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  bg.Config _getBgConfig(bool moving) {
    return bg.Config(
      reset: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5.0,
      preventSuspend: true,
      heartbeatInterval: Platform.isAndroid ? null : 30,
      isMoving: moving,
      stopOnTerminate: true,
      stopOnStationary: false,
      startOnBoot: false,
      stopTimeout: enableInactivityTimeout ? inactivityTimeoutMinutes : 5,
      debug: _logRide,
      logLevel: _logLevel,
      logMaxDays: 1,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      foregroundService: true,
      locationAuthorizationRequest: Platform.isAndroid ? 'WhenInUse' : 'Always',
      backgroundPermissionRationale: Platform.isAndroid
          ? null
          : bg.PermissionRationale(
              title: localize.dlgBackgroundLocationPermissionTitle,
              message: localize.dlgBackgroundLocationPermissionContent,
              positiveAction: localize.dlgBackgroundLocationPermissionAction1,
              negativeAction: localize.dlgBackgroundLocationPermissionAction2),
    );
  }
```

## Expected Behavior

No exceptions.
## Actual Behavior

The Google pre-launch report shows this crash:
FATAL EXCEPTION: pool-8-thread-3
Process: com.xxxx.xxxx, PID: 26439
java.lang.VerifyError: Superclass androidx.core.app.f of androidx.activity.ComponentActivity is declared final (declaration of 'androidx.activity.ComponentActivity' appears in /data/app/~~9Uip78QaVATSX7o5FKnF0A==/com.xxxx.xxxx-sTAYk9CooCdl2DV0ucsUqQ==/base.apk)
	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:196)
	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.b(Unknown Source:9)
	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:10)
	at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule$1.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
## Steps to Reproduce

1. The prelaunch report shows a crash when calling await bg.BackgroundGeolocation.ready(_getBgConfig(false)) at app startup. This gets called automatically when the app starts up, not when the user presses a button. So, when playing back the test, I see the splash screen, then the first screen gets painted, then ready gets called and the app crashes.
2.
3.
4.

## Context

This is in the pre-launch test, so it may be due to a Google bug. I don't see any crashes on my own Pixel 3 running Android 12.

I rebuilt and resubmitted and this time the Google Pixel 6/Android 12 and Google Pixel 5/Android 11 passed, but the Samsung Galaxy S20 5G/Android 10 and DOCOMO AQUOS sense2 SH-01L/Android 9 failed.

Trying to make sense of this...
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by ozzy1873** [comment]
https://issuetracker.google.com/issues/237785592

**Comment by ozzy1873** [comment]
Adding this proguard rule solves the problem:

-keep class androidx.core.app.** { *; }

Closing.
