### ISSUE TITLE
IncompatibleClassChangeError in Google pre-launch report

### ISSUE THREAD

**Issue by ozzy1873** [transistorsoft/flutter_background_geolocation#787]
## Your Environment
* Plugin version: 4.7.0
* Platform: Android
* OS version: 8.1
* Device manufacturer / model: xiaomi Redmi 6A, Nokia Nokia 1
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.22000.739], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.15)
[√] Android Studio (version 2021.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
• No issues found!
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  bg.Config _getBgConfig(bool moving) {
    return bg.Config(
      reset: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5.0,
      preventSuspend: true,
      heartbeatInterval: Platform.isAndroid ? null : 30,
      isMoving: moving,
      stopOnTerminate: true,
      stopOnStationary: false,
      startOnBoot: false,
      stopTimeout: enableInactivityTimeout ? inactivityTimeoutMinutes : 5,
      debug: _logRide,
      logLevel: _logLevel,
      logMaxDays: 1,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      foregroundService: true,
      locationAuthorizationRequest: Platform.isAndroid ? 'WhenInUse' : 'Always',
      backgroundPermissionRationale: Platform.isAndroid
          ? null
          : bg.PermissionRationale(
              title: localize.dlgBackgroundLocationPermissionTitle,
              message: localize.dlgBackgroundLocationPermissionContent,
              positiveAction: localize.dlgBackgroundLocationPermissionAction1,
              negativeAction: localize.dlgBackgroundLocationPermissionAction2),
    );
  }
```

## Expected Behavior

No exceptions.
## Actual Behavior

The Google pre-launch report shows this crash:
FATAL EXCEPTION: pool-7-thread-3
Process: com.osborntech.supercycle, PID: 27275
java.lang.IncompatibleClassChangeError: Superclass androidx.core.app.f of androidx.activity.ComponentActivity is declared final (declaration of 'androidx.activity.ComponentActivity' appears in /data/app/com.osborntech.supercycle-Kk0qQcYsQziY8dHYMKk5NQ==/base.apk)
	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:196)
	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.b(Unknown Source:9)
	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:10)
	at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule$1.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
## Steps to Reproduce

1. The prelaunch report shows a crash when calling await bg.BackgroundGeolocation.ready(_getBgConfig(false)) at app startup. This gets called automatically when the app starts up, not when the user presses a button. So, when playing back the test, I see the splash screen, then the first screen gets painted, then ready gets called and the app crashes.
2.
3.
4.

## Context

This is in the pre-launch test, so it may be due to a Google bug. I do not see crashes on my own devices, but I only have Android 9 and 12, not 8.1. The tests pass for Samsung Galaxy S9/Android 8, Google Pixel 5/Android 11, Samsung Galaxy s20 5G/Android 10, and DOCOMO AQUOS sense2 SH-01L/Android 9.
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I was not aware of this "*Prelaunch Report*".  I have set this up for myself now in *Google Play Console* and submitted a release for testing.

**Comment by christocracy** [comment]
Try a prelaunch-test with `disableLocationAuthorizationAlert: true`

**Comment by ozzy1873** [comment]
The tests are still running, but I am still getting this error on Samsung Galaxy S9/Android 8

**Comment by ozzy1873** [comment]
Here is the logcat file
[logcat.txt](https://github.com/transistorsoft/flutter_background_geolocation/files/9033589/logcat.txt)

**Comment by christocracy** [comment]
When we see an error on `TSLocationManagerActivity`, this is related to [`Config.disableLocationAuthorizationAlert`](https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/disableLocationAuthorizationAlert.html) (default is `false`), where an *invisible, transparent* activity is shown so that the plugin can execute an automated [Settings resolution check](https://developers.google.com/android/reference/com/google/android/gms/location/SettingsClient) provided by the *Play Services Location API*.  Eg:  if we attempt to turn on location updates and the user has *Location: Disabled*, the OS will automatically show a dialog to the user:  *"Location Services are required:  Enable?"*.

However, while debugging a previous issue related to a *Samsung* device, I added a 200ms timeout before this "invisible Activity" is shown:

It could be that this 200ms timeout doesn't play nice with the automated testing system.  Perhaps the `Activity` is attempt to be shown while the test-harness is in the process of tearing itself down when the timer fires a new `Activity` is attempted to be shown.

```java
//
// TSLocationManagerActivity.java
//
handler.postDelayed(new Runnable() {
            @Override public void run() {
                try {
                    context.startActivity(intent);   // <--------------- start Activity
                } catch (ActivityNotFoundException e) {
                    TSLog.logger.error(TSLog.error(e.getMessage()), e);
                }
            }
        }, 200);  // <-------- 200ms timeout
```




```
07-02 12:15:26.270: I/zygote64(10328): Rejecting re-init on previously-failed class java.lang.Class<com.transistorsoft.locationmanager.activity.TSLocationManagerActivity>: java.lang.IncompatibleClassChangeError: Superclass androidx.core.app.f of androidx.activity.ComponentActivity is declared final (declaration of 'androidx.activity.ComponentActivity' appears in /data/app/com.osborntech.supercycle-f-lnaQCs-PqpV4UXZqugAQ==/base.apk)
07-02 12:15:26.270: I/zygote64(10328):   at void com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(android.content.Context) (:-1)
07-02 12:15:26.270: I/zygote64(10328):   at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.b(android.content.Context) (:-1)
07-02 12:15:26.270: I/zygote64(10328):   at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(android.content.Context) (:-1)
07-02 12:15:26.270: I/zygote64(10328):   at void com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule$1.run() (:-1)
07-02 12:15:26.270: I/zygote64(10328):   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1162)
07-02 12:15:26.270: I/zygote64(10328):   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:636)
07-02 12:15:26.270: I/zygote64(10328):   at void java.lang.Thread.run() (Thread.java:764)
```

**Comment by ozzy1873** [comment]
I got the same failure whether disableLocationAuthorizationAlert was true or false. Also, this was working fine just a week ago and I don't think I made any code changes that would be related. Makes me think this is a Google bug. Did you get prelaunch failures?

**Comment by christocracy** [comment]
*Google Pixel 2 (Virtual), 1080x1920, Android 9 (SDK 28)*

```
FATAL EXCEPTION: main
Process: com.transistorsoft.flutterbackgroundgeolocationexample, PID: 9232
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.transistorsoft.flutterbackgroundgeolocationexample/com.transistorsoft.flutterbackgroundgeolocationexample.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
	at m1.d.e(Unknown Source:460)
	at io.flutter.embedding.engine.a.<init>(Unknown Source:184)
	at io.flutter.embedding.engine.a.<init>(Unknown Source:12)
	at io.flutter.embedding.android.e.F(Unknown Source:106)
	at io.flutter.embedding.android.e.o(Unknown Source:7)
	at io.flutter.embedding.android.d.onCreate(Unknown Source:13)
	at android.app.Activity.performCreate(Activity.java:8051)
	at android.app.Activity.performCreate(Activity.java:8031)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
	... 12 more
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
	at m1.d.e(Unknown Source:28)
	... 21 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1656)
	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(Unknown Source:13)
	at m1.d$a.b(Unknown Source:18)
	at m1.d$a.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
```

**Comment by ozzy1873** [comment]
Did you add the following to your app/build.gradle under buildTypes/release?
           ndk {
                abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
            }

**Comment by christocracy** [comment]
Yes

**Comment by christocracy** [comment]
I'll create a virtual device for *Google Pixel 2 (Virtual), 1080x1920, Android 9 (SDK 28)* and see if anything can be done.

**Comment by christocracy** [comment]
So far no crash on the virtual device.

**Comment by ozzy1873** [comment]
This issue: https://issuetracker.google.com/issues/237785592
I posted that same link in #786 .
There are comments for that issue that also mention IncompatibleClassChangeError. Looks like the issue has been assigned.

**Comment by christocracy** [comment]
Yea, something exploded over there.

**Comment by christocracy** [comment]
Where did you discover this?
