### ISSUE TITLE
Plugin crashed on Android Emulator.

### ISSUE THREAD

**Issue by MichalMisiaszek** [transistorsoft/flutter_background_geolocation#86]
Plugin crashed on Android Emulator

## Your Environment
* Plugin version: 1.0.9
* Platform: Android
* OS version: 9
* Device manufacturer / model: Emulator
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
              desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
              distanceFilter: _gpsInterval,
              disableElasticity: true,
              stopOnTerminate: false,
              startOnBoot: false,
              debug: false,
              logLevel: bg.Config.LOG_LEVEL_DEBUG,
              reset: true
```

## Expected Behavior

Update location,
## Actual Behavior

App crashed
## Steps to Reproduce

Can't reproduce.

## Context

Pull static location.
## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
I/flutter ( 6550): [providerchange] - [ProviderChangeEvent enabled:true, status: 2, network: true, gps: true]
D/TSLocationManager( 6550): [c.t.l.l.TSLocationManager clearLastOdometerLocation]
D/TSLocationManager( 6550):   ℹ️  Clear last odometer location
D/TSLocationManager( 6550): [c.t.l.g.TSGeofenceManager c] ℹ️  Persist monitored geofences: []
D/TSLocationManager( 6550): [c.t.l.g.TSGeofenceManager b]
D/TSLocationManager( 6550):   🔴  Stop monitoring geofences
I/TSLocationManager( 6550): [c.t.l.g.TSGeofenceManager stopMonitoringSignificantLocationChanges]
I/TSLocationManager( 6550):   🔴  Stop monitoring significant location changes
D/TSLocationManager( 6550): [c.t.l.g.TSGeofenceManager stopMonitoringStationaryRegion]
D/TSLocationManager( 6550):   🔴  Stop monitoring stationary region
I/TSLocationManager( 6550): [c.t.l.s.ActivityRecognitionService b]
I/TSLocationManager( 6550):   🔴  Stop motion-activity updates
I/TSLocationManager( 6550): [c.t.l.service.HeartbeatService a]
I/TSLocationManager( 6550):   🔴  Stop heartbeat
D/TSLocationManager( 6550): [c.t.l.http.HttpService stopMonitoringConnectivityChanges]
D/TSLocationManager( 6550):   🔴  Stop monitoring connectivity changes
D/TSLocationManager( 6550): [c.t.l.service.TrackingService onDestroy]
D/TSLocationManager( 6550):   🔴  TrackingService destroyed
D/TSLocationManager( 6550): [c.t.l.s.GeofencingService onDestroy]
D/TSLocationManager( 6550):   🔴  GeofencingService destroyed
D/TSLocationManager( 6550): [c.t.l.s.ActivityRecognitionService onDestroy]
D/TSLocationManager( 6550):   🔴  ActivityRecognitionService destroyed
I/pestscopemobil( 6550): Waiting for a blocking GC ProfileSaver
I/pestscopemobil( 6550): Background concurrent copying GC freed 192660(4MB) AllocSpace objects, 7(328KB) LOS objects, 31% free, 13MB/19MB, paused 6.506ms total 443.885ms
I/pestscopemobil( 6550): WaitForGcToComplete blocked ProfileSaver on ProfileSaver for 88.457ms
I/pestscopemobil( 6550): Background concurrent copying GC freed 283450(7MB) AllocSpace objects, 7(128KB) LOS objects, 30% free, 13MB/19MB, paused 18us total 284.245ms
I/pestscopemobil( 6550): Background concurrent copying GC freed 209682(6MB) AllocSpace objects, 7(132KB) LOS objects, 26% free, 16MB/22MB, paused 260us total 239.341ms
I/pestscopemobil( 6550): Background concurrent copying GC freed 237734(5MB) AllocSpace objects, 12(1684KB) LOS objects, 25% free, 17MB/23MB, paused 24us total 144.170ms
I/pestscopemobil( 6550): Background concurrent copying GC freed 224182(6MB) AllocSpace objects, 8(4MB) LOS objects, 30% free, 13MB/19MB, paused 41us total 115.199ms
I/pestscopemobil( 6550): Background concurrent copying GC freed 313141(8MB) AllocSpace objects, 10(184KB) LOS objects, 49% free, 5MB/11MB, paused 22us total 117.599ms
I/flutter ( 6550): Temp:60
I/pestscopemobil( 6550): Background concurrent copying GC freed 221417(5MB) AllocSpace objects, 7(244KB) LOS objects, 47% free, 6MB/12MB, paused 666us total 108.017ms
I/flutter ( 6550): With team parcels:210
I/flutter ( 6550): [MFKokWkBsxgSvtTOFlZsbjUqSaw2, null, daA6yvJGBUgX8dSjB78ZyNr1OUw2]
I/flutter ( 6550): Temp:60
I/flutter ( 6550): Temp:60
I/TSLocationManager( 6550): [c.t.locationmanager.util.b$1 onPermissionGranted]
I/TSLocationManager( 6550):   ✅  LocationAuthorization: Permission granted
D/AndroidRuntime( 6550): Shutting down VM
I/flutter ( 6550): [providerchange] - [ProviderChangeEvent enabled:true, status: 3, network: true, gps: true]
E/AndroidRuntime( 6550): FATAL EXCEPTION: main
E/AndroidRuntime( 6550): Process: com.pestscope.pestscopemobile, PID: 6550
E/AndroidRuntime( 6550): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=34, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.pestscope.pestscopemobile/com.pestscope.pestscopemobile.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 6550): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
E/AndroidRuntime( 6550): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
E/AndroidRuntime( 6550): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime( 6550): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime( 6550): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime( 6550): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime( 6550): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6550): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 6550): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 6550): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6550): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 6550): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime( 6550): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 6550): 	at com.lyokone.location.LocationPlugin$1.onRequestPermissionsResult(LocationPlugin.java:200)
E/AndroidRuntime( 6550): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:203)
E/AndroidRuntime( 6550): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:128)
E/AndroidRuntime( 6550): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:137)
E/AndroidRuntime( 6550): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7608)
E/AndroidRuntime( 6550): 	at android.app.Activity.dispatchActivityResult(Activity.java:7458)
E/AndroidRuntime( 6550): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
E/AndroidRuntime( 6550): 	... 11 more
E/TSLocationManager( 6550): [c.t.l.a.BackgroundGeolocation$e uncaughtException]
E/TSLocationManager( 6550):   ‼️  Uncaught Exception: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=34, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.pestscope.pestscopemobile/com.pestscope.pestscopemobile.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/TSLocationManager( 6550): {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"autoSync":true,"autoSyncThreshold":0,"batchSync":false,"debug":false,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableElasticity":true,"disableLocationAuthorizationAlert":false,"disableStopDetection":false,"distanceFilter":1,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"forceReloadOnBoot":false,"forceReloadOnGeofence":false,"forceReloadOnHeartbeat":false,"forceReloadOnLocationChange":false,"forceReloadOnMotionChange":false,"forceReloadOnSchedule":false,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":4,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":false,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":false,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":true}
E/TSLocationManager( 6550): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=34, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.pestscope.pestscopemobile/com.pestscope.pestscopemobile.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/TSLocationManager( 6550): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
E/TSLocationManager( 6550): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
E/TSLocationManager( 6550): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/TSLocationManager( 6550): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/TSLocationManager( 6550): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/TSLocationManager( 6550): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/TSLocationManager( 6550): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/TSLocationManager( 6550): 	at android.os.Looper.loop(Looper.java:193)
E/TSLocationManager( 6550): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/TSLocationManager( 6550): 	at java.lang.reflect.Method.invoke(Native Method)
E/TSLocationManager( 6550): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/TSLocationManager( 6550): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/TSLocationManager( 6550): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/TSLocationManager( 6550): 	at com.lyokone.location.LocationPlugin$1.onRequestPermissionsResult(LocationPlugin.java:200)
E/TSLocationManager( 6550): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsRes
I/pestscopemobil( 6550): Background concurrent copying GC freed 147459(3MB) AllocSpace objects, 0(0B) LOS objects, 31% free, 12MB/18MB, paused 269us total 262.112ms
I/Process ( 6550): Sending signal. PID: 6550 SIG: 9
Lost connection to device.
```

</details>

**Comment by christocracy** [comment]
Not from my plugin.  It’s from another of your plugins;

E/AndroidRuntime( 6550): 	at com.lyokone.location.LocationPlugin$1.onRequestPermissionsResult(LocationPlugin.java:200)

**Comment by MichalMisiaszek** [comment]
Thanks.
