### ISSUE TITLE
Error Running the Demo App: dlopen failed: library "libflutter.so" not found

### ISSUE THREAD

**Issue by cafrie** [transistorsoft/flutter_background_geolocation#867]
## Your Environment
* Plugin version: 4.8.3
* Platform: Android
* OS version: Android 11.0
* Device manufacturer / model: Pixel 4
* Flutter info (`flutter doctor`):

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (4 available)
    ! Device emulator-5554 is offline.
[✓] HTTP Host Availability

• No issues found!
```

* Plugin config: (No changes made to the demo app)
```dart <-- Syntax highlighting: DO NOT REMOVE -->
reset: true,
debug: true,
logLevel: bg.Config.LOG_LEVEL_VERBOSE,
desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
distanceFilter: 10.0,
backgroundPermissionRationale: bg.PermissionRationale(
    title:
        "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
    message:
        "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
    positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
    negativeAction: 'Cancel'),
url: "${ENV.TRACKER_HOST}/api/locations",
authorization: bg.Authorization(
    // <-- demo server authenticates with JWT
    strategy: bg.Authorization.STRATEGY_JWT,
    accessToken: token.accessToken,
    refreshToken: token.refreshToken,
    refreshUrl: "${ENV.TRACKER_HOST}/api/refresh_token",
    refreshPayload: {'refresh_token': '{refreshToken}'}),
stopOnTerminate: false,
startOnBoot: true,
enableHeadless: true
```

## Expected Behavior

App should be installed and running on the device.

## Actual Behavior

App not being installed. Flutter initialization failed.

## Steps to Reproduce

1. Clone the repo
2. Open the demo app in Android Studio
3. Run on device

## Context

Trying to run the demo app.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
E/FlutterLoader(12260): Flutter initialization failed.
E/FlutterLoader(12260): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader(12260): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/FlutterLoader(12260): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/FlutterLoader(12260): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:239)
E/FlutterLoader(12260): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:327)
E/FlutterLoader(12260): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:207)
E/FlutterLoader(12260): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:271)
E/FlutterLoader(12260): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/FlutterLoader(12260): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/FlutterLoader(12260): 	at android.app.Activity.performCreate(Activity.java:7989)
E/FlutterLoader(12260): 	at android.app.Activity.performCreate(Activity.java:7978)
E/FlutterLoader(12260): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/FlutterLoader(12260): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3316)
E/FlutterLoader(12260): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3485)
E/FlutterLoader(12260): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/FlutterLoader(12260): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/FlutterLoader(12260): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/FlutterLoader(12260): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
E/FlutterLoader(12260): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/FlutterLoader(12260): 	at android.os.Looper.loop(Looper.java:223)
E/FlutterLoader(12260): 	at android.app.ActivityThread.main(ActivityThread.java:7478)
E/FlutterLoader(12260): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader(12260): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
E/FlutterLoader(12260): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
E/FlutterLoader(12260): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader(12260): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
E/FlutterLoader(12260): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
E/FlutterLoader(12260): 	at java.lang.System.loadLibrary(System.java:1661)
E/FlutterLoader(12260): 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
E/FlutterLoader(12260): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:189)
E/FlutterLoader(12260): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:182)
E/FlutterLoader(12260): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterLoader(12260): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterLoader(12260): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterLoader(12260): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime(12260): FATAL EXCEPTION: main
E/AndroidRuntime(12260): Process: com.transistorsoft.flutterbackgroundgeolocationexample, PID: 12260
E/AndroidRuntime(12260): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.transistorsoft.flutterbackgroundgeolocationexample/com.transistorsoft.flutterbackgroundgeolocationexample.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/AndroidRuntime(12260): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3341)
E/AndroidRuntime(12260): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3485)
E/AndroidRuntime(12260): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(12260): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(12260): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(12260): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
E/AndroidRuntime(12260): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(12260): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(12260): 	at android.app.ActivityThread.main(ActivityThread.java:7478)
E/AndroidRuntime(12260): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12260): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
E/AndroidRuntime(12260): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
E/AndroidRuntime(12260): Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/AndroidRuntime(12260): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:345)
E/AndroidRuntime(12260): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:327)
E/AndroidRuntime(12260): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:207)
E/AndroidRuntime(12260): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:271)
E/AndroidRuntime(12260): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/AndroidRuntime(12260): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/AndroidRuntime(12260): 	at android.app.Activity.performCreate(Activity.java:7989)
E/AndroidRuntime(12260): 	at android.app.Activity.performCreate(Activity.java:7978)
E/AndroidRuntime(12260): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime(12260): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3316)
E/AndroidRuntime(12260): 	... 11 more
E/AndroidRuntime(12260): Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/AndroidRuntime(12260): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/AndroidRuntime(12260): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/AndroidRuntime(12260): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:239)
E/AndroidRuntime(12260): 	... 20 more
E/AndroidRuntime(12260): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/AndroidRuntime(12260): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
E/AndroidRuntime(12260): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
E/AndroidRuntime(12260): 	at java.lang.System.loadLibrary(System.java:1661)
E/AndroidRuntime(12260): 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
E/AndroidRuntime(12260): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:189)
E/AndroidRuntime(12260): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:182)
```

</details>

**Comment by christocracy** [comment]
I just did a fresh clone and successfully ran `/example` on my *Samsung Galaxy S20 FE @ 12.0.0*

```console
git clone https://github.com/transistorsoft/flutter_background_geolocation.git
cd example
flutter pub get
flutter run
```

success.

**Comment by christocracy** [comment]
```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6 21G115 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```
