### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ozzy1873** [transistorsoft/flutter_background_geolocation#885]
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at java.util.Formatter$FormatSpecifier.addZeros(Formatter.java:3505)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:3401)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:3332)
       at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2893)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:2844)
       at java.util.Formatter.format(Formatter.java:2523)
       at java.util.Formatter.format(Formatter.java:2458)
       at java.lang.String.format(String.java:2770)
       at android.location.Location.toString(Location.java:1032)
       at java.lang.String.valueOf(String.java:2827)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at com.transistorsoft.locationmanager.service.LocationRequestService.handleLocationResult(:178)
       at com.transistorsoft.locationmanager.service.LocationRequestService.access$000()
       at com.transistorsoft.locationmanager.service.LocationRequestService$a.run(:24)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

## Your Environment
* Plugin version: 4.8.3
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Galaxy J7(2016)
* Flutter info (`flutter doctor`):
* [√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.22621.819], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.15)
[√] Android Studio (version 2021.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
  bg.Config _getBgConfig(bool moving) {
    var localize = GlobalContext().localize;
    return bg.Config(
      reset: true,
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 5.0,
      preventSuspend: true,
      heartbeatInterval: Platform.isAndroid ? null : 30,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      isMoving: moving,
      stopOnTerminate: true,
      stopOnStationary: false,
      startOnBoot: false,
      stopTimeout: 60 * 24 * 5,
      debug: _logRide,
      logLevel: _logLevel,
      logMaxDays: 1,
      persistMode: bg.Config.PERSIST_MODE_NONE,
      foregroundService: true,
      locationAuthorizationRequest: Platform.isAndroid ? 'WhenInUse' : 'Always',
      backgroundPermissionRationale: Platform.isAndroid
          ? null
          : bg.PermissionRationale(
              title: localize.dlgBackgroundLocationPermissionTitle,
              message: localize.dlgBackgroundLocationPermissionContent,
              positiveAction: localize.dlgBackgroundLocationPermissionAction1,
              negativeAction: localize.dlgBackgroundLocationPermissionAction2),
    );
  }
```

## Expected Behavior
No exception thrown

## Actual Behavior
This exception was thrown twice on a single device for a single user. 

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
>at android.location.Location.toString(Location.java:1032)

This is strange.  It looks like the OS's own `Location.toString` function is failing here while attempting to log the location, eg:

TSLocationManager: ╟─ 📍  Location[fused 45.518908,-73.600547 hAcc=20.0 et=+3m4s712ms alt=46.5 vAcc=1.2405908 vel=0.019391423 bear=236.63376 {Bundle[{}]}], age: 1192ms, time: 1668611585471
