### ISSUE TITLE
android, release, stops after some time

### ISSUE THREAD

**Issue by prasenjitpickcel** [transistorsoft/flutter_background_geolocation#89]
## Your Environment
* Plugin version: 1.0.10
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Vivo v9 model no - 1727 and few more android devices
* Flutter info (`flutter doctor`): NA
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
void initLocLib(String UID, String OID) {
  bg.BackgroundGeolocation.onLocation((bg.Location location) {
    postLocationUpdate(location.coords.latitude, location.coords.longitude, UID, OID, null, location.toMap(), location.coords.accuracy);
  });

  bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
    postLocationUpdate(location.coords.latitude, location.coords.longitude, UID, OID, null, location.toMap(), location.coords.accuracy);
  });
  
  bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
  bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
  bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);

  // 2.  Configure the plugin
  bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      distanceFilter: 0,
      stopOnTerminate: false,
      startOnBoot: true,
      url : "https://us-central1-taskcaretest2.cloudfunctions.net/orders/saveData/${UID}",
      debug: true,
      enableHeadless: true,
      reset: true,
      autoSync: true,
      batchSync: true,
      foregroundService: true,
      locationUpdateInterval: 30000
  )).then((bg.State state) {
    if(state.enabled == false) {
      _onClickEnable(true);
    }
  });
}
```

## Expected Behavior
Should update location to Firestore database in background.

## Actual Behavior
It stops after some time, if we use enable headless true? is it mandatory to register it in main.dart?

## Steps to Reproduce

1. Create a new Flutter app
2. Install the plugin as per https://github.com/transistorsoft/flutter_background_geolocation
3. Using the above plugin config to initialise
4. when the plugin state is ready enabling it by calling  _onClickEnable(true);

```dart <-- Syntax highlighting: DO NOT REMOVE -->
void _onClickEnable(enabled) {
    if (enabled) {
      bg.BackgroundGeolocation.start().then((bg.State state) {
        setState(() {
          _enabled = state.enabled;
        });
      });
    } else {
      bg.BackgroundGeolocation.stop().then((bg.State state) {
        bg.BackgroundGeolocation.setOdometer(0.0);
        setState(() {
          _enabled = state.enabled;
        });
      });
    }
  }
```

## Context
Trying to send the new location to firestore database

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by prasenjitpickcel** [comment]
with the above reference to make it clear of how we are sending location to our Firestore collection, when we get a new location, we are using firebase batch writes to send to our required collection.
Below is the code structure

final collRef = Firestore.instance.collection('organizations').document(OID)
      .collection("employees").document(UID)
      .collection("location");
  DocumentReference docReferance = collRef.document(UID)
      .collection(date)
      .document();
  var batch = Firestore.instance.batch();
  batch.setData(docReferance, userTrack);
  batch.commit();

**Comment by christocracy** [comment]
Never ignore the issue template:

*****************************************************************
*
* WARNING:  DO NOT IGNORE THIS TEMPLATE
*
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by prasenjitpickcel** [comment]
Your Environment

Plugin version: 1.0.10
Platform: Android
OS version: NA
Device manufacturer / model: vivo v9,  and few more devices
Flutter info (flutter doctor): 
/Users/mac/Desktop/Flutter/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, v1.5.4, on Mac OS X 10.14.5 18F132, locale en-IN)
    • Flutter version 1.5.4 at /Users/mac/Desktop/Flutter/flutter
    • Framework revision b593f5167b (3 months ago), 2019-04-22 07:51:33 -0700
    • Engine revision ca31a7c57b
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
Process finished with exit code 0

Plugin config: N/A



Expected Behavior

Following the instructions in https://github.com/transistorsoft/flutter_background_geolocation should provide us location when the app is in background


Actual Behavior
Sometimes it stops and it does not send location, it send again when the app is in foreground

Steps to Reproduce

1. Create a new Flutter app
2. Install the plugin as per https://github.com/transistorsoft/flutter_background_geolocation
3. following is the code sample(to start and stop the status of enabled we are using checkbox)



@override
  void initState() {
    super.initState();
    initLocLib();
}

void initLocLib() {
    bg.BackgroundGeolocation.onLocation(_onLocation);
    bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
    bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
    bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
    bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);

    // 2.  Configure the plugin
    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 2.0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: false,
        reset: true,
        //locationUpdateInterval: 5000
    )).then((bg.State state) {
      setState(() {
        _enabled = state.enabled;
        //_isMoving = state.isMoving;
      });
    });
  }

void _onLocation(bg.Location location) {
    //print("task.care new loc with lib is  : "+'[location] - $location');
    postLocationUpdate(
        location.coords.latitude,
        location.coords.longitude,
        UID,
        OID,
        null,
        location.toMap(),
        location.coords.accuracy);
  }

  void _onMotionChange(bg.Location location) {
    //print('task.care motion changed : - $location');
  }

  void _onActivityChange(bg.ActivityChangeEvent event) {
    //print('task.care user activity changed : - $event');
  }

  void _onProviderChange(bg.ProviderChangeEvent event) {
    //print("task.care provider changed"+'$event');
  }

  void _onConnectivityChange(bg.ConnectivityChangeEvent event) {
    //print("task.care connectivity changed : "+'$event');
  }

  void _onClickEnable(enabled) {
    if (enabled) {
      bg.BackgroundGeolocation.start().then((bg.State state) {
        setState(() {
          _enabled = state.enabled;
        });
      });
    } else {
      bg.BackgroundGeolocation.stop().then((bg.State state) {
        bg.BackgroundGeolocation.setOdometer(0.0);
        setState(() {
          _enabled = state.enabled;
        });
      });
    }
  }

  void postLocationUpdate(double latitude, double longitude, String UID,
      String OID, Map<String, dynamic> locDetails, Map otherData,
      double accuracy) {
    Map<String, dynamic> userTrack = new Map();
    var formatter = new DateFormat('yyyy-MM-dd');
    String date = formatter.format(DateTime.now());

    userTrack["UID"] = UID;
    userTrack["latlng"] = GeoPoint(latitude, longitude);
    userTrack["time"] = new DateTime.now();
    userTrack["date"] = date;

    if (accuracy != null) {
      userTrack["accuracy"] = accuracy;
    }

    if (locDetails != null) {
      userTrack["activity"] = locDetails;
    }

    if (otherData != null) {
      userTrack["otherData"] = otherData;
    }

    final collRef = Firestore.instance.collection('organizations').document(OID)
        .collection("employees").document(UID)
        .collection("location");
    DocumentReference docReferance = collRef.document(UID)
        .collection(date)
        .document();
    var batch = Firestore.instance.batch();
    batch.setData(docReferance, userTrack);
    batch.commit();
  }


Debug logs: NA

**Comment by christocracy** [comment]
- OS version
- Debug Logs
- See http://dontkillmyapp.com

**Comment by prasenjitpickcel** [comment]
## Your Environment
* Plugin version: 1.0.10
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Vivo 1727
* Flutter info (`flutter doctor`): NA
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
void initLocLib() {
    bg.BackgroundGeolocation.onLocation(_onLocation);
    bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
    bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
    bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
    bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);

    // 2.  Configure the plugin
    bg.BackgroundGeolocation.ready(bg.Config(
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        distanceFilter: 0,
        stopOnTerminate: false,
        startOnBoot: true,
        debug: true,
        enableHeadless: true,
        reset: true,
        foregroundService: true,
        locationUpdateInterval: 30000
    )).then((bg.State state) {
      setState(() {
        _enabled = state.enabled;
        //_isMoving = state.isMoving;
      });
    });
  }

  void _onLocation(bg.Location location) {
    //updating location to firestore
    postLocationUpdate(
        location.coords.latitude,
        location.coords.longitude,
        UID,
        OID,
        null,
        location.toMap(),
        location.coords.accuracy);
  }

  void _onMotionChange(bg.Location location) {
    //updating location to firestore
    postLocationUpdate(
        location.coords.latitude,
        location.coords.longitude,
        UID,
        OID,
        null,
        location.toMap(),
        location.coords.accuracy);
  }
```

## Expected Behavior
Should update location to Firestore database in background

## Actual Behavior
It stops after some time, if we use enable headless true? is it mandatory to register it in main.dart?

## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
I see you've configured `enableHeadless: true,`.  Have you configured your app for [Headless mode](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Android-Headless-Mode)?

Also, provide logs.  See Wiki [Debugging](https://github.com/transistorsoft/flutter_background_geolocation/wiki/Debugging)

**Comment by prasenjitpickcel** [comment]
yes we have configured in the following way:

void headlessTask(bg.HeadlessEvent headlessEvent) async {
  //print('[BackgroundGeolocation HeadlessTask]: $headlessEvent');
  // Implement a 'case' for only those events you're interested in.
  switch(headlessEvent.name) {
    case bg.Event.TERMINATE:
      bg.State state = headlessEvent.event;
      //print('- State: $state');
      break;
    case bg.Event.HEARTBEAT:
      bg.HeartbeatEvent event = headlessEvent.event;
      //print('- HeartbeatEvent: $event');
      break;
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      postLocationUpdate(location.coords.latitude, location.coords.longitude, _UID, OID, null, location.toMap(), location.coords.accuracy);
      print('task.care headless Location: $location');
      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      //print('- Location: $location');
      break;
    case bg.Event.GEOFENCE:
      bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      //print('- GeofenceEvent: $geofenceEvent');
      break;
    case bg.Event.GEOFENCESCHANGE:
      bg.GeofencesChangeEvent event = headlessEvent.event;
      //print('- GeofencesChangeEvent: $event');
      break;
    case bg.Event.SCHEDULE:
      bg.State state = headlessEvent.event;
      //print('- State: $state');
      break;
    case bg.Event.ACTIVITYCHANGE:
      bg.ActivityChangeEvent event = headlessEvent.event;
      //print('ActivityChangeEvent: $event');
      break;
    case bg.Event.HTTP:
      bg.HttpEvent response = headlessEvent.event;
      //print('HttpEvent: $response');
      break;
    case bg.Event.POWERSAVECHANGE:
      bool enabled = headlessEvent.event;
      //print('ProviderChangeEvent: $enabled');
      break;
    case bg.Event.CONNECTIVITYCHANGE:
      bg.ConnectivityChangeEvent event = headlessEvent.event;
      //print('ConnectivityChangeEvent: $event');
      break;
    case bg.Event.ENABLEDCHANGE:
      bool enabled = headlessEvent.event;
      //print('EnabledChangeEvent: $enabled');
      break;
  }
}


**Starting the service with the following line in main:**
bg.BackgroundGeolocation.registerHeadlessTask(headlessTask);

Do we need the to send the the location from here to our database? And also we don't get the trigger in the above switch case

**Comment by prasenjitpickcel** [comment]
And also do we need to register headless if we want to send location in background on new location event ?

**Comment by christocracy** [comment]
>do we need to register headless if we want to send location in background on new location event

There are 3 states for an Android app.
- Foreground
- Background
- Terminated.

The Headless-task operates in the *terminated* state only.

**Comment by prasenjitpickcel** [comment]
when we register a headless task in main.dart as shown above and we try to start the service it crashes it the following error :

Could not dispatch event: class com.transistorsoft.locationmanager.event.HeadlessEvent to subscribing class class com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask
    java.lang.IllegalStateException: registrar.activity() must not be null
        at com.example.flutterplacesdialog.FlutterPlacesDialogPlugin$Companion.registerWith(FlutterPlacesDialogPlugin.kt:26)
        at com.example.flutterplacesdialog.FlutterPlacesDialogPlugin.registerWith(Unknown Source:2)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:50)
        at com.pickcel.taskmanagement.Application.registerWith(Application.java:19)
        at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.initFlutterView(HeadlessTask.java:189)
        at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.onHeadlessEvent(HeadlessTask.java:107)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:420)
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.e(Unknown Source:66)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:295)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:15)
        at com.transistorsoft.locationmanager.scheduler.ScheduleEvent.onOneShot(Unknown Source:30)
        at com.transistorsoft.locationmanager.scheduler.ScheduleJobService.onStartJob(Unknown Source:38)
        at android.app.job.JobService$1.onStartJob(JobService.java:71)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6679)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

**Comment by christocracy** [comment]
Most Flutter plugins were not designed with Headless operation in mind.  Your app is crashing due to a 3rd-party plugin called [flutter_places_dialog](https://github.com/pinkfish/flutter_places_dialog)
```
com.example.flutterplacesdialog.FlutterPlacesDialogPlugin$Companion.registerWith(FlutterPlacesDialogPlugin.kt:26)
```
It's crashing [at flutter_places_dialog here](https://github.com/pinkfish/flutter_places_dialog/blob/master/android/src/main/kotlin/com/example/flutterplacesdialog/FlutterPlacesDialogPlugin.kt#L26).

This plugin is assuming that `registrar.activity()` always exists.  This is not true in the Headless context, since headless *means* there's no activity.

Like many other plugins, this one needs to first check `registrar.activity() != null` before referencing it.

```diff
+if (registrar.activity() != null) {  // <-- no Activity in Headless context.
    var plugin = FlutterPlacesDialogPlugin(activity = registrar.activity())
     channel.setMethodCallHandler(plugin)
     registrar.addActivityResultListener(plugin)
+}
```

See #96

**Comment by prasenjitpickcel** [comment]
we are trying to send location on new loc found in our firebase database, but it stops sometime, is it recommended to use the url parameter to send location ?

**Comment by christocracy** [comment]
I’m not sure what you mean.  Show me code.

**Comment by prasenjitpickcel** [comment]
void initLocLib(String UID, String OID, bool isStart) {

  bg.BackgroundGeolocation.onLocation((bg.Location location) {
    String oid = location.extras.containsKey("oid") ? location.extras["oid"] : null;
    String uid = location.extras.containsKey("uid") ? location.extras["uid"] : null;
    sendtoDb(location, did);
  });

  bg.BackgroundGeolocation.onMotionChange((bg.Location location) {
    String oid = location.extras.containsKey("oid") ? location.extras["oid"] : null;
    String uid = location.extras.containsKey("uid") ? location.extras["uid"] : null;
    sendtoDb(location, did);
 });

  bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
  bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
  bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);

  // 2.  Configure the plugin
  bg.BackgroundGeolocation.ready(bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
      distanceFilter: 0,
      stopOnTerminate: false,
      startOnBoot: true,
      //url : "https://us-central1-taskcaretest2.cloudfunctions.net/orders/saveData/${UID}",
      debug: false,
      enableHeadless: true,
      reset: true,
      autoSync: true,
      batchSync: true,
      foregroundService: true,
      extras: {
        'oid': OID,
        'uid': UID
      },
      locationUpdateInterval: 15000
  )).then((bg.State state) {
    if(isStart == true) {
      if (state.enabled == false) {
        _onClickEnable(true);
      }
    } else {
      _onClickEnable(false);
    }
  });
}

void _onClickEnable(enabled) {
  if (enabled) {
    bg.BackgroundGeolocation.start().then((bg.State state) {
      //_startService();
    });
  } else {
    bg.BackgroundGeolocation.stop().then((bg.State state) {
      bg.BackgroundGeolocation.setOdometer(0.0);
      //_stopService();
    });
  }
}

**Comment by christocracy** [comment]
If you're submitting to Firebase, have you tried the [background_geolocation_firebase](https://github.com/transistorsoft/flutter_background_geolocation_firebase) companion plugin?
