### ISSUE TITLE
Location not getting in background [ after app termination ]

### ISSUE THREAD

**Issue by chirag-chopra** [transistorsoft/flutter_background_geolocation#900]
## Your Environment
* Plugin version: 4.8.5
* Platform: Android
* OS version:
* Device manufacturer / model: Motorola G22
* Flutter info (`flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
MAIN.DART

/// Receive events from BackgroundGeolocation in Headless state.
@pragma('vm:entry-point')
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  print('📬 --> $headlessEvent');

  switch (headlessEvent.name) {
    case bg.Event.BOOT:
      bg.State state = await bg.BackgroundGeolocation.state;
      print("📬 didDeviceReboot: ${state.didDeviceReboot}");
      break;
    case bg.Event.TERMINATE:
      try {
        bg.Location location =
            await bg.BackgroundGeolocation.getCurrentPosition(
                samples: 1, extras: {"event": "terminate", "headless": true});
        sendDataToServer();
        print("[getCurrentPosition] Headless: $location");
      } catch (error) {
        print("[getCurrentPosition] Headless ERROR: $error");
      }

      break;
    case bg.Event.HEARTBEAT:
      sendDataToServer();
      /* DISABLED getCurrentPosition on heartbeat
      try {
        bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(
          samples: 1,
          extras: {
            "event": "heartbeat",
            "headless": true
          }
        );
        print('[getCurrentPosition] Headless: $location');
      } catch (error) {
        print('[getCurrentPosition] Headless ERROR: $error');
      }
      */
      break;
    case bg.Event.LOCATION:
      bg.Location location = headlessEvent.event;
      print(location);
      break;
    case bg.Event.MOTIONCHANGE:
      bg.Location location = headlessEvent.event;
      sendDataToServer();
      print(location);
      break;
    case bg.Event.GEOFENCE:
      bg.GeofenceEvent geofenceEvent = headlessEvent.event;
      print(geofenceEvent);
      break;
    case bg.Event.GEOFENCESCHANGE:
      bg.GeofencesChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.SCHEDULE:
      bg.State state = headlessEvent.event;
      print(state);
      break;
    case bg.Event.ACTIVITYCHANGE:
      bg.ActivityChangeEvent event = headlessEvent.event;
      sendDataToServer();
      print(event);
      break;
    case bg.Event.HTTP:
      bg.HttpEvent response = headlessEvent.event;
      print(response);
      break;
    case bg.Event.POWERSAVECHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.CONNECTIVITYCHANGE:
      bg.ConnectivityChangeEvent event = headlessEvent.event;
      print(event);
      break;
    case bg.Event.ENABLEDCHANGE:
      bool enabled = headlessEvent.event;
      print(enabled);
      break;
    case bg.Event.AUTHORIZATION:
      bg.AuthorizationEvent event = headlessEvent.event;
      print(event);
      // bg.BackgroundGeolocation.setConfig(
      //     bg.Config(url: "${ENV.TRACKER_HOST}/api/locations"));
      break;
  }
}

/// Receive events from BackgroundFetch in Headless state.
@pragma('vm:entry-point')
void backgroundFetchHeadlessTask(HeadlessTask task) async {
  String taskId = task.taskId;

  // Is this a background_fetch timeout event?  If so, simply #finish and bail-out.
  if (task.timeout) {
    print("[BackgroundFetch] HeadlessTask TIMEOUT: $taskId");
    BackgroundFetch.finish(taskId);
    return;
  }

  print("[BackgroundFetch] HeadlessTask: $taskId");

  try {
    var location = await bg.BackgroundGeolocation.getCurrentPosition(
        samples: 1, extras: {"event": "background-fetch", "headless": true});
    print("[location] $location");
  } catch (error) {
    print("[location] ERROR: $error");
  }

  BackgroundFetch.finish(taskId);
}

```

```
TRACKER.dart


  void _onLocation(bg.Location location) {
    print('[${bg.Event.LOCATION}] - $location');
  }

  void _onLocationError(bg.LocationError error) {
    print('[${bg.Event.LOCATION}] ERROR - $error');
  }

  void _onMotionChange(bg.Location location) {
    print('[${bg.Event.MOTIONCHANGE}] - $location');
  }

  void _onActivityChange(bg.ActivityChangeEvent event) {
    print('[${bg.Event.ACTIVITYCHANGE}] - $event');
  }

  void _onProviderChange(bg.ProviderChangeEvent event) async {
    print('[${bg.Event.PROVIDERCHANGE}] - $event');

    if ((event.status == bg.ProviderChangeEvent.AUTHORIZATION_STATUS_ALWAYS) &&
        (event.accuracyAuthorization ==
            bg.ProviderChangeEvent.ACCURACY_AUTHORIZATION_REDUCED)) {
      // Supply "Purpose" key from Info.plist as 1st argument.
      bg.BackgroundGeolocation.requestTemporaryFullAccuracy("DemoPurpose")
          .then((int accuracyAuthorization) {
        if (accuracyAuthorization ==
            bg.ProviderChangeEvent.ACCURACY_AUTHORIZATION_FULL) {
          print(
              "[requestTemporaryFullAccuracy] GRANTED:  $accuracyAuthorization");
        } else {
          print(
              "[requestTemporaryFullAccuracy] DENIED:  $accuracyAuthorization");
        }
      }).catchError((error) {
        print("[requestTemporaryFullAccuracy] FAILED TO SHOW DIALOG: $error");
      });
    }
  }

  void _onHeartbeat(bg.HeartbeatEvent event) {
    print('[${bg.Event.HEARTBEAT}] -JOKER I HIGH- $event');
    sendDataToServer();
  }

  void _onSchedule(bg.State state) {
    print('[${bg.Event.SCHEDULE}] - $state');
  }

  void _onNotificationAction(String action) {
    print('[onNotificationAction] $action');
    switch (action) {
      case 'notificationButtonFoo':
        bg.BackgroundGeolocation.changePace(false);
        break;
      case 'notificationButtonBar':
        break;
    }
  }

  void _configureBackgroundGeolocation() async {
    // 1.  Listen to events (See docs for all 13 available events).
    bg.BackgroundGeolocation.onLocation(_onLocation, _onLocationError);
    bg.BackgroundGeolocation.onMotionChange(_onMotionChange);
    bg.BackgroundGeolocation.onActivityChange(_onActivityChange);
    bg.BackgroundGeolocation.onProviderChange(_onProviderChange);
    // bg.BackgroundGeolocation.onHttp(_onHttp);
    // bg.BackgroundGeolocation.onConnectivityChange(_onConnectivityChange);
    bg.BackgroundGeolocation.onHeartbeat(_onHeartbeat);
    // bg.BackgroundGeolocation.onGeofence(_onGeofence);
    bg.BackgroundGeolocation.onSchedule(_onSchedule);
    // bg.BackgroundGeolocation.onPowerSaveChange(_onPowerSaveChange);
    // bg.BackgroundGeolocation.onEnabledChange(_onEnabledChange);
    bg.BackgroundGeolocation.onNotificationAction(_onNotificationAction);

    // bg.TransistorAuthorizationToken token =
    //     await bg.TransistorAuthorizationToken.findOrCreate(
    //         orgname, username, ENV.TRACKER_HOST);

    // 2.  Configure the plugin
    bg.BackgroundGeolocation.ready(bg.Config(
            reset:
                false, // <-- lets the Settings screen drive the config rather than re-applying each boot.
            // Convenience option to automatically configure the SDK to post to Transistor Demo server.
            // transistorAuthorizationToken: token,
            // Logging & Debug
            debug: true,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE,
            // Geolocation options
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 500.0,
            // Activity recognition options
            stopTimeout: 5,
            backgroundPermissionRationale: bg.PermissionRationale(
                title:
                    "Allow {applicationName} to access this device's location even when the app is closed or not in use.",
                message:
                    "This app collects location data to enable recording your trips to work and calculate distance-travelled.",
                positiveAction: 'Change to "{backgroundPermissionOptionLabel}"',
                negativeAction: 'Cancel'),
            // HTTP & Persistence
            autoSync: false,
            // Application options
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true,
            heartbeatInterval: 60))
        .then((bg.State state) async {
      print('[ready] ${state.toMap()}');
      print('[didDeviceReboot] ${state.didDeviceReboot}');
      if (state.schedule!.isNotEmpty) {
        bg.BackgroundGeolocation.startSchedule();
      }
      // setState(() {
      //   _enabled = state.enabled;
      //   _isMoving = state.isMoving;
      // });
    }).catchError((error) {
      print('[ready] ERROR: $error');
    });

    // Fetch currently selected tab.
    // SharedPreferences prefs = await _prefs;
    // int tabIndex = prefs.getInt("tabIndex");

    // Which tab to view?  MapView || EventList.   Must wait until after build before switching tab or bad things happen.
    // WidgetsBinding.instance.addPostFrameCallback((_) {
    //   if (tabIndex != null) {
    //     _tabController.animateTo(tabIndex);
    //   }
    // });
  }

// Configure BackgroundFetch (not required by BackgroundGeolocation).
  void _configureBackgroundFetch() async {
    BackgroundFetch.configure(
        BackgroundFetchConfig(
            minimumFetchInterval: 15,
            startOnBoot: true,
            stopOnTerminate: false,
            enableHeadless: true,
            requiresStorageNotLow: false,
            requiresBatteryNotLow: false,
            requiresCharging: false,
            requiresDeviceIdle: false,
            requiredNetworkType: NetworkType.NONE), (String taskId) async {
      print("[BackgroundFetch] received event $taskId");

      SharedPreferences prefs = await SharedPreferences.getInstance();
      int count = 0;
      if (prefs.get("fetch-count") != null) {
        // count = prefs.getInt("fetch-count");
      }
      prefs.setInt("fetch-count", ++count);
      print('[BackgroundFetch] count: $count');

      if (taskId == 'flutter_background_fetch') {
        try {
          // Fetch current position
          var location = await bg.BackgroundGeolocation.getCurrentPosition(
              samples: 1,
              extras: {"event": "background-fetch", "headless": false});
          print("[location] $location");
          sendDataToServer();
        } catch (error) {
          print("[location] ERROR: $error");
        }

        // Test scheduling a custom-task in fetch event.
        BackgroundFetch.scheduleTask(TaskConfig(
            taskId: "com.transistorsoft.customtask",
            delay: 5000,
            periodic: false,
            forceAlarmManager: true,
            stopOnTerminate: false,
            enableHeadless: true));
      }
      BackgroundFetch.finish(taskId);
    });
  }

  // background services
  @override
  void onInit() {
    _configureBackgroundGeolocation();
    _configureBackgroundFetch();

    super.onInit();
  }
```

I am triggering this while app starts. It's is getx controller
## Expected Behavior
App should trigger callback after app gets terminated and foreground at 15 min periodic intervals. 

## Actual Behavior
App is not working in foreground as well as background. It's only working when is open
App is making sound but, callback is not getting triggered

## Steps to Reproduce

1.
2.
3.
4.

## Context
I am trying to make an app that takes user's current location and send that location details to server in background, foreground and while app open.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> reset: false

do you know what this does?  If you don’t know exactly what this does, don’t use it.

**Comment by chirag-chopra** [comment]
When app is in open state
```
I/flutter ( 7127): [location] - [Location {odometer: 0.0, activity: {confidence: 100, type: still}, extras: {headless: true, event: background-fetch}, battery: {level: 0.86, is_charging: false}, uuid: cb409884-0078-4c37-82c7-dd18c8c7d696, coords: {altitude: 189.2, heading: -1.0, latitude: 28.6395565, accuracy: 11.4, heading_accuracy: -1.0, altitude_accuracy: 1.0, speed_accuracy: -1.0, speed: 0.02, longitude: 77.1782293, ellipsoidal_altitude: 189.2}, is_moving: false, timestamp: 2022-12-16T14:04:53.035Z}]
I/flutter ( 7127): FINAL FIRST PAYLOAD  :  ==> {device_id: deviceID, locationtime: 2022-12-16T19:34:53.139481, latitude: 28.6395565, longitude: 77.1782293, address: 35/8, Rajinder Nagar, Shankar Road, New Delhi, 110060, Delhi, India, createdat: 2022-12-16T19:34:53.140445, activity_Type: still, activity_confidence: 100, battery_Level: 0.86, battery_is_charging: false, is_Moving: false, mocklocation: false, speed: 0.02, accuracy: 11.4, speed_Accuracy: -1.0, heading: -1.0, heading_Accuracy: -1.0, altitude: 189.2, altitude_Accuracy: 1.0, odometer: 0.0}
I/flutter ( 7127): SERVER STATUS CODE : 200
I/flutter ( 7127): FINAL PAYLOAD  :  ==> {device_id: deviceID, locationtime: 2022-12-16T19:34:53.139481, latitude: 28.6395565, longitude: 77.1782293, address: 35/8, Rajinder Nagar, Shankar Road, New Delhi, 110060, Delhi, India, createdat: 2022-12-16T19:34:53.140445, activity_Type: still, activity_confidence: 100, battery_Level: 0.86, battery_is_charging: false, is_Moving: false, mocklocation: false, speed: 0.02, accuracy: 11.4, speed_Accuracy: -1.0, heading: -1.0, heading_Accuracy: -1.0, altitude: 189.2, altitude_Accuracy: 1.0, odometer: 0.0}
I/flutter ( 7127): LOCATION UPDATED SUCCESSFULLY TO SERVER==============>



When app is in Background state
...
D/FlutterGeolocator( 7798): Creating service.
D/FlutterGeolocator( 7798): Binding to location service.
D/FlutterGeolocator( 7798): Geolocator foreground service connected
D/FlutterGeolocator( 7798): Initializing Geolocator services
D/FlutterGeolocator( 7798): Flutter engine connected. Connected engine count 1
I/flutter ( 7798): The Dart VM service is listening on http://127.0.0.1:41595/bSYd_lafSGw=/
I/flutter ( 7798): 📬 --> [HeadlessEvent name: connectivitychange, event: [ConnectivityChangeEvent connected: true]]
I/flutter ( 7798): [ConnectivityChangeEvent connected: true]
I/flutter ( 7798): 📬 --> [HeadlessEvent name: providerchange, event: [ProviderChangeEvent enabled:true, status: 3, network: true, gps: true, accuracyAuthorization: 0]]
I/flutter ( 7798): 📬 --> [HeadlessEvent name: terminate, event: [State enabled: true, isMoving: false, trackingMode: 1, desiredAccuracy: -2, distanceFilter: 500.0, odometer: 0.0, schedulerEnabled: false, foregroundService: true]]
I/flutter ( 7798): ---------------------SENDING DATA TO SERVER--------------------
I/flutter ( 7798): [getCurrentPosition] Headless: [Location {odometer: 0.0, activity: {confidence: 100, type: still}, extras: {headless: true, event: terminate}, battery: {level: 0.86, is_charging: false}, uuid: 12ef3f98-5521-4619-96ca-5a7ff85a33da, coords: {altitude: 189.2, heading: -1.0, latitude: 28.6395493, accuracy: 18.6, heading_accuracy: -1.0, altitude_accuracy: 1.0, speed_accuracy: -1.0, speed: -1.0, longitude: 77.1782083, ellipsoidal_altitude: 189.2}, is_moving: false, timestamp: 2022-12-16T14:05:10.934Z}]
I/flutter ( 7798): 📬 --> [HeadlessEvent name: location, event: [Location {is_moving: false, uuid: 12ef3f98-5521-4619-96ca-5a7ff85a33da, timestamp: 2022-12-16T14:05:10.934Z, odometer: 0, coords: {latitude: 28.6395493, longitude: 77.1782083, accuracy: 18.6, speed: -1, speed_accuracy: -1, heading: -1, heading_accuracy: -1, altitude: 189.2, ellipsoidal_altitude: 189.2, altitude_accuracy: 1}, activity: {type: still, confidence: 100}, battery: {is_charging: false, level: 0.86}, extras: {headless: true, event: terminate}}]]
I/flutter ( 7798): [Location {is_moving: false, uuid: 12ef3f98-5521-4619-96ca-5a7ff85a33da, timestamp: 2022-12-16T14:05:10.934Z, odometer: 0, coords: {latitude: 28.6395493, longitude: 77.1782083, accuracy: 18.6, speed: -1, speed_accuracy: -1, heading: -1, heading_accuracy: -1, altitude: 189.2, ellipsoidal_altitude: 189.2, altitude_accuracy: 1}, activity: {type: still, confidence: 100}, battery: {is_charging: false, level: 0.86}, extras: {headless: true, event: terminate}}]
I/flutter ( 7798): 📬 --> [HeadlessEvent name: location, event: [Location {is_moving: false, uuid: 8ea52f94-582d-4587-a616-2cc472ec40a0, timestamp: 2022-12-16T14:05:11.756Z, odometer: 0, coords: {latitude: 28.639549, longitude: 77.1782245, accuracy: 14.9, speed: 0.09, speed_accuracy: -1, heading: -1, heading_accuracy: -1, altitude: 189.2, ellipsoidal_altitude: 189.2, altitude_accuracy: 1}, activity: {type: still, confidence: 100}, battery: {is_charging: false, level: 0.86}, extras: {headless: true, event: background-fetch}}]]
I/flutter ( 7798): [Location {is_moving: false, uuid: 8ea52f94-582d-4587-a616-2cc472ec40a0, timestamp: 2022-12-16T14:05:11.756Z, odometer: 0, coords: {latitude: 28.639549, longitude: 77.1782245, accuracy: 14.9, speed: 0.09, speed_accuracy: -1, heading: -1, heading_accuracy: -1, altitude: 189.2, ellipsoidal_altitude: 189.2, altitude_accuracy: 1}, activity: {type: still, confidence: 100}, battery: {is_charging: false, level: 0.86}, extras: {headless: true, event: background-fetch}}]
I/flutter ( 7798): FINAL FIRST PAYLOAD  :  ==> {device_id: deviceID, locationtime: 2022-12-16T19:35:11.914293, latitude: 28.639549, longitude: 77.1782245, address: 35/8, Rajinder Nagar, Shankar Road, New Delhi, 110060, Delhi, India, createdat: 2022-12-16T19:35:11.946490, activity_Type: still, activity_confidence: 100, battery_Level: 0.86, battery_is_charging: false, is_Moving: false, mocklocation: false, speed: 0.09, accuracy: 14.9, speed_Accuracy: -1.0, heading: -1.0, heading_Accuracy: -1.0, altitude: 189.2, altitude_Accuracy: 1.0, odometer: 0.0}
E/flutter ( 7798): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 7798): #0      authHeader (package:example/common/constants.dart:23:35)
E/flutter ( 7798): #1      authHeader (package:example/common/constants.dart)
E/flutter ( 7798): #2      sendDataToServer (package:example/main.dart:83:45)
E/flutter ( 7798): <asynchronous suspension>
E/flutter ( 7798):
```
We tried with static tokan 
Removed reset parameter as per your suggestion 

Request working when app is active on screen but same request not working in background [ app will terminated ]

**Comment by christocracy** [comment]
Why don't you investigate that error reported **from you own code**?

```
E/flutter ( 7798): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 7798): #0      authHeader (package:example/common/constants.dart:23:35)
E/flutter ( 7798): #1      authHeader (package:example/common/constants.dart)
E/flutter ( 7798): #2      sendDataToServer (package:example/main.dart:83:45)
```

**Comment by adn9990** [comment]
@christocracy  Same code is working when app sends location in active state, and it's get stopped when it sends location update in background state
Already checked code

**Comment by christocracy** [comment]
That error is reported from **your own code**.  It is not an error from the plugin.

I cannot help you with errors in your own code.

**Comment by adn9990** [comment]
@christocracy is there any condition in which some piece of code or token not works in background, We already tried with static token because error was from AUTH header where token was provided

**Comment by christocracy** [comment]
You don’t seem to be using the plugins built in http service so manually performing your own http requests.
