### ISSUE TITLE
Service Location started after 1+ minute after moving

### ISSUE THREAD

**Issue by vitaliy-anatolievych** [transistorsoft/flutter_background_geolocation#930]
## Your Environment
* Plugin version:  '^4.8.1'
* Platform: Android
* OS version: API 26+ 
* Device manufacturer / model: any
* Flutter info (`flutter doctor`): 
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2486], locale uk-UA)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.3)
[!] Android Studio (version 2022.2)
    X Unable to find bundled Java version.
[√] IntelliJ IDEA Community Edition (version 2022.1)
[√] VS Code (version 1.74.3)
[√] Connected device (3 available)    
[√] HTTP Host Availability

* Plugin config:
```
    bg.BackgroundGeolocation.ready(bg.Config(
            notification: bg.Notification(
              title: "Name App",
              text: "Location is working"
            ),
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 1.0,
            stopOnTerminate: true,
            startOnBoot: false,
            debug: false,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE))
        .then((bg.State state) {
      if (!state.enabled) {
        ////
        // 3.  Start the plugin.
        //
        bg.BackgroundGeolocation.start();
      }
    });
```

## Expected Behavior
I want the location service to work always after launching.

## Actual Behavior
After the user starts moving, the service responds and starts after a minute or a minute and a half.

## Steps to Reproduce

1. 
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
https://mechanic-app.ru/log.html
```

</details>

PLEASE WATCH VIDEO!!
https://youtu.be/0y7BZPnVZog

**Comment by christocracy** [comment]
If you wish to manually toggle the plugin into the *moving* state. See api docs for method `.changePace`

**Comment by vitaliy-anatolievych** [comment]
i added this, and this is not solve my problem!

**watch video!**
https://youtu.be/HZqJTy8UEQ0

**HOW FIX THIS?!**

* Plugin config:
```
    bg.BackgroundGeolocation.changePace(true);
    bg.BackgroundGeolocation.ready(bg.Config(
            notification: bg.Notification(
              title: "Name App",
              text: "Location is working"
            ),
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: 1.0,
            stopOnTerminate: true,
            startOnBoot: false,
            debug: false,
            logLevel: bg.Config.LOG_LEVEL_VERBOSE))
        .then((bg.State state) {
      if (!state.enabled) {
        ////
        // 3.  Start the plugin.
        //
        bg.BackgroundGeolocation.start();
      }
    });
```

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
https://mechanic-app.ru/log.html
```
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:51537/SgN0XIChj-s=/
D/TSLocationManager( 4825): [c.t.f.b.streams.StreamHandler onListen] location
D/TSLocationManager( 4825): [c.t.f.b.streams.StreamHandler onListen] motionchange  
D/TSLocationManager( 4825): [c.t.f.b.streams.StreamHandler onListen] providerchange
D/TSLocationManager( 4825): [c.t.l.adapter.TSConfig d] ℹ️   Persist config, dirty: [desiredAccuracy, distanceFilter, extras, headers,
 headlessJobService, logLevel, notification, notification.title, notification.text, params, schedule]
D/TSLocationManager( 4825): [c.t.l.adapter.TSConfig d] ℹ️   Persist config, dirty: [desiredAccuracy, distanceFilter, headlessJobServi
ce, logLevel, notification, notification.title, notification.text]
W/Settings( 4825): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
W/Settings( 4825): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
E/flutter ( 4825): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid radix-10 number (at character 1)
E/flutter ( 4825): BackgroundGeolocation is disabled
E/flutter ( 4825): ^
E/flutter ( 4825):
E/flutter ( 4825): #0      int._handleFormatError (dart:core-patch/integers_patch.dart:131:5)
E/flutter ( 4825): #1      int._parseRadix (dart:core-patch/integers_patch.dart:157:16)
E/flutter ( 4825): #2      int._parse (dart:core-patch/integers_patch.dart:103:12)
E/flutter ( 4825): #3      int.parse (dart:core-patch/integers_patch.dart:65:12)
E/flutter ( 4825): #4      new Error (package:flutter_background_geolocation/models/error.dart:11:16)
E/flutter ( 4825): #5      BackgroundGeolocation.changePace (package:flutter_background_geolocation/models/background_geolocation.dart:432:13)
E/flutter ( 4825): <asynchronous suspension>
E/flutter ( 4825):
D/TSLocationManager( 4825): [c.t.locationmanager.util.c g]
D/TSLocationManager( 4825):   ℹ️  LocationAuthorization: Permission granted
I/TSLocationManager( 4825): - Enable: false → true, trackingMode: 1
I/flutter ( 4825): [providerChange] - [ProviderChangeEvent enabled:true, status: 3, network: true, gps: true, accuracyAuthorization: 
0]
The Flutter DevTools debugger and profiler on Android SDK built for x86 is available at:
http://127.0.0.1:9103?uri=http://127.0.0.1:51537/SgN0XIChj-s=/
D/eglCodecCommon( 4825): setVertexArrayObject: set vao to 0 (0) 1 0
D/TSLocationManager( 4825): [c.t.l.http.HttpService startMonitoringConnectivityChanges] 
D/TSLocationManager( 4825):   🎾  Start monitoring connectivity changes
D/TSLocationManager( 4825): [c.t.l.device.DeviceSettings startMonitoringPowerSaveChanges]
D/TSLocationManager( 4825):   🎾  Start monitoring powersave changes
I/TSLocationManager( 4825): [c.t.l.service.HeartbeatService stop] 
I/TSLocationManager( 4825):   🔴  Stop heartbeat
D/EGL_emulation( 4825): eglMakeCurrent: 0xdad1a120: ver 2 0 (tinfo 0xc0871460)
D/eglCodecCommon( 4825): setVertexArrayObject: set vao to 0 (0) 1 0
W/Settings( 4825): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/TSLocationManager( 4825): [c.t.locationmanager.util.c h]
D/TSLocationManager( 4825):   ℹ️  LocationAuthorization: Permission granted
I/TSLocationManager( 4825): [c.t.l.service.TrackingService changePace]
I/TSLocationManager( 4825):   🔵  setPace: false → false
D/TSLocationManager( 4825): [c.t.l.http.HttpService a]
D/TSLocationManager( 4825): ╔═════════════════════════════════════════════
D/TSLocationManager( 4825): ║ 📶  Connectivity change: connected? true
D/TSLocationManager( 4825): ╠═════════════════════════════════════════════
D/EGL_emulation( 4825): eglMakeCurrent: 0xdad1a120: ver 2 0 (tinfo 0xc0871460)
D/TSLocationManager( 4825): [c.t.l.service.AbstractService start] 
D/TSLocationManager( 4825):   🎾  LocationRequestService [eventCount: 1]
I/TSLocationManager( 4825): [c.t.l.l.SingleLocationRequest startUpdatingLocation]
I/TSLocationManager( 4825):   🔵  [SingleLocationRequest start, action: 1, requestId: 1]
W/ActivityThread( 4825): handleWindowVisibility: no activity for token android.os.BinderProxy@8445820
I/TSLocationManager( 4825): [c.t.l.s.ActivityRecognitionService start] 
I/TSLocationManager( 4825):   🎾  Start motion-activity updates
D/TSLocationManager( 4825): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]  
D/TSLocationManager( 4825): [c.t.l.a.TSLocationManagerActivity execute] locationsettings
D/TSLocationManager( 4825): [c.t.l.adapter.TSConfig translateDesiredAccuracy] translateDesiredAccuracy (true): -1
W/aradze.gtm_clu( 4825): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/aradze.gtm_clu( 4825): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/TSLocationManager( 4825): [c.t.l.a.TSLocationManagerActivity$b onComplete] 
D/TSLocationManager( 4825):   ℹ️  Location Settings Resolution: START
D/TSLocationManager( 4825): [c.t.l.a.TSLocationManagerActivity onActivityResult] 
D/TSLocationManager( 4825):   ✅  Location settings resolution: ACCEPTED
D/TSLocationManager( 4825): [c.t.l.a.TSLocationManagerActivity stop] eventCount: 0
I/TSLocationManager( 4825): [c.t.l.s.TSScheduleManager oneShot] 
I/TSLocationManager( 4825):   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
D/TSLocationManager( 4825): [c.t.l.a.TSLocationManagerActivity onDestroy] 
I/TSLocationManager( 4825): [c.t.l.s.TSScheduleManager cancelOneShot] 
I/TSLocationManager( 4825):   ⏰ Cancel OneShot: TERMINATE_EVENT
D/TSLocationManager( 4825): [c.t.l.service.AbstractService start] 
D/TSLocationManager( 4825):   🎾  ActivityRecognitionService [eventCount: 1]
D/TSLocationManager( 4825): [c.t.l.s.ActivityRecognitionService handleActivityRecognitionResult]
D/TSLocationManager( 4825):   🚘 ️DetectedActivity [type=STILL, confidence=100]
D/TSLocationManager( 4825): [c.t.l.service.AbstractService finish] ⚙️︎  finish ActivityRecognitionService [eventCount: 0, sticky: fal
se]
D/TSLocationManager( 4825): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager( 4825):   🔴  ActivityRecognitionService stopped
D/EGL_emulation( 4825): eglMakeCurrent: 0xdad1a120: ver 2 0 (tinfo 0xc0871460)
I/TSLocationManager( 4825): [c.t.l.s.TSScheduleManager oneShot] 
I/TSLocationManager( 4825):   ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
D/TSLocationManager( 4825): [c.t.l.l.LifecycleManager onPause] ☯️  onPause
D/TSLocationManager( 4825): [c.t.l.l.LifecycleManager onStop] ☯️  onStop
W/Settings( 4825): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/TSLocationManager( 4825): [c.t.l.service.TrackingService changePace] 
D/TSLocationManager( 4825):   ⚠️  Waiting for existing motionchange request #1 to complete
D/TSLocationManager( 4825): [c.t.locationmanager.util.c h]
D/TSLocationManager( 4825):   ℹ️  LocationAuthorization: Permission granted
I/TSLocationManager( 4825): [c.t.l.p.TSProviderManager handleProviderChangeEvent] 
I/TSLocationManager( 4825): ╔═════════════════════════════════════════════
I/TSLocationManager( 4825): ║ Location-provider change: true
I/TSLocationManager( 4825): ╠═════════════════════════════════════════════
I/TSLocationManager( 4825): ╟─ GPS: false
I/TSLocationManager( 4825): ╟─ Network: true
I/TSLocationManager( 4825): ╟─ AP Mode: false
I/flutter ( 4825): [providerChange] - [ProviderChangeEvent enabled:true, status: 3, network: true, gps: false, accuracyAuthorization: 0]
D/TSLocationManager( 4825): [c.t.l.service.AbstractService start] 
D/TSLocationManager( 4825):   🎾  LocationRequestService [eventCount: 1]
I/TSLocationManager( 4825): [c.t.l.l.SingleLocationRequest startUpdatingLocation] 
I/TSLocationManager( 4825):   🔵  [SingleLocationRequest start, action: 3, requestId: 2]
D/TSLocationManager( 4825): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
D/TSLocationManager( 4825): [c.t.l.service.AbstractService start] 
D/TSLocationManager( 4825):   🎾  LocationRequestService [eventCount: 1]
I/TSLocationManager( 4825): [c.t.l.s.LocationRequestService handleLocationResult]
I/TSLocationManager( 4825): ╔═════════════════════════════════════════════
I/TSLocationManager( 4825): ║ motionchange LocationResult: 1
I/TSLocationManager( 4825): ╠═════════════════════════════════════════════
I/TSLocationManager( 4825): ╟─ 📍  Location[gps 47,304762,31,026082 hAcc=10 et=+1h19m1s4ms alt=113.25438690185547 vel=2.6078272 bear=213.93073 vAcc=??? sAcc=??? bAcc=??? mock {Bundle[{}]}], age: 189ms, time: 1674762004230
I/TSLocationManager( 4825): [c.t.l.l.TSLocationManager onSingleLocationResult] 
I/TSLocationManager( 4825):   🔵  Acquired motionchange position, isMoving: false
D/TSLocationManager( 4825): [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 10.433925
D/EGL_emulation( 4825): eglMakeCurrent: 0xdad1a120: ver 2 0 (tinfo 0xc0871460)
D/TSLocationManager( 4825): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
D/TSLocationManager( 4825): [c.t.l.s.LocationRequestService handleLocationResult] SingleLocationRequest 1 isFinished? true
D/TSLocationManager( 4825): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false] 
I/TSLocationManager( 4825): [c.t.l.data.sqlite.b persist]
I/TSLocationManager( 4825):   ✅  INSERT: 4c9718f9-3afb-4030-975b-2ba57f3b77fd
D/TSLocationManager( 4825): [c.t.l.g.TSGeofenceManager startMonitoringStationaryRegion] 
D/TSLocationManager( 4825):   🎾  Start monitoring stationary region (radius: 150.0m 47.304762439529085,31.026082185835445 hAcc=10.433925)
D/TSLocationManager( 4825): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager( 4825):   🔴  LocationRequestService stopped
D/TSLocationManager( 4825): [c.t.l.service.AbstractService start] 
D/TSLocationManager( 4825):   🎾  TrackingService [eventCount: 1]
I/TSLocationManager( 4825): [c.t.l.service.TrackingService handleMotionChangeResult]
I/TSLocationManager( 4825): ╔═════════════════════════════════════════════
I/TSLocationManager( 4825): ║ TrackingService motionchange: false
I/TSLocationManager( 4825): ╠═════════════════════════════════════════════
D/TSLocationManager( 4825): [c.t.l.service.AbstractService finish] ⚙️︎  finish TrackingService [eventCount: 0, sticky: false]        
D/TSLocationManager( 4825): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager( 4825):   🔴  TrackingService stopped
D/TSLocationManager( 4825): [c.t.l.service.AbstractService start] 
D/TSLocationManager( 4825):   🎾  LocationRequestService [eventCount: 1]
I/TSLocationManager( 4825): [c.t.l.s.LocationRequestService handleLocationResult]
I/TSLocationManager( 4825): ╔═════════════════════════════════════════════
I/TSLocationManager( 4825): ║ providerchange LocationResult: 2
I/TSLocationManager( 4825): ╠═════════════════════════════════════════════
I/TSLocationManager( 4825): ╟─ 📍  Location[gps 47,304744,31,026070 hAcc=10 et=+1h19m2s8ms alt=113.53631591796875 vel=3.732461 bear=213.77887 vAcc=??? sAcc=??? bAcc=??? mock {Bundle[{}]}], age: 95ms, time: 1674762005234
I/TSLocationManager( 4825): [c.t.l.l.TSLocationManager onSingleLocationResult] 
I/TSLocationManager( 4825):   🔵  Acquired providerchange position
D/TSLocationManager( 4825): [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 10.313124
D/TSLocationManager( 4825): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
D/TSLocationManager( 4825): [c.t.l.service.AbstractService onDestroy] 
D/TSLocationManager( 4825):   🔴  LocationRequestService stopped
D/TSLocationManager( 4825): [c.t.l.s.LocationRequestService handleLocationResult] SingleLocationRequest 2 isFinished? true
D/TSLocationManager( 4825): [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
I/TSLocationManager( 4825): [c.t.l.data.sqlite.b persist]
I/TSLocationManager( 4825):   ✅  INSERT: d38e19d9-f6dc-4229-becd-d86c49df0638
D/TSLocationManager( 4825): [c.t.l.l.TSLocationManager$b onLocation]
D/TSLocationManager( 4825):   ℹ️  Distance from last location: 6043282.5
D/TSLocationManager( 4825): [c.t.l.g.TSGeofenceManager startMonitoringStationaryRegion]
D/TSLocationManager( 4825):   🎾  Start monitoring stationary region (radius: 150.0m 47.30474447606086,31.026070178060806 hAcc=10.192323)
D/EGL_emulation( 4825): eglMakeCurrent: 0xdad1a120: ver 2 0 (tinfo 0xc0871460)
D/TSLocationManager( 4825): [c.t.l.l.LifecycleManager onStart] ☯️  onStart
I/TSLocationManager( 4825): [c.t.l.s.TSScheduleManager cancelOneShot] 
I/TSLocationManager( 4825):   ⏰ Cancel OneShot: TERMINATE_EVENT
D/TSLocationManager( 4825): [c.t.l.l.LifecycleManager onResume] ☯️  onResume
D/EGL_emulation( 4825): eglMakeCurrent: 0xe2e0c580: ver 2 0 (tinfo 0xd7993f10)
D/EGL_emulation( 4825): eglMakeCurrent: 0xe2e0c580: ver 2 0 (tinfo 0xd7993f10)
D/EGL_emulation( 4825): eglMakeCurrent: 0xdad1a120: ver 2 0 (tinfo 0xc0871460)
D/TSLocationManager( 4825): [c.t.l.service.AbstractService start] 
D/TSLocationManager( 4825):   🎾  GeofencingService [eventCount: 1]
D/TSLocationManager( 4825): [c.t.l.adapter.TSConfig d] ℹ️   Persist config, dirty: [isMoving]
I/TSLocationManager( 4825): [c.t.l.service.HeartbeatService stop]
I/TSLocationManager( 4825):   🔴  Stop heartbeat
D/TSLocationManager( 4825): [c.t.l.g.TSGeofenceManager stopMonitoringStationaryRegion]
D/TSLocationManager( 4825):   🔴  Stop monitoring stationary region
D/TSLocationManager( 4825): [c.t.locationmanager.util.c h] 
D/TSLocationManager( 4825):   ℹ️  LocationAuthorization: Permission granted
I/TSLocationManager( 4825): [c.t.l.service.TrackingService changePace]
I/TSLocationManager( 4825):   🔵  setPace: false → true
I/TSLocationManager( 4825): [c.t.l.s.GeofencingService handleStationaryGeofenceExit]
I/TSLocationManager( 4825): ╔═════════════════════════════════════════════
I/TSLocationManager( 4825): ║ GeofencingService: Stationary geofence EXIT
I/TSLocationManager( 4825): ╠═════════════════════════════════════════════
</details>

**Comment by christocracy** [comment]
>HOW FIX THIS?!
>bg.BackgroundGeolocation.changePace(true);

WHY ARE YOU TELLING THE PLUGIN TO ENTER THE *MOVING* STATE BEFORE YOU'VE EVEN TOLD THE PLUGIN TO START?!?!

```dart
await bg.BackgroundGeolocation.start();
await bg.BackgroundGeolocation.changePace(true);
```

If the plugin were an electronic device, like a *Stereo System*:
- `.ready(config)` is like plugging the power cable in.
- `.start() / .stop()` is like the power button.
- `.changePace(true)` is the `[ > ]` button.  `.changePace(false)` is like the `[ || ]` button.

You can't tell your stereo to `[ > ]` (`.changePace(true)` until you turn the power on (`.start()`).

>>i paid for this and this not works normally

Because you're doing it *wrong* and not following directions.

**Comment by christocracy** [comment]
Perhaps you should spend some time playing with the /example app in this repo.

![68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f732f7761343377316e3378686b6a6e30692f686f6d652d6672616d65642d3335302e706e673f646c3d31](https://user-images.githubusercontent.com/14999/214939191-032dae5a-8ba8-405c-b2c2-fb44b2240d5c.png)

**Comment by vitaliy-anatolievych** [comment]
Ok, thanx. This is solve my problem.
But, last question.

How accurately does your service provide the current speed?
My research showed that it is understated by a factor of 1.5 compared to the real one.

**Comment by christocracy** [comment]
not *calculate* speed.  `speed` comes directly from native API.  For *Android*, this is the Java class [`com.android.Location.getSpeed`](https://developer.android.com/reference/android/location/Location#getSpeed()).  Speed comes from GPS.  That plugin does 

The plugin also provides `location.Coords.speedAccuracy` to learn about the accuracy of the returned speed.
