### ISSUE TITLE
FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by miguelflores1993** [transistorsoft/flutter_background_geolocation#937]
* Plugin version: 4.8.5
* Platform: Android
* OS version: 12
* Device manufacturer / model: XIAOMI 11T

I want to use an `awesomecamera` library and the graddle requirement is version `1.7.10`

but it prevents me because the application together with the `flutter_background_geolocation` use `graddle 1.6.21`  ibrary no longer works, the application closes as an error, what could we do?

``` <!-- syntax-highligting:  DO NOT REMOVE -->
E/AndroidRuntime( 3313): FATAL EXCEPTION: main
E/AndroidRuntime( 3313): Process: com.deltaxlat.appdriver.dev, PID: 3313
E/AndroidRuntime( 3313): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gms.location.ActivityRecognitionClient' appears in /data/app/~~ormrqoBzvT3udWou-CEC2g==/com.deltaxlat.appdriver.dev-yP9rUuHd0egpa9ehAF8b0w==/base.apk!classes7.dex)
E/AndroidRuntime( 3313): 	at com.transistorsoft.locationmanager.service.ActivityRecognitionService.start(Unknown Source:84)
E/AndroidRuntime( 3313): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$n0.a(Unknown Source:16)
E/AndroidRuntime( 3313): 	at com.transistorsoft.locationmanager.adapter.TSConfig.b(Unknown Source:32)
E/AndroidRuntime( 3313): 	at com.transistorsoft.locationmanager.adapter.TSConfig.b(Unknown Source:225)
E/AndroidRuntime( 3313): 	at com.transistorsoft.locationmanager.adapter.TSConfig.b(Unknown Source:0)
E/AndroidRuntime( 3313): 	at com.transistorsoft.locationmanager.adapter.TSConfig$Builder.commit(Unknown Source:10)
E/AndroidRuntime( 3313): 	at com.transistorsoft.locationmanager.adapter.TSConfig$Builder.a(Unknown Source:144)
E/AndroidRuntime( 3313): 	at com.transistorsoft.locationmanager.adapter.TSConfig$Builder.b(Unknown Source:0)
E/AndroidRuntime( 3313): 	at com.transistorsoft.locationmanager.adapter.TSConfig.reset(Unknown Source:2)
E/AndroidRuntime( 3313): 	at com.transistorsoft.locationmanager.adapter.TSConfig.reset(Unknown Source:1)
E/AndroidRuntime( 3313): 	at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule.ready(BackgroundGeolocationModule.java:365)
E/AndroidRuntime( 3313): 	at com.transistorsoft.flutter.backgroundgeolocation.BackgroundGeolocationModule.onMethodCall(BackgroundGeolocationModule.java:222)
E/AndroidRuntime( 3313): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime( 3313): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 3313): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime( 3313): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 3313): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 3313): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3313): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 3313): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 3313): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime( 3313): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3313): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 3313): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)E
```

**Comment by christocracy** [comment]
Duplicate #933 

Please search issues before posting.

**Comment by christocracy** [comment]
You'll find this [cameawesome](https://github.com/Apparence-io/CamerAwesome/blame/4022a571693b8639e6b50d131ec499c496e81c78/android/build.gradle#L59) is using a **hard-coded (bad)** `play-services:location:21.0.1`.

They should be exposing a configurable `ext.playServicesLocationVersion` so developers can control the version of that dependency, as *this plugin* has for years.

<img width="1139" alt="Screenshot 2023-01-31 at 8 29 24 AM" src="https://user-images.githubusercontent.com/14999/215773915-c5fd47ea-d3e7-42a2-86bf-ca56c9295fd9.png">

**Comment by christocracy** [comment]
You need to use a previous version of `camerawesome` which imports `play-services-location:20.0.0`

**Comment by christocracy** [comment]
And no, you cannot simply configure `playServicesLocationVersion = "21.0.1" here, since I need to **recompile** the android library `tslocationmanager.aar` against `play-services-location:21.0.1`.

**Comment by christocracy** [comment]
I have a recompiled version supporting v21 due for release today or tomorrow.

The author of camerawesome [contacted me](https://github.com/Baseflow/flutter-geolocator/pull/1202#issuecomment-1410642750) and will soon implement gradle Config var `ext.playServicesLocationVersion`.

**Comment by miguelflores1993** [comment]
Yes dear, they already released a test branch to see this issue, they already solved it.
very nice of you
