### ISSUE TITLE
App crashes on startup with com.transistorsoft.locationmanager.util.LogFileProvider

### ISSUE THREAD

**Issue by joserocha3** [transistorsoft/flutter_background_geolocation#98]
## Your Environment
* Plugin version: 1.0.11
* Platform: Android
* OS version: 19
* Device manufacturer / model: Galaxy Note 3 Duos, Galaxy Tab 3, Moto X
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

• No issues found!
```

* Plugin config:
```dart
 bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      persistMode: bg.Config.PERSIST_MODE_GEOFENCE,
      geofenceProximityRadius: 100000, // about 62 miles
      logLevel: bg.Config.LOG_LEVEL_ERROR,
      stopOnTerminate: false,
      enableHeadless: true,
      startOnBoot: true,
      autoSync: true,
      reset: _reset ?? true,
      // Do not record location event if more than 300 meters/second since last
      // recorded event - Android only, iOS does not allow mock locations on device
      speedJumpFilter: 300,
      foregroundService: true,
      disableLocationAuthorizationAlert: true,
      notification: bg.Notification(
        title: 'Zone Tracker',
        text: 'Search underway',
        channelName: 'Zone Tracker',
        color:
            '#${Constants.colors.primary.value.toRadixString(16).substring(2)}',
        smallIcon: 'drawable/ic_notification',
        largeIcon: 'drawable/ic_notification',
        priority: bg.Config.NOTIFICATION_PRIORITY_MIN,
      ),
    );
```

## Expected Behavior
Should start without crash.

## Actual Behavior
App crashes on start.

## Steps to Reproduce
1. Start app on specified devices.
2. Search for `LogFileProvider` in logcat.

## Context
Run the app on specified devices. This only happens on certain devices.

## Debug logs
[Full logcat](https://www.dropbox.com/s/pp8hcgz7q7xvl9c/logcat.txt?dl=0).
<details>
	<summary>Logs</summary>

```
java.lang.RuntimeException: Unable to get provider com.transistorsoft.locationmanager.util.LogFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.transistorsoft.locationmanager.util.LogFileProvider" on path: DexPathList[[zip file "/data/app/com.dotdotdata.pointbee-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.dotdotdata.pointbee-1, /vendor/lib, /system/lib]]
FATAL EXCEPTION: main
Process: com.dotdotdata.pointbee, PID: 27739
java.lang.RuntimeException: Unable to get provider com.transistorsoft.locationmanager.util.LogFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.transistorsoft.locationmanager.util.LogFileProvider" on path: DexPathList[[zip file "/data/app/com.dotdotdata.pointbee-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.dotdotdata.pointbee-1, /vendor/lib, /system/lib]]
	at android.app.ActivityThread.installProvider(ActivityThread.java:4993)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4585)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4499)
	at android.app.ActivityThread.access$1500(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5293)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.transistorsoft.locationmanager.util.LogFileProvider" on path: DexPathList[[zip file "/data/app/com.dotdotdata.pointbee-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.dotdotdata.pointbee-1, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	at android.app.ActivityThread.installProvider(ActivityThread.java:4978)
```

</details>

**Comment by christocracy** [comment]
It's not only `LogfileProvider` you're having trouble with:

- java.lang.ClassNotFoundException: io.flutter.plugins.firebaseauth.FlutterFirebaseAppRegistrar
- java.lang.NoClassDefFoundError: io/flutter/plugins/firebaseauth/FlutterFirebaseAppRegistrar
- java.lang.ClassNotFoundException: io.flutter.plugins.firebase.core.FlutterFirebaseAppRegistrar

Perhaps you need to enable multidex?

**Comment by joserocha3** [comment]
Thank you for pointing that out. I am using `multiDexEnabled true` in `defaultConfig`, but those tests were run on Android version prior to 21; there is some [extra setup work](https://developer.android.com/studio/build/multidex#mdex-gradle) to get multidex to work for those order versions.
