### ISSUE TITLE
Error while embbed Flutter as aar in native Android App

### ISSUE THREAD

**Issue by developers-lumiplan** [transistorsoft/flutter_background_geolocation#980]
## Your Environment
* Plugin version: 4.9.0
* Platform: Android
* OS version: Tested only on 33 & 31
* Device manufacturer / model: simulator
* Flutter info (`flutter doctor`):
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.0.1 21A559 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2021.3)
[✓] VS Code (version 1.76.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

* Plugin config:
```dart
bg.Config(
            locationAuthorizationRequest: "WhenInUse",
            desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
            distanceFilter: _minDistanceChangeForUpdate,
            locationUpdateInterval: _updateInterval,
            fastestLocationUpdateInterval: _fastestInterval,
            stopOnTerminate: true,
            startOnBoot: false,
            debug: kDebugMode,
            logLevel: kDebugMode
                ? bg.Config.LOG_LEVEL_VERBOSE
                : bg.Config.LOG_LEVEL_WARNING);
```

## Expected Behavior
We have an existing Android native app where we include a flutter module with your plugin, the flutter module launch independently work fine.
We compile it as an aar to include it in our existing application

To be able to compile the app, we have added the following repositories on build.gradle of our native app

```
maven {
    url 'https://raw.githubusercontent.com/transistorsoft/flutter_background_fetch/master/android/libs'
}
maven {
    url 'https://raw.githubusercontent.com/transistorsoft/flutter_background_geolocation/master/android/libs'
}
```

On iOS after a lot of testing, we make it work but we are stuck on Android.

Thank you for your help

## Actual Behavior

The app crash when we start the geolocation

## Debug logs

```
    ╔═════════════════════════════════════════════
    ║ TSLocationManager version: 3.3.1 (418)
    ╠═════════════════════════════════════════════
    ╟─ Google sdk_gphone64_x86_64 @ 12 (flutter)
    {
      "activityRecognitionInterval": 10000,
      "allowIdenticalLocations": false,
      "authorization": {},
      "autoSync": true,
      "autoSyncThreshold": 0,
      "backgroundPermissionRationale": {
        "title": "Allow {applicationName} to access this device's location even when closed or not in use?",
        "message": "[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.",
        "positiveAction": "Change to \"{backgroundPermissionOptionLabel}\"",
        "negativeAction": ""
      },
      "batchSync": false,
      "configUrl": "",
      "debug": true,
      "deferTime": 0,
      "desiredAccuracy": -1,
      "desiredOdometerAccuracy": 100,
      "disableAutoSyncOnCellular": false,
      "disableElasticity": false,
      "disableLocationAuthorizationAlert": false,
      "disableMotionActivityUpdates": false,
      "disableProviderChangeRecord": false,
      "disableStopDetection": false,
      "distanceFilter": 10,
      "elasticityMultiplier": 1,
      "enableHeadless": false,
      "enableTimestampMeta": false,
      "extras": {},
      "fastestLocationUpdateInterval": 1000,
      "foregroundService": true,
      "geofenceInitialTriggerEntry": true,
      "geofenceModeHighAccuracy": false,
      "geofenceProximityRadius": 1000,
      "geofenceTemplate": "",
      "headers": {},
      "headlessJobService": "com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask",
      "heartbeatInterval": -1,
      "httpRootProperty": "location",
      "httpTimeout": 60000,
      "isMoving": false,
      "locationAuthorizationRequest": "WhenInUse",
      "locationTemplate": "",
      "locationTimeout": 60,
      "locationUpdateInterval": 10000,
      "locationsOrderDirection": "ASC",
      "logLevel": 5,
      "logMaxDays": 3,
      "maxBatchSize": -1,
      "maxDaysToPersist": 1,
      "maxRecordsToPersist": -1,
      "method": "POST",
      "minimumActivityRecognitionConfidence": 75,
      "motionTriggerDelay": 0,
      "notification": {
        "layout": "",
        "title": "",
        "text": "Location Service activated",
        "color": "",
        "channelName": "TSLocationManager",
        "channelId": "",
        "smallIcon": "",
        "largeIcon": "",
        "priority": 0,
        "sticky": false,
        "strings": {},
        "actions": []
      },
      "params": {},
      "persist": true,
      "persistMode": 2,
      "schedule": [],
      "scheduleUseAlarmManager": false,
      "speedJumpFilter": 300,
      "startOnBoot": false,
      "stationaryRadius": 25,
      "stopAfterElapsedMinutes": 0,
      "stopOnStationary": false,
      "stopOnTerminate": true,
      "stopTimeout": 5,
      "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
      "url": "",
      "useSignificantChangesOnly": false,
      "enabled": false,
      "schedulerEnabled": false,
      "trackingMode": 1,
      "odometer": 0,
      "isFirstBoot": false,
      "didLaunchInBackground": false,
      "didDeviceReboot": false
    }
I/TSLocationManager: [c.t.l.logger.LoggerFacade$a a] 
    ╔═════════════════════════════════════════════
    ║ DEVICE SENSORS
    ╠═════════════════════════════════════════════
    ╟─ ✅  ACCELEROMETER: {Sensor name="Goldfish 3-axis Accelerometer", vendor="The Android Open Source Project", version=1, type=1, maxRange=39.300102, resolution=2.480159E-4, power=3.0, minDelay=10000}
    ╟─ ✅  GYROSCOPE: {Sensor name="Goldfish 3-axis Gyroscope", vendor="The Android Open Source Project", version=1, type=4, maxRange=16.46, resolution=0.001, power=3.0, minDelay=10000}
    ╟─ ✅  MAGNETOMETER: {Sensor name="Goldfish 3-axis Magnetic field sensor", vendor="The Android Open Source Project", version=1, type=2, maxRange=2000.0, resolution=0.5, power=6.7, minDelay=10000}
    ╟─ ⚠️  SIGNIFICANT_MOTION:  none.  Motion-detection system performance will be degraded
    ╚═════════════════════════════════════════════
I/TSLocationManager: [c.t.l.logger.LoggerFacade$a a] 
      🎾  Start monitoring location-provider changes
D/TSLocationManager: [c.t.l.logger.LoggerFacade$a a] 
      ℹ️  PRUNE -1 days
I/TSLocationManager: [c.t.l.s.ActivityRecognitionService stop] 
      🔴  Stop motion-activity updates
I/TSLocationManager: [c.t.l.service.HeartbeatService stop] 
      🔴  Stop heartbeat
D/TSLocationManager: [c.t.l.http.HttpService stopMonitoringConnectivityChanges] 
      🔴  Stop monitoring connectivity changes
D/TSLocationManager: [c.t.l.g.TSGeofenceManager d] ℹ️  Persist monitored geofences: []
D/TSLocationManager: [c.t.l.g.TSGeofenceManager f] 
      🔴  Stop monitoring geofences
D/TSLocationManager: [c.t.l.adapter.TSConfig d] ℹ️   Persist config, dirty: [debug, desiredAccuracy, fastestLocationUpdateInterval, headlessJobService, locationAuthorizationRequest, locationUpdateInterval, logLevel]
W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/TSLocationManager: [c.t.locationmanager.util.c g] 
      ℹ️  LocationAuthorization: Permission granted
I/TSLocationManager: - Enable: false → true, trackingMode: 1
D/TSLocationManager: [c.t.l.http.HttpService startMonitoringConnectivityChanges] 
      🎾  Start monitoring connectivity changes
D/TSLocationManager: [c.t.l.device.DeviceSettings startMonitoringPowerSaveChanges] 
      🎾  Start monitoring powersave changes
I/TSLocationManager: [c.t.l.service.HeartbeatService stop] 
      🔴  Stop heartbeat
I/TSLocationManager: [c.t.locationmanager.util.c h] 
      🔵  LocationAuthorization: Requesting permission
I/TSLocationManager: [c.t.locationmanager.util.c$j onPermissionGranted] 
      ✅  LocationAuthorization: Permission granted
W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
I/TSLocationManager: [c.t.l.service.TrackingService changePace] 
      🔵  setPace: false → false
W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/TSLocationManager: [c.t.l.service.AbstractService start] 
      🎾  LocationRequestService [eventCount: 1]
I/TSLocationManager: [c.t.l.l.SingleLocationRequest startUpdatingLocation] 
      🔵  [SingleLocationRequest start, action: 1, requestId: 1]
I/TSLocationManager: [c.t.l.s.ActivityRecognitionService start] 
      🎾  Start motion-activity updates
D/TSLocationManager: [c.t.l.http.HttpService a] 
    ╔═════════════════════════════════════════════
    ║ 📶  Connectivity change: connected? true
    ╠═════════════════════════════════════════════
D/TSLocationManager: [c.t.l.service.AbstractService finish] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
D/TSLocationManager: [c.t.l.a.TSLocationManagerActivity execute] locationsettings
D/TSLocationManager: [c.t.l.adapter.TSConfig translateDesiredAccuracy] translateDesiredAccuracy (false): -1
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.demo, PID: 12462
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.demo/com.transistorsoft.locationmanager.activity.TSLocationManagerActivity}: java.lang.IllegalArgumentException: illegal priority: -1
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.IllegalArgumentException: illegal priority: -1
        at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.0.0:3)
        at com.google.android.gms.location.LocationRequest.setPriority(com.google.android.gms:play-services-location@@20.0.0:2)
        at com.transistorsoft.locationmanager.location.TSLocationManager.buildLocationRequest(Unknown Source:175)
        at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.checkLocationSettings(Unknown Source:8)
        at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.execute(Unknown Source:47)
        at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.onCreate(Unknown Source:14)
        at android.app.Activity.performCreate(Activity.java:8051)
        at android.app.Activity.performCreate(Activity.java:8031)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
E/TSLocationManager: [c.t.l.a.BackgroundGeolocation$w0 uncaughtException] 
      ‼️  Uncaught Exception: Unable to start activity ComponentInfo{com.test.demo/com.transistorsoft.locationmanager.activity.TSLocationManagerActivity}: java.lang.IllegalArgumentException: illegal priority: -1
    {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"backgroundPermissionRationale":{"title":"Allow {applicationName} to access this device's location even when closed or not in use?","message":"[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.","positiveAction":"Change to \"{backgroundPermissionOptionLabel}\"","negativeAction":""},"batchSync":false,"configUrl":"","debug":true,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableProviderChangeRecord":false,"disableStopDetection":false,"distanceFilter":10,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":1000,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"WhenInUse","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":10000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","channelId":"","smallIcon":"","largeIcon":"","priority":0,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":false,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":true,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":false,"didLaunchInBackground":false,"didDeviceReboot":false}
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.demo/com.transistorsoft.locationmanager.activity.TSLocationManagerActivity}: java.lang.IllegalArgumentException: illegal priority: -1
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.IllegalArgumentException: illegal priority: -1
        at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.0.0:3)
        at com.google.android.gms.location.LocationRequest.setPriority(com.google.android.gms:play-services-location@@20.0.0:2)
E/TSLocationManager:     at com.transistorsoft.locationmanager.location.TSLocationManager.buildLocationRequest(Unknown Source:175)
        at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.checkLocationSettings(Unknown Source:8)
        at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.execute(Unknown Source:47)
        at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.onCreate(Unknown Source:14)
        at android.app.Activity.performCreate(Activity.java:8051)
        at android.app.Activity.performCreate(Activity.java:8031)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
    	... 12 common frames omitted
```

**Comment by christocracy** [comment]
Embedding in native apps is not supported.
