### ISSUE TITLE
Geofence errors when subsequently removing location permission

### ISSUE THREAD

**Issue by joserocha3** [transistorsoft/flutter_background_geolocation#99]
## Your Environment
* Plugin version: 1.0.11
* Platform: Android
* OS version: Android 7.7.1
* Device manufacturer / model: Nexus 6
* Flutter info (`flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

• No issues found!
```

* Plugin config:
```dart
 bg.Config(
      desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
      persistMode: bg.Config.PERSIST_MODE_GEOFENCE,
      geofenceProximityRadius: 100000, // about 62 miles
      logLevel: bg.Config.LOG_LEVEL_ERROR,
      stopOnTerminate: false,
      enableHeadless: true,
      startOnBoot: true,
      autoSync: true,
      reset: _reset ?? true,
      // Do not record location event if more than 300 meters/second since last
      // recorded event - Android only, iOS does not allow mock locations on device
      speedJumpFilter: 300,
      foregroundService: true,
      disableLocationAuthorizationAlert: true,
      notification: bg.Notification(
        title: 'Zone Tracker',
        text: 'Search underway',
        channelName: 'Zone Tracker',
        color:
            '#${Constants.colors.primary.value.toRadixString(16).substring(2)}',
        smallIcon: 'drawable/ic_notification',
        largeIcon: 'drawable/ic_notification',
        priority: bg.Config.NOTIFICATION_PRIORITY_MIN,
      ),
    );
```

## Expected Behavior
Existing geofences should not cause an error. Even if location permissions are subsequently denied.

## Actual Behavior
An error is thrown when loading geofences. This happens when removing location permission after the plugin has already loaded geofences and previously had location permission.

## Steps to Reproduce
1. Start app.
2. Grant location permission.
3. Add geofences.
4. Close app.
5. Go to app settings and remove location permission.
6. Open app.

## Context
Trying to test some possible user scenarios. In this scenario the user is using the app successfully with geofences and has already granted location permission. Then user decides to deny location permission, and opens the app with the permissions denied.

## Debug logs
<details>
	<summary>Logs</summary>

```
   --------- beginning of system
2019-07-22 19:31:02.954 941-2132/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.dotdotdata.pointbee/.MainActivity bnds=[15,436][297,760] (has extras)} from uid 10043 on display 0
2019-07-22 19:31:02.970 941-954/? W/BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 pkg=com.google.android.googlequicksearchbox (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.reflection.ReflectionReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.google.android.googlequicksearchbox (uid 10043)
2019-07-22 19:31:02.978 941-954/? W/BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 pkg=com.google.android.gms (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.google.android.googlequicksearchbox (uid 10043)
2019-07-22 19:31:03.089 1986-2247/? I/MicroDetector: Keeping mic open: false
2019-07-22 19:31:03.090 1986-21219/? I/AudioController: internalShutdown
2019-07-22 19:31:03.091 1986-21877/? I/MicroRecognitionRunner: Stopping hotword detection.
2019-07-22 19:31:03.092 1986-21883/? I/DeviceStateChecker: DeviceStateChecker cancelled
2019-07-22 19:31:03.129 460-22934/? D/audio_hw_primary: disable_audio_route: usecase(8) reset and update mixer path: audio-record
2019-07-22 19:31:03.130 460-22934/? D/audio_hw_primary: disable_snd_device: snd_device(63: voice-rec-mic)
2019-07-22 19:31:03.136 460-819/? I/SoundTriggerHwService::Module: void android::SoundTriggerHwService::Module::onCallbackEvent(const sp<android::SoundTriggerHwService::CallbackEvent> &) mClient == 0
2019-07-22 19:31:03.137 1986-21219/? I/MicrophoneInputStream: mic_close  SR : 16000 CC : 16 SO : 1999
2019-07-22 19:31:03.137 1986-21219/? E/AudioSource: Stop listening is called on already closed AudioSource
2019-07-22 19:31:03.139 1986-21884/? I/MicroRecognitionRunner: Detection finished
2019-07-22 19:31:03.168 941-1511/? W/InputMethodManagerService: Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@1641bdb (uid=10043 pid=2071)
2019-07-22 19:31:03.189 941-961/? I/ActivityManager: Displayed com.dotdotdata.pointbee/.MainActivity: +209ms
2019-07-22 19:31:03.412 1633-1654/? E/GLMSImpl: original addGeofence() exception (before parcelling)
    java.lang.SecurityException: Geofence usage requires ACCESS_FINE_LOCATION permission
        at bfsp.a(:com.google.android.gms@17785015@17.7.85 (040300-253824076):78)
        at afgm.a(:com.google.android.gms@17785015@17.7.85 (040300-253824076))
        at aamg.a(:com.google.android.gms@17785015@17.7.85 (040300-253824076):1)
        at cwm.onTransact(:com.google.android.gms@17785015@17.7.85 (040300-253824076):4)
        at android.os.Binder.transact(Binder.java:499)
        at aand.onTransact(:com.google.android.gms@17785015@17.7.85 (040300-253824076):25)
        at android.os.Binder.execTransact(Binder.java:565)
2019-07-22 19:31:03.413 22644-22644/? E/TSLocationManager: [c.t.l.g.TSGeofenceManager$3 onFailure] 
      ⚠️  Failed to add geofences: 10: SecurityException: Geofence usage requires ACCESS_FINE_LOCATION permission
2019-07-22 19:31:03.577 1986-21882/? I/PBSessionCacheImpl: Deleted sessionId[2145942197163] from persistence.
2019-07-22 19:31:03.614 1986-2247/? W/SearchServiceCore: Abort, client detached.
2019-07-22 19:31:03.616 1986-2247/? I/StreamController: cleanUpControllerScope(nowcards-15-8467a6-81db)
2019-07-22 19:31:06.201 460-731/? D/audio_hw_primary: disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback speaker
```

</details>

**Comment by christocracy** [comment]
This error is supposed to happen.
```
Failed to add geofences: 10: SecurityException: Geofence usage requires ACCESS_FINE_LOCATION permission
2
```

Your app is not crashing, is it?

**Comment by joserocha3** [comment]
It was not crashing, but it would "freeze". I am try/catching all plugin calls so I was thinking it was not handling an error on the native side.

I am using a new build from this morning and it does not seem to have the issue. The apps loads as expected after location is denied. I will reopen if I see this again.
