### ISSUE TITLE
ClassCastException: Cannot cast java.lang.SecurityException to com.transistorsoft.xms.g.common.api.ApiException

### ISSUE THREAD

**Issue by choim4389** [transistorsoft/flutter_background_geolocation#996]
## Your Environment
* Plugin version: 4.10.0
* Platform: Android
* OS version: 13
* Device manufacturer / model: Galaxy S20
* Flutter info (`flutter doctor`):  Flutter 3.7.5
* Plugin config:
```dart <-- Syntax highlighting: DO NOT REMOVE -->
bg.Config(
      isMoving: true,
      desiredAccuracy: Platform.isAndroid ? bg.Config.DESIRED_ACCURACY_HIGH : bg.Config.DESIRED_ACCURACY_NAVIGATION,
      allowIdenticalLocations: true,
      stopOnTerminate: false,
      disableStopDetection: true,
      disableMotionActivityUpdates: true,
      startOnBoot: true,
      pausesLocationUpdatesAutomatically: false,
      persistMode: bg.Config.PERSIST_MODE_LOCATION,
      maxRecordsToPersist: 1,
      locationAuthorizationRequest: 'WhenInUse',
      logLevel: kReleaseMode ? bg.Config.LOG_LEVEL_OFF : bg.Config.LOG_LEVEL_VERBOSE,
      notification : bg.Notification(
        channelId: 'channel_id',
        title: 'title',
        text: 'text',
        smallIcon: 'drawable/img_noti_small'
      )
    )
```

## Expected Behavior
no exception

## Actual Behavior
```
Fatal Exception: java.lang.ClassCastException: Cannot cast java.lang.SecurityException to com.transistorsoft.xms.g.common.api.ApiException
       at java.lang.Class.cast(Class.java:2479)
       at com.transistorsoft.locationmanager.service.ActivityRecognitionService.a(ActivityRecognitionService.java:8)
       at com.transistorsoft.xms.g.tasks.OnFailureListener$1.onFailure(:17)
       at com.google.android.gms.tasks.zzk.run(:31)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

## Steps to Reproduce

1. foreground service launched and running in background.
2. launch app from icon

**Comment by christocracy** [comment]
Confirmed.  Fix coming today.
